import type { PurchaseCase, PurchaseOverview } from "../types";
import { request } from "./_shared";

export const purchaseCasesApi = {
  createPurchaseCase:(slug:string,input:{caseId?:string;source:{kind:"document"|"bank_transaction"|"payable";id:number};documentationOutcome?:"ordinary_evidence_sufficient"|"alternative_evidence_assessed"|"unresolved";note?:string;idempotencyKey:string}) => request<{ok:true;purchaseCase:unknown}>(`/api/companies/${encodeURIComponent(slug)}/purchase-cases`,{method:"POST",headers:{"idempotency-key":input.idempotencyKey},body:JSON.stringify({...input,confirm:true})}),
  purchaseOverview:(slug:string,input:{from:string;to:string;includeProvisional?:boolean}) => request<{ok:true;overview:PurchaseOverview}>(`/api/companies/${encodeURIComponent(slug)}/purchase-overview?${new URLSearchParams(Object.entries(input).filter(([,value])=>value!==undefined).map(([key,value])=>[key,String(value)]))}`).then(result=>result.overview),
  listPurchaseCases:(slug:string) => request<{ok:true;purchaseCases:PurchaseCase[]}>(`/api/companies/${encodeURIComponent(slug)}/purchase-cases`).then(result=>result.purchaseCases),
  getPurchaseCase:(slug:string,caseId:string) => request<{ok:true;purchaseCase:PurchaseCase|null}>(`/api/companies/${encodeURIComponent(slug)}/purchase-cases/${encodeURIComponent(caseId)}`).then(result=>result.purchaseCase),
  reviewPurchaseCase:(slug:string,caseId:string,input:{expectedVersion:number;expectedSourceFingerprint:string;expectedPolicyEventHash?:string;documentationOutcome:"ordinary_evidence_sufficient"|"alternative_evidence_assessed"|"unresolved";note?:string;idempotencyKey:string}) => request<{ok:true;purchaseCase:PurchaseCase}>(`/api/companies/${encodeURIComponent(slug)}/purchase-cases/${encodeURIComponent(caseId)}/review`,{method:"POST",headers:{"idempotency-key":input.idempotencyKey},body:JSON.stringify({...input,confirm:true})}),
  reassessPurchaseCase:(slug:string,caseId:string,input:{expectedVersion:number;expectedSourceFingerprint:string;currentSourceFingerprint:string;expectedPolicyEventHash?:string;documentationOutcome:"ordinary_evidence_sufficient"|"alternative_evidence_assessed"|"unresolved";reason:string;idempotencyKey:string}) => request<{ok:true;purchaseCase:PurchaseCase}>(`/api/companies/${encodeURIComponent(slug)}/purchase-cases/${encodeURIComponent(caseId)}/reassess`,{method:"POST",headers:{"idempotency-key":input.idempotencyKey},body:JSON.stringify({...input,confirm:true})}),
  reviewPurchaseCaseGroup:(slug:string,input:{groupId?:string;members:Array<{caseId:string;expectedVersion:number;expectedSourceFingerprint:string}>;expectedPolicyEventHash?:string;documentationOutcome:"ordinary_evidence_sufficient"|"alternative_evidence_assessed"|"unresolved";note?:string;idempotencyKey:string}) => request<{ok:true;group:unknown}>(`/api/companies/${encodeURIComponent(slug)}/purchase-cases/group-review`,{method:"POST",headers:{"idempotency-key":input.idempotencyKey},body:JSON.stringify({...input,confirm:true})}),
};
