import { spawn, type ChildProcess } from 'node:child_process';
import { once } from 'node:events';
import { expect, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

let server: ChildProcess;
let url: string;
let date: string;
test.beforeAll(async () => {
  server = spawn('bun', ['../scripts/tasks-live-server.ts'], { cwd: process.cwd(), stdio: ['ignore', 'pipe', 'pipe'] });
  let output = '';
  let errors = '';
  server.stderr!.on('data', chunk => { errors += chunk; });
  await new Promise<void>((resolve, reject) => {
    const timeout = setTimeout(() => reject(new Error(`Synthetic server did not start: ${errors}`)), 20_000);
    server.once('exit', code => { clearTimeout(timeout); reject(new Error(`Synthetic server exited ${code}: ${errors}`)); });
    server.stdout!.on('data', chunk => {
      output += chunk;
      const line = output.split('\n').find(line => line.startsWith('{"url":'));
      if (line) { ({ url, date } = JSON.parse(line)); clearTimeout(timeout); resolve(); }
    });
  });
});
test.afterAll(async () => { if (server && server.exitCode === null) { const exited = once(server, 'exit'); server.kill('SIGTERM'); await exited; } });

test('real server persists one task through all views, references, reminders and documented completion', async ({ page, request }) => {
  await page.goto(`${url}/opgaver`);
  await expect(page.getByRole('heading', { name: 'Opgaver', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Fælles økonomimøde', exact: true })).toHaveCount(1);
  await page.getByRole('link', { name: 'Kontrollér månedens dokumentation', exact: true }).click();
  await page.getByRole('link', { name: 'knowledge: page-month-review' }).click();
  await expect(page.getByRole('heading', { name: 'Syntetisk månedsplaybook' })).toBeVisible();
  expect(await page.locator('article script').count()).toBe(0);
  await page.getByRole('link', { name: 'Tilbage til opgaven', exact: true }).click();
  await page.getByRole('link', { name: 'Tilbage til opgaver', exact: true }).click();
  await page.getByRole('button', { name: 'Opret opgave', exact: true }).click();
  const editor = page.getByRole('dialog', { name: 'Opret opgave' });
  await editor.getByLabel('Titel', { exact: true }).fill('Afklar syntetisk kontrakt');
  await editor.getByLabel('Opgavens selskab eller fælles scope').selectOption('green-aps');
  await editor.locator('summary').click();
  await editor.getByLabel('Arbejdsdato', { exact: true }).fill(date);
  const deadline = new Date(Date.parse(`${date}T12:00:00Z`) + 86_400_000).toISOString().slice(0, 10);
  await editor.getByLabel('Frist', { exact: true }).fill(deadline);
  await editor.getByLabel('Grundlag for fristen').fill('Syntetisk aftale');
  await editor.getByLabel('Kræv afslutningsbevis').check();
  await editor.getByRole('button', { name: 'Gem opgave' }).click();
  await expect(editor).toHaveCount(0);
  const response = await request.get(`${url}/api/tasks`);
  const created = (await response.json()).tasks.find((task: { title: string }) => task.title === 'Afklar syntetisk kontrakt');
  expect(created.taskId).toBeTruthy();
  await page.goto(`${url}/companies/green-aps/opgaver`);
  await expect(page.getByRole('link', { name: 'Afklar syntetisk kontrakt', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Kalender', exact: true }).click();
  await page.getByLabel('Kalendervisning').selectOption('agenda');
  await expect(page.getByRole('link', { name: 'Afklar syntetisk kontrakt', exact: true })).toHaveCount(2);
  await page.getByRole('button', { name: 'Kanban', exact: true }).click();
  await page.getByRole('button', { name: 'Tilpas kolonner' }).click();
  const board = page.getByRole('dialog', { name: 'Tilpas kolonner' });
  await board.getByRole('button', { name: 'Tilføj kolonne' }).click();
  await board.getByLabel('Kolonnenavn 5').fill('Hos revisor');
  await board.getByRole('button', { name: 'Vis konsekvenser' }).click();
  await board.getByRole('button', { name: 'Anvend viste ændringer' }).click();
  await expect(board).toHaveCount(0);
  const card = page.locator(`[data-task-id="${created.taskId}"]`);
  await card.getByLabel('Flyt Afklar syntetisk kontrakt').selectOption({ label: 'Hos revisor · Afventer' });
  await card.getByRole('button', { name: 'Flyt opgave' }).click();
  await expect(page.getByRole('region', { name: 'Kolonne Hos revisor' })).toContainText('Afklar syntetisk kontrakt');
  await page.goto(`${url}/opgaver?view=year`);
  await page.getByRole('button', { name: 'Årshjul', exact: true }).click();
  await expect(page.getByLabel('Årshjul', { exact: true })).toContainText('Månedlig afstemning');
  await page.getByRole('button', { name: 'Liste', exact: true }).click();
  await page.getByRole('link', { name: 'Afklar syntetisk kontrakt', exact: true }).click();
  await page.getByRole('button', { name: 'Påmindelser', exact: true }).click();
  const reminder = page.getByRole('dialog', { name: 'Påmindelser i Rentemester' });
  await reminder.getByLabel('Aktivér denne påmindelsesplan').check();
  await reminder.getByRole('button', { name: 'Gem påmindelsesplan' }).click();
  await expect(reminder).toHaveCount(0);
  await expect(page.getByRole('main')).toContainText('Aktiv levering');
  await page.getByRole('button', { name: 'Afslut med dokumentation' }).click();
  const complete = page.getByRole('dialog', { name: 'Afslut opgave' });
  await complete.getByLabel('Afslutningsnote eller begrundelse').fill('Syntetisk kontrakt bekræftet');
  await complete.getByLabel('Sikre referencer').fill('external_receipt:SYNTHETIC-RECEIPT');
  await complete.getByRole('button', { name: 'Gem afslutning' }).click();
  await expect(complete).toHaveCount(0);
  await expect(page.getByRole('main')).toContainText('Oplyst af brugeren');
  await expect(page.getByRole('main')).toContainText('Inaktiv levering');
  const final = await (await request.get(`${url}/api/tasks/${created.taskId}`)).json();
  expect(final.task.taskId).toBe(created.taskId);
  expect(final.task.status).toBe('done');
  expect(final.task.completion.references[0].ref).toBe('SYNTHETIC-RECEIPT');
  expect(final.history.map((event: { operation: string }) => event.operation)).toContain('completed');
  await page.setViewportSize({ width: 320, height: 844 });
  await page.goto(`${url}/opgaver?view=calendar`);
  await expect(page.getByLabel('Kalendervisning')).toHaveValue('agenda');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  const accessibility = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze();
  expect(accessibility.violations).toEqual([]);
});
