import * as stylex from "@stylexjs/stylex";
import { colors, controls, rounded, spacing, typography } from "../design/tokens.stylex";

export const dashboardStyles = stylex.create({
  overview: { minWidth: 0 },
  muted: { color: colors.inkMuted },
  paragraph: { marginBlock: spacing.md },
  heading: { fontFamily: typography.headlineFamily, fontWeight: 600, color: colors.ink, lineHeight: 1.25, marginTop: 0, marginBottom: spacing.md },
  link: {
    "color": colors.accent,
    "textDecoration": { "default": "none", ":hover": "underline" },
    "outlineWidth": { "default": null, ":focus-visible": controls.focusWidth },
    "outlineStyle": { "default": null, ":focus-visible": "solid" },
    "outlineColor": { "default": null, ":focus-visible": colors.info },
    "outlineOffset": { "default": null, ":focus-visible": controls.focusOffset },
  },
  actions: {
    "display": { "default": "flex", "@media print": "none" },
    "flexWrap": "wrap",
    "gap": spacing.sm,
  },
  card: { backgroundColor: colors.paperRaised, borderWidth: 1, borderStyle: "solid", borderColor: colors.border, borderRadius: rounded.lg, padding: spacing.md, minWidth: 0 },
  banner: { padding: spacing.sm, marginBottom: spacing.md, borderWidth: 1, borderStyle: "solid", borderColor: colors.warning, borderRadius: rounded.md, backgroundColor: colors.warningSoft },
  section: { marginTop: spacing.xl, marginBottom: spacing.lg },
  period: { marginTop: 0, marginBottom: spacing.md, fontSize: typography.sizeSm },
  kpis: {
    "display": "grid",
    "gridTemplateColumns": { "default": "repeat(3, minmax(0, 1fr))", "@media (max-width: 639px)": "minmax(0, 1fr)" },
    "gap": { "default": spacing.md, "@media (max-width: 639px)": spacing.sm },
    "marginBottom": { "default": spacing.xl, "@media (max-width: 639px)": spacing.lg },
  },
  kpi: {
    "display": "block",
    "backgroundColor": colors.paperRaised,
    "borderWidth": 1,
    "borderStyle": "solid",
    "borderColor": colors.border,
    "borderTopWidth": 3,
    "borderTopColor": colors.borderStrong,
    "borderRadius": rounded.lg,
    "paddingBlock": spacing.md,
    "paddingInline": spacing.lg,
    "minWidth": 0,
    "padding": { "default": null, "@media (max-width: 639px)": spacing.md },
  },
  emphasised: {
    "padding": { "default": spacing.lg, "@media (max-width: 639px)": spacing.md },
  },
  positiveBorder: { borderTopColor: colors.success },
  negativeBorder: { borderTopColor: colors.danger },
  positive: { color: colors.success },
  negative: { color: colors.danger },
  kpiLabel: { fontSize: typography.sizeSm, textTransform: "uppercase", letterSpacing: 0.5, color: colors.inkMuted },
  kpiValue: {
    "fontFamily": typography.monoFamily,
    "fontVariantNumeric": "tabular-nums",
    "fontSize": { "default": typography.size2xl, "@media (max-width: 639px)": typography.sizeXl },
    "fontWeight": 700,
    "marginTop": spacing.xs,
    "lineHeight": 1.2,
    "maxWidth": "100%",
    "whiteSpace": "nowrap",
    "overflowX": "auto",
  },
  prominentValue: {
    "fontSize": { "default": 34, "@media (max-width: 639px)": typography.sizeXl },
  },
  kpiSub: { fontSize: typography.sizeSm, color: colors.inkMuted, marginTop: spacing.xxs },
  cardLink: {
    "textDecoration": { "default": "none", ":hover": "none" },
    "color": "inherit",
    "borderColor": { "default": null, ":hover": colors.borderStrong },
    "backgroundColor": { "default": null, ":hover": colors.paper },
    "outlineWidth": { "default": null, ":focus-visible": controls.focusWidth },
    "outlineStyle": { "default": null, ":focus-visible": "solid" },
    "outlineColor": { "default": null, ":focus-visible": colors.accent },
    "outlineOffset": { "default": null, ":focus-visible": 2 },
  },
  keyFigures: {
    "display": "grid",
    "gridTemplateColumns": { "default": "repeat(2, minmax(0, 1fr))", "@media (max-width: 639px)": "minmax(0, 1fr)" },
    "gap": { "default": spacing.md, "@media (max-width: 639px)": spacing.sm },
    "marginBottom": { "default": spacing.xl, "@media (max-width: 639px)": spacing.lg },
  },
  keyFigure: { display: "flex", flexDirection: "column", gap: spacing.xxs, paddingBlock: spacing.sm, paddingInline: spacing.md },
  keyLabel: { fontSize: typography.sizeSm, textTransform: "uppercase", letterSpacing: 0.5, color: colors.inkMuted },
  keyValue: { fontFamily: typography.monoFamily, fontVariantNumeric: "tabular-nums", fontSize: typography.sizeXl, fontWeight: 700 },
  keyNote: { fontSize: typography.sizeXs, color: colors.inkMuted },
  statusGrid: {
    "display": "grid",
    "gridTemplateColumns": { "default": "repeat(2, minmax(0, 1fr))", "@media (max-width: 639px)": "minmax(0, 1fr)" },
    "gap": spacing.md,
  },
  statusCard: { display: "flex", flexDirection: "column", gap: spacing.xs },
  statusTitle: { margin: 0, fontSize: typography.sizeMd, textTransform: "uppercase", letterSpacing: 0.5, color: colors.inkMuted, fontFamily: typography.bodyFamily, fontWeight: 600 },
  statusFigure: { fontFamily: typography.monoFamily, fontVariantNumeric: "tabular-nums", fontSize: typography.sizeXl, fontWeight: 700 },
  statusNote: { fontSize: typography.sizeSm, margin: 0 },
  statusList: { listStyle: "none", marginTop: spacing.xxs, marginBottom: 0, padding: 0, display: "flex", flexDirection: "column", gap: spacing.xs, fontSize: typography.sizeSm },
  statusLink: {
    "color": "inherit",
    "textDecoration": { "default": "none", ":hover": "underline", ":focus-visible": "underline" },
  },
  warning: { color: colors.warning, fontWeight: 600 },
  success: { color: colors.success, fontWeight: 600 },
  flag: { fontSize: typography.sizeSm, paddingBlock: 3, paddingInline: spacing.xs, borderRadius: rounded.sm, fontWeight: 500 },
  criticalFlag: { color: colors.danger, backgroundColor: colors.dangerSoft },
  warningFlag: { color: colors.warning, backgroundColor: colors.warningSoft },
  taskRow: {
    "display": "flex",
    "flexWrap": "wrap",
    "alignItems": "flex-start",
    "justifyContent": "space-between",
    "gap": spacing.sm,
    "paddingBlock": spacing.xs,
    "borderTopWidth": { "default": null, ":not(:first-child)": 1 },
    "borderTopStyle": { "default": null, ":not(:first-child)": "solid" },
    "borderTopColor": { "default": null, ":not(:first-child)": colors.border },
  },
  taskText: { display: "flex", flexDirection: "column", gap: spacing.xxs, minWidth: 0, flex: "1 1 220px" },
  taskMessage: { display: "block" },
  taskAction: { margin: 0, fontSize: typography.sizeSm, color: colors.inkMuted, overflowWrap: "anywhere" },
  dialogWarning: { marginTop: spacing.sm, marginBottom: 0, padding: spacing.sm, borderRadius: rounded.md, backgroundColor: colors.warningSoft, borderWidth: 1, borderStyle: "solid", borderColor: colors.warning, color: colors.ink },
  recentEntries: { listStyle: "none", marginTop: spacing.xxs, marginBottom: 0, padding: 0, display: "flex", flexDirection: "column" },
  recentEntry: {
    "display": "flex",
    "justifyContent": "space-between",
    "alignItems": { "default": "baseline", "@media (max-width: 639px)": "stretch" },
    "gap": { "default": spacing.sm, "@media (max-width: 639px)": spacing.xxs },
    "paddingBlock": spacing.xs,
    "borderBottomWidth": { "default": 1, ":last-child": 0 },
    "borderBottomStyle": "solid",
    "borderBottomColor": colors.border,
    "fontSize": typography.sizeSm,
    "flexDirection": { "default": null, "@media (max-width: 639px)": "column" },
  },
  recentText: { flex: "1 1 auto", minWidth: 0, overflowWrap: "anywhere" },
  recentMeta: {
    "display": "flex",
    "alignItems": "baseline",
    "gap": spacing.sm,
    "flexShrink": 0,
    "justifyContent": { "default": null, "@media (max-width: 639px)": "space-between" },
  },
  entryDate: { fontFamily: typography.monoFamily, color: colors.inkMuted, whiteSpace: "nowrap" },
  recentAmount: { fontFamily: typography.monoFamily, fontVariantNumeric: "tabular-nums", fontWeight: 600 },
  getStarted: { display: "flex", flexDirection: "column", gap: spacing.sm, marginBottom: spacing.md, borderLeftWidth: 3, borderLeftColor: colors.accent },
  getStartedTitle: { margin: 0, fontSize: typography.sizeLg },
  table: { width: "100%", borderCollapse: "collapse", fontSize: typography.sizeSm, marginBlock: spacing.md },
  cell: { paddingBlock: spacing.xs, paddingInline: spacing.sm, borderBottomWidth: 1, borderBottomStyle: "solid", borderBottomColor: colors.border, textAlign: "left" },
  amount: { fontFamily: typography.monoFamily, fontVariantNumeric: "tabular-nums", textAlign: "right", whiteSpace: "nowrap" },
  list: { paddingInlineStart: spacing.lg },
  evidence: { marginBlock: spacing.sm },
  summary: { minHeight: controls.height, paddingBlock: spacing.xs, cursor: "pointer" },
});
