import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { useState } from "react";
import { useAsync } from "../lib/useAsync";
import { request } from "../lib/api/_shared";
import { PartySummary } from "../components/PartyLink";
import { FilterBar, PageState } from "../components/CockpitPrimitives";

type Hub={rows:Array<{partyId:string;name:string;roles:string[];recentActivity:string|null;computedSpend:number;partyLink:{href:string}}>};
type Profile={party:{name:string;kind:string;roles:Array<{role:string}>};computed:{period:{from:string;to:string};asOf:string;purchase:{amount:number};sales:{amount:number};sourceCoverage:{documents:number}};research:{assertions:Array<{field:string;value:string;source:string;observed_at:string;review_state:string}>;warnings:string[]};links:{documents:Array<{id:number;label:string;role:string}>;relations:Array<{type:string;companySlug:string;href:string}>}};
const endpoint=(slug:string,path="")=>`/api/companies/${encodeURIComponent(slug)}/party-hub${path}`;
export function PartyHubView(){const {slug=""}=useParams(),nav=useNavigate(),[params]=useSearchParams(),[query,setQuery]=useState("");const context=params.toString()?`?${params}`:"";const state=useAsync(()=>request<Hub>(`${endpoint(slug)}?query=${encodeURIComponent(query)}`),[slug,query]);if(state.loading&&!state.data)return <PageState kind="loading" title="Henter parter…"/>;if(state.error)return <PageState kind="error" title="Parter kunne ikke hentes" onRetry={state.reload}>{state.error}</PageState>;return <section className="page" data-cockpit-page="party-hub" data-evidence-issue="655"><header className="page-head"><div><p className="eyebrow">Viden</p><h2>Parter</h2><p className="muted">Søg og sortér canonical parter. Beløb vises kun fra eksplicitte partskoblinger.</p></div></header><FilterBar activeFilters={query ? [`Søgning: ${query}`] : []} onReset={()=>setQuery("")}><label>Søg <input type="search" aria-label="Søg parter" value={query} onChange={event=>setQuery(event.currentTarget.value)}/></label></FilterBar>{state.data?.rows.length?<ul className="card">{state.data.rows.map(row=><li key={row.partyId}><button type="button" className="link-button" onClick={()=>nav(`/companies/${slug}/parter/${row.partyId}${context}`)}><PartySummary name={row.name} roles={row.roles}/></button> <span className="muted"> · køb {row.computedSpend} · senest {row.recentActivity??"ingen aktivitet"}</span></li>)}</ul>:<PageState kind="empty" title="Ingen parter endnu">Der er ingen canonical parter med en synlig virksomhedsrolle.</PageState>}</section>}
export function PartyProfileView(){const {slug="",partyId=""}=useParams(),[params]=useSearchParams();const context=params.toString()?`?${params}`:"";const state=useAsync(()=>request<Profile>(endpoint(slug,`/${encodeURIComponent(partyId)}${context}`)),[slug,partyId,context]);if(state.loading&&!state.data)return <PageState kind="loading" title="Henter partsprofil"/>;if(state.error)return <PageState kind="error" title="Partsprofil kunne ikke hentes" onRetry={state.reload}>{state.error}</PageState>;const p=state.data!;return <section className="page" data-cockpit-detail-route="party-profile" data-evidence-issue="655"><Link className="btn secondary" to={`/companies/${slug}/parter${context}`}>Tilbage til parter</Link><header className="page-head"><div><p className="eyebrow">Canonical part</p><h2>{p.party.name}</h2><p className="muted">{p.party.kind} · {p.party.roles.map(r=>r.role).join(", ")}</p></div></header><section className="card"><h3>Beregnede Rentemester-tal</h3><p>Periode {p.computed.period.from} – {p.computed.period.to} · pr. {p.computed.asOf}</p><p>Køb: {p.computed.purchase.amount} · Salg: {p.computed.sales.amount}</p><p className="muted">Kildedækning: {p.computed.sourceCoverage.documents} eksplicit koblede bilag.</p></section><section className="card"><h3>Kildeunderbygget research og review</h3>{p.research.warnings.map(w=><p className="error" role="alert" key={w}>{w}</p>)}{p.research.assertions.length?<ul>{p.research.assertions.map((a,index)=><li key={index}>{a.field}: {a.value} <span className="muted">· {a.source} · {a.observed_at} · {a.review_state}</span></li>)}</ul>:<p className="muted">Ingen research-assertions.</p>}</section><section className="card"><h3>Forbundne kilder og relationer</h3><ul>{p.links.documents.map(d=><li key={d.id}>Bilag {d.label} · {d.role}</li>)}{p.links.relations.map(r=><li key={`${r.type}-${r.companySlug}`}><a href={r.href}>{r.type}: {r.companySlug}</a></li>)}</ul></section></section>}
