import { useNavigate, useParams } from "react-router-dom";
import { useState } from "react";
import { useAsync } from "../lib/useAsync";
import { request } from "../lib/api/_shared";
import { ErrorState, Loading } from "../components/Feedback";

type Hub={rows:Array<{partyId:string;name:string;roles:string[];recentActivity:string|null;computedSpend:number;partyLink:{href:string}}>};
type Profile={party:{name:string;kind:string;roles:Array<{role:string}>};computed:{period:{from:string;to:string};asOf:string;purchase:{amount:number};sales:{amount:number};sourceCoverage:{documents:number}};research:{assertions:Array<{field:string;value:string;source:string;observed_at:string;review_state:string}>;warnings:string[]};links:{documents:Array<{id:number;label:string;role:string}>;relations:Array<{type:string;companySlug:string;href:string}>}};
const endpoint=(slug:string,path="")=>`/api/companies/${encodeURIComponent(slug)}/party-hub${path}`;
export function PartyHubView(){const {slug=""}=useParams(),nav=useNavigate(),[query,setQuery]=useState("");const state=useAsync(()=>request<Hub>(`${endpoint(slug)}?query=${encodeURIComponent(query)}`),[slug,query]);if(state.loading&&!state.data)return <Loading label="Henter parter…"/>;if(state.error)return <ErrorState message={state.error} onRetry={state.reload}/>;return <section className="page"><header className="page-head"><div><p className="eyebrow">Viden</p><h2>Parter</h2><p className="muted">Søgbar oversigt over canonical parter. Beløb vises kun fra eksplicitte partskoblinger.</p></div></header><label>Søg <input aria-label="Søg parter" value={query} onChange={event=>setQuery(event.currentTarget.value)}/></label>{state.data?.rows.length?<ul className="card">{state.data.rows.map(row=><li key={row.partyId}><button type="button" className="link-button" onClick={()=>nav(`/companies/${slug}/parter/${row.partyId}`)}>{row.name}</button> <span className="muted">{row.roles.join(", ")} · køb {row.computedSpend} · senest {row.recentActivity??"ingen aktivitet"}</span></li>)}</ul>:<div className="card"><h3>Ingen parter endnu</h3><p className="muted">Der er ingen canonical parter med en synlig virksomhedsrolle.</p></div>}</section>}
export function PartyProfileView(){const {slug="",partyId=""}=useParams(),nav=useNavigate();const state=useAsync(()=>request<Profile>(endpoint(slug,`/${encodeURIComponent(partyId)}`)),[slug,partyId]);if(state.loading&&!state.data)return <Loading label="Henter partsprofil…"/>;if(state.error)return <ErrorState message={state.error} onRetry={state.reload}/>;const p=state.data!;return <section className="page"><button className="btn secondary" onClick={()=>nav(`/companies/${slug}/parter`)}>Tilbage til parter</button><header className="page-head"><div><p className="eyebrow">Canonical part</p><h2>{p.party.name}</h2><p className="muted">{p.party.kind} · {p.party.roles.map(r=>r.role).join(", ")}</p></div></header><section className="card"><h3>Beregnede Rentemester-tal</h3><p>Periode {p.computed.period.from} – {p.computed.period.to} · pr. {p.computed.asOf}</p><p>Køb: {p.computed.purchase.amount} · Salg: {p.computed.sales.amount}</p><p className="muted">Kildedækning: {p.computed.sourceCoverage.documents} eksplicit koblede bilag.</p></section><section className="card"><h3>Kildeunderbygget research</h3>{p.research.warnings.map(w=><p className="error" key={w}>{w}</p>)}{p.research.assertions.length?<ul>{p.research.assertions.map((a,index)=><li key={index}>{a.field}: {a.value} <span className="muted">· {a.source} · {a.observed_at} · {a.review_state}</span></li>)}</ul>:<p className="muted">Ingen research-assertions.</p>}</section><section className="card"><h3>Forbundne kilder og relationer</h3><ul>{p.links.documents.map(d=><li key={d.id}>Bilag {d.label} · {d.role}</li>)}{p.links.relations.map(r=><li key={`${r.type}-${r.companySlug}`}><a href={r.href}>{r.type}: {r.companySlug}</a></li>)}</ul></section></section>}
