import { useState, type FormEvent } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import { api } from "../lib/api";
import { formatKroner } from "../lib/format";
import { useAsync } from "../lib/useAsync";
import type { PurchaseCase, PurchaseNeedGroup, PurchaseOverview, PurchaseSourceFact } from "../lib/types";
import { ErrorState, Loading } from "../components/Feedback";
import { ConfirmDialog } from "../components/ConfirmDialog";

const today=()=>new Date().toISOString().slice(0,10);
const yearStart=()=>`${new Date().getUTCFullYear()}-01-01`;
const sourceLabel=(source:PurchaseCase["source"])=>source.kind==="document"?`Bilag #${source.id}`:source.kind==="bank_transaction"?`Bankpost #${source.id}`:`Leverandørfaktura #${source.id}`;
const SourceFacts=({fact,slug}:{fact:PurchaseSourceFact|undefined;slug:string})=><span>{fact?.date??"Dato ukendt"} · {fact?.supplier??"Leverandør ukendt"} · {fact?.amount==null?"Beløb ukendt":formatKroner(fact.amount,fact.currency??"DKK")}{fact?.documentId!=null&&<> · <Link to={`/companies/${slug}/bilag?documentId=${fact.documentId}`}>Bilag #{fact.documentId}</Link></>}</span>;
const documentationLabel=(outcome:PurchaseCase["documentationOutcome"])=>outcome==="unresolved"?"Mangler review":outcome==="ordinary_evidence_sufficient"?"Almindeligt bilag vurderet":"Alternativ dokumentation vurderet";
type CaseAction={purchaseCase:PurchaseCase;outcome:"ordinary_evidence_sufficient"|"alternative_evidence_assessed";reassess:boolean};

export function PurchaseOverviewView(){
  const {slug=""}=useParams(); const [searchParams]=useSearchParams(); const requestedKind=searchParams.get("sourceKind"); const requestedId=searchParams.get("sourceId"); const contextKind=requestedKind==="document"||requestedKind==="bank_transaction"||requestedKind==="payable"?requestedKind:null; const contextId=requestedId&&Number.isInteger(Number(requestedId))&&Number(requestedId)>0?requestedId:null;
  const {sourceKind:initialSourceKind,sourceId:initialSourceId,fromContext:initialFromContext}=contextKind&&contextId?{sourceKind:contextKind,sourceId:contextId,fromContext:true}:{sourceKind:"document" as const,sourceId:"",fromContext:false};
  const [from,setFrom]=useState(yearStart); const [to,setTo]=useState(today); const [includeProvisional,setIncludeProvisional]=useState(true);
  const [selected,setSelected]=useState<PurchaseNeedGroup|null>(null); const [selectedMemberIds,setSelectedMemberIds]=useState<string[]>([]); const [caseAction,setCaseAction]=useState<CaseAction|null>(null); const [sourceKind,setSourceKind]=useState<"document"|"bank_transaction"|"payable">(initialSourceKind as "document"|"bank_transaction"|"payable"); const [sourceId,setSourceId]=useState(initialSourceId); const [fromContext,setFromContext]=useState(initialFromContext); const [createPending,setCreatePending]=useState(false); const [actionError,setActionError]=useState<string|null>(null);
  const state=useAsync<PurchaseOverview>(()=>api.purchaseOverview(slug,{from,to,includeProvisional}),[slug,from,to,includeProvisional]); const cases=useAsync(()=>api.listPurchaseCases(slug),[slug]); const policy=useAsync(()=>api.accountingApprovalPolicy(slug),[slug]);
  if(state.loading&&!state.data)return <Loading label="Henter købsoversigt…"/>;
  if(state.error||policy.error)return <ErrorState message={state.error??policy.error??"Købsoverblik kunne ikke hentes."} onRetry={()=>{state.reload();policy.reload();}}/>;
  const overview=state.data!; const reload=()=>{state.reload();cases.reload();};
  function create(event:FormEvent){event.preventDefault();if(!Number.isInteger(Number(sourceId))||Number(sourceId)<=0){setActionError("Kilde-id skal være et positivt heltal.");return;}setCreatePending(true);}
  async function confirmCreate(){try{await api.createPurchaseCase(slug,{source:{kind:sourceKind,id:Number(sourceId)},documentationOutcome:"unresolved",idempotencyKey:crypto.randomUUID()});setSourceId("");setCreatePending(false);reload();}catch(cause){setActionError(cause instanceof Error?cause.message:"Købscasen kunne ikke oprettes.");throw cause;}}
  async function confirmCaseAction(note:string){if(!caseAction)return;if(caseAction.reassess&&!note.trim())throw new Error("En begrundelse for genvurderingen er påkrævet.");const fresh=await api.getPurchaseCase(slug,caseAction.purchaseCase.caseId);if(!fresh)throw new Error("Casen findes ikke længere. Opdatér oversigten.");if(caseAction.reassess){if(!fresh.sourceStatus?.currentSourceFingerprint)throw new Error("Kilden mangler og kan ikke genvurderes.");await api.reassessPurchaseCase(slug,fresh.caseId,{expectedVersion:fresh.version,expectedSourceFingerprint:fresh.sourceFingerprint,currentSourceFingerprint:fresh.sourceStatus.currentSourceFingerprint,expectedPolicyEventHash:policy.data?.eventHash,documentationOutcome:caseAction.outcome,reason:note,idempotencyKey:crypto.randomUUID()});}else await api.reviewPurchaseCase(slug,fresh.caseId,{expectedVersion:fresh.version,expectedSourceFingerprint:fresh.sourceFingerprint,expectedPolicyEventHash:policy.data?.eventHash,documentationOutcome:caseAction.outcome,note,idempotencyKey:crypto.randomUUID()});setCaseAction(null);reload();}
  return <section className="statement"><div className="page-head"><div><h2>Købsoverblik</h2><p className="muted">Kildebaseret status og dokumenterede behov. Foreløbige beløb ændrer aldrig hovedbog eller momsindberetning.</p></div></div>
    {actionError&&<div className="card archived-notice" role="alert"><p>{actionError}</p></div>}<div className="row-actions"><label>Fra <input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>Til <input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label><label><input type="checkbox" checked={includeProvisional} onChange={event=>setIncludeProvisional(event.target.checked)}/> Vis foreløbig effekt</label></div>
    <div className="cards"><article className="card"><strong>{formatKroner(overview.basis.canonical.economicEffect.expense)}</strong><span>Bogført omkostning</span><p className="muted">Fra hovedbogen i perioden.</p></article><article className="card"><strong>{includeProvisional?formatKroner(overview.basis.provisional.economicEffect.expense):"Slået fra"}</strong><span>Foreløbig omkostning</span><p className="muted">Kun aktive, klassificerede drafts; ikke bogført.</p></article><article className="card"><strong>{includeProvisional?formatKroner(overview.basis.provisional.economicEffect.expectedVat):"Slået fra"}</strong><span>Forventet moms</span><p className="muted">Ikke klar til momsindberetning.</p></article></div>
    <form className="card" onSubmit={create}><h3>Åbn foreløbig købscase</h3><p className="muted">Knytter én eksisterende kilde til en arbejds-case. Den bogfører ikke og ændrer ikke momsstatus.</p>{fromContext?<div className="row-actions"><strong>Valgt kilde: {sourceLabel({kind:sourceKind,id:Number(sourceId)})}</strong><button type="button" className="btn secondary" onClick={()=>setFromContext(false)}>Vælg anden kilde</button><button className="btn" type="submit">Åbn case</button></div>:<div className="row-actions"><label>Kildetype <select value={sourceKind} onChange={event=>setSourceKind(event.target.value as typeof sourceKind)}><option value="document">Bilag</option><option value="bank_transaction">Bankpost</option><option value="payable">Leverandørfaktura</option></select></label><label>Kilde-id <input required inputMode="numeric" value={sourceId} onChange={event=>setSourceId(event.target.value)}/></label><button className="btn" type="submit">Åbn case</button></div>}</form>
    <div className="card statement-card"><h3>Åbne købscases</h3>{cases.loading&&!cases.data?<Loading label="Henter cases…"/>:cases.error?<p role="alert">Cases kunne ikke hentes: {cases.error}</p>:!cases.data?.length?<p className="muted">Ingen købscases endnu.</p>:<ul className="plain-list">{cases.data.map(purchaseCase=>{const stale=purchaseCase.sourceStatus?.status!=="current";return <li key={purchaseCase.caseId}><strong>{sourceLabel(purchaseCase.source)}</strong><p className="muted"><SourceFacts fact={purchaseCase.sourceFact} slug={slug}/></p><p className="muted">{documentationLabel(purchaseCase.documentationOutcome)} · {purchaseCase.accountingProgress==="posted"?"Bogført":"Ikke bogført"} · kilde: {purchaseCase.sourceStatus?.status??"ukendt"} · moms: {purchaseCase.vatEvidence.status}</p>{purchaseCase.accountingProgress==="unposted"&&!stale&&<span className="row-actions"><button type="button" className="btn secondary" onClick={()=>setCaseAction({purchaseCase,outcome:"ordinary_evidence_sufficient",reassess:false})}>Review almindeligt bilag</button><button type="button" className="btn secondary" onClick={()=>setCaseAction({purchaseCase,outcome:"alternative_evidence_assessed",reassess:false})}>Review alternativ dokumentation</button></span>}{purchaseCase.accountingProgress==="unposted"&&purchaseCase.sourceStatus?.status==="stale"&&<button type="button" className="btn secondary" onClick={()=>setCaseAction({purchaseCase,outcome:"ordinary_evidence_sufficient",reassess:true})}>Genvurdér ændret kilde</button>}{purchaseCase.sourceStatus?.status==="missing"&&<p role="alert">Kilden mangler; den kan ikke reviewes eller genvurderes.</p>}</li>;})}</ul>}</div>
    <div className="card statement-card"><h3>Grupperede behov</h3>{overview.groups.length===0?<p className="muted">Ingen åbne grupper i perioden.</p>:<ul className="plain-list">{overview.groups.map(group=>{const selectedIds=selected?.selectionHash===group.selectionHash?selectedMemberIds:group.members.map(member=>member.caseId);const selectedCount=selectedIds.length;return <li key={group.selectionHash}><strong>{group.need.question}</strong><p className="muted">{group.caseCount} eksakte cases · {group.need.key}</p><ul className="plain-list">{group.members.map(member=><li key={member.caseId} className="muted">{group.need.key==="documentation:unresolved"&&<label><input type="checkbox" checked={selectedIds.includes(member.caseId)} onChange={event=>{if(selected?.selectionHash!==group.selectionHash){setSelected(group);setSelectedMemberIds(event.target.checked?group.members.map(item=>item.caseId):group.members.filter(item=>item.caseId!==member.caseId).map(item=>item.caseId));}else setSelectedMemberIds(ids=>event.target.checked?[...ids,member.caseId]:ids.filter(id=>id!==member.caseId));}}/> Vælg</label>} {sourceLabel(member.source)} · <SourceFacts fact={member.sourceFact} slug={slug}/>kilde: {member.sourceStatus.status} · {member.need?.key??"intet åbent behov"}</li>)}</ul>{group.need.key==="documentation:unresolved"&&<><button type="button" className="btn secondary" disabled={selectedCount===0} onClick={()=>{setSelected(group);if(selected?.selectionHash!==group.selectionHash)setSelectedMemberIds(group.members.map(member=>member.caseId));}}>Review {selectedCount} valgt{selectedCount===1?"":"e"}</button>{selected?.selectionHash===group.selectionHash&&selectedCount===0&&<p role="alert">Vælg mindst én case før review.</p>}</>}</li>;})}</ul>}</div>
    {createPending&&<ConfirmDialog title="Åbn foreløbig købscase" body={<p>Casen bindes til den valgte kilde. Den bogfører ikke og godkender ikke moms.</p>} confirmLabel="Åbn case" onConfirm={confirmCreate} onClose={()=>setCreatePending(false)}/>}
    {caseAction&&<ConfirmDialog title={caseAction.reassess?"Genvurdér ændret købskilde":"Review købscase"} body={<p>{caseAction.reassess?"Du bekræfter en ny vurdering af den ændrede kilde. Den tidligere vurdering bevares i revisionssporet.":"Reviewet gælder den viste case og bogfører ikke eller ændrer momsstatus."}</p>} noteLabel={caseAction.reassess?"Begrundelse for genvurdering":"Review-note (valgfri)"} notePlaceholder={caseAction.reassess?"Hvad er ændret i kilden?":"Notér grundlaget for reviewet"} confirmLabel={caseAction.reassess?"Bekræft genvurdering":"Bekræft review"} onConfirm={confirmCaseAction} onClose={()=>setCaseAction(null)}/>}
    {selected&&<ConfirmDialog title="Review købsdokumentation" body={<p>Review kun de {selectedMemberIds.length} præcist valgte cases. Handlingen bogfører ikke og ændrer ikke momsstatus.</p>} confirmLabel="Bekræft review" confirmKind="primary" onConfirm={async note=>{const members=selected.members.filter(member=>selectedMemberIds.includes(member.caseId));if(members.length===0)throw new Error("Vælg mindst én case før review.");await api.reviewPurchaseCaseGroup(slug,{groupId:`ui-group-${crypto.randomUUID()}`,members:members.map(member=>({caseId:member.caseId,expectedVersion:member.version,expectedSourceFingerprint:member.sourceFingerprint})),expectedPolicyEventHash:policy.data?.eventHash,documentationOutcome:"ordinary_evidence_sufficient",note,idempotencyKey:crypto.randomUUID()});setSelected(null);setSelectedMemberIds([]);reload();}} onClose={()=>{setSelected(null);setSelectedMemberIds([]);}}/>}</section>;
}
