import { useMutationOutcome } from "../lib/useMutationOutcome";
import { useUnsavedChanges } from "../lib/useUnsavedChanges";
import { Button, Input, PageHeader, Select } from "../components/ui";
import { useRef, useState, type FormEvent } from "react";
import { useParams } from "react-router-dom";
import { Banner, ErrorState, Loading } from "../components/Feedback";
import { useAsync } from "../lib/useAsync";
import { api } from "../lib/api";
import { workspaceInboxApi } from "../lib/api/workspace-inbox";

/** One deliberately small inbox: ingest → inspect → explicitly assign → handoff. */
export function WorkspaceInboxView(){const {slug=""}=useParams();const data=useAsync((signal)=>workspaceInboxApi.list(slug, { signal }),[slug]);const companies=useAsync((signal)=>api.companies({ signal }),[]);const [file,setFile]=useState<File>();const [target,setTarget]=useState("");const [message,setMessage]=useState<string>();const ingestKey = useRef<string>();const outcome = useMutationOutcome(() => data.reload());
  useUnsavedChanges(Boolean(file));const reload=()=>data.reload();async function ingest(event:FormEvent){event.preventDefault();
    if (outcome.isBlocked()) return;if(!file){setMessage("Vælg en fil.");return;}try{if (!ingestKey.current) ingestKey.current = crypto.randomUUID();const encoded=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(new Error("Filen kunne ikke læses."));r.onload=()=>resolve(String(r.result).split(",")[1]??"");r.readAsDataURL(file);});await workspaceInboxApi.ingest(slug,{idempotencyKey:ingestKey.current,bytesBase64:encoded,filename:file.name,mimeType:file.type||"application/octet-stream",transport:"upload",receivedAt:new Date().toISOString(),metadata:{},candidates:[]}).catch(outcome.reject);setFile(undefined);ingestKey.current=undefined;setMessage("Kilden er lagt i workspace-indbakken uden bogføring.");reload();}catch(error){setMessage(error instanceof Error?error.message:"Indlæsning fejlede.");}}async function act(sourceId:string,action:"assign"|"complete"){
    if (outcome.isBlocked()) return;try{if(!target){setMessage("Vælg målvirksomheden efter gennemgang.");return;}await workspaceInboxApi[action](slug,sourceId,target).catch(outcome.reject);setMessage(action==="assign"?"Ruting er godkendt. Håndoff er stadig et separat trin.":"Kilden er overdraget én gang til virksomhedens dokumentflow.");reload();}catch(error){setMessage(error instanceof Error?error.message:"Handlingen fejlede.");}}if(data.loading&&!data.data)return <Loading label="Henter workspace-indbakke…"/>;if(data.error)return <ErrorState message={data.error} onRetry={reload}/>;return <section className="page">
    {outcome.feedback}<PageHeader title="Fælles dokumentindbakke" actions={<><Button variant="secondary" type="button" className="secondary" onClick={reload}>Opdater</Button></>}><div><p className="eyebrow">Workspace</p><p className="muted">Kilder ligger uden for hovedbogen, indtil en autoriseret bruger har valgt virksomhed og fuldført overdragelsen.</p></div></PageHeader><section className="card"><h3>Indlæs kilde</h3><form onSubmit={event=>void ingest(event)}><Input disabled={outcome.blocked} aria-label="Inbox-fil" type="file" onChange={event=>setFile(event.target.files?.[0])}/><Button requiredPermission="company.documents.upload" variant="secondary" className="btn secondary" type="submit" disabled={outcome.blocked || (!file)}>Indlæs til indbakke</Button></form></section><section className="card"><h3>Afventer review</h3><label>Målvirksomhed efter gennemgang<Select disabled={outcome.blocked} aria-label="Inbox målvirksomhed" value={target} onChange={event=>setTarget(event.target.value)}><option value="">Vælg virksomhed</option>{companies.data?.filter(company=>!company.archived).map(company=><option key={company.slug} value={company.slug}>{company.name}</option>)}</Select></label>{data.data?.rows.length?<ul>{data.data.rows.map(source=><li key={source.sourceId}><strong>{source.filename}</strong> <span className="muted">{source.transport} · SHA-256 {source.sha256.slice(0,12)}… · {(source.exception?.code??source.assignments.map(item=>`${item.companySlug}: ${item.state}`).join(", "))||"kræver review"}</span><div className="modal-actions"><Button disabled={outcome.blocked} requiredPermission="company.documents.upload" variant="secondary" type="button" className="secondary" onClick={()=>void act(source.sourceId,"assign")}>Godkend ruting</Button><Button disabled={outcome.blocked} requiredPermission="company.documents.upload" variant="secondary" type="button" className="secondary" onClick={()=>void act(source.sourceId,"complete")}>Fuldfør handoff</Button></div></li>)}</ul>:<p className="muted">Ingen synlige kilder.</p>}</section>{message&&<Banner kind={message.includes("fejl")||message.includes("Angiv")?"error":"success"}>{message}</Banner>}</section>}
