import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { applyBookkeepingBatch, approveBookkeepingBatchPlan, createBookkeepingBatchRun, getBookkeepingBatchState, planBookkeepingBatch } from "../../core/bookkeeping-batch";
import { envelopeShape, wrapCoreResult } from "../envelope";
import { confirmField, withCompanyDb, withCompanyDbConfirmed } from "../tool-runtime";
import { currentMcpAuthenticatedPrincipal } from "../security";
const dates = { companyId: z.number().int().positive(), accountingFrom: z.string(), accountingTo: z.string(), bankFrom: z.string(), bankTo: z.string() };
export function registerBookkeepingBatchTools(server: McpServer): void {
	 const principal=()=>{const value=currentMcpAuthenticatedPrincipal();return value?{kind:value.kind,subjectId:value.subjectId}:undefined};
	 const state=getBookkeepingBatchState;
	 const persistBatch = (toolName: string, compatibilityDryRun: boolean) => withCompanyDbConfirmed<any>(server,toolName,({db,actor,args})=>{const plan=planBookkeepingBatch(db,args);const run=createBookkeepingBatchRun(db,{...plan,runKey:args.runKey,actor:actor.createdBy,principal:principal()});const result={ok:true,...(compatibilityDryRun?{dryRun:true}:{}),runId:run.runId,duplicate:run.duplicate,plan:run.plan,state:state(db,run.runId)};return wrapCoreResult(result);});
	 server.registerTool("bookkeeping_batch_plan", { title:"Plan bookkeeping batch",description:"Read-only deterministic plan and hash. It never persists, approves or applies.",inputSchema:{company:z.string().min(1),...dates},outputSchema:envelopeShape,annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},withCompanyDb<any>(server,({db,args})=>wrapCoreResult({ok:true,dryRun:true,plan:planBookkeepingBatch(db,args)})));
	 server.registerTool("bookkeeping_batch_persist", { title:"Persist bookkeeping batch plan",description:"Persist an exact reviewed plan. This does not approve or apply it. Requires actor attribution and confirm:true; identical runKey retries are idempotent. write-reversible.",inputSchema:{company:z.string().min(1),runKey:z.string().min(1),...dates,confirm:confirmField},outputSchema:envelopeShape,annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false}},persistBatch("bookkeeping_batch_persist",false));
	 server.registerTool("bookkeeping_batch_dry_run", { title: "Persist bookkeeping batch plan (deprecated alias)", description: "Deprecated compatibility alias for bookkeeping_batch_persist. Persists a canonical immutable review revision; requires actor attribution and confirm:true; identical runKey retries are idempotent. write-reversible.", inputSchema: { company:z.string().min(1),runKey:z.string().min(1),...dates,confirm:confirmField }, outputSchema: envelopeShape, annotations: { readOnlyHint:false, destructiveHint:false, idempotentHint:true, openWorldHint:false } }, persistBatch("bookkeeping_batch_dry_run",true));
 server.registerTool("bookkeeping_batch_approve", { title:"Approve bookkeeping batch",description:"Approve exactly one reviewed plan hash. A stable principal may not approve its own plan. Requires actor attribution and confirm:true; retry reads the existing approval. write-reversible.",inputSchema:{company:z.string().min(1),runId:z.number().int().positive(),planHash:z.string().regex(/^[a-f0-9]{64}$/),confirm:confirmField},outputSchema:envelopeShape,annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false}},withCompanyDbConfirmed<any>(server,"bookkeeping_batch_approve",({db,actor,args})=>wrapCoreResult({...approveBookkeepingBatchPlan(db,{runId:args.runId,planHash:args.planHash,actor:actor.createdBy,principal:principal()}),state:state(db,args.runId)})));
 server.registerTool("bookkeeping_batch_apply", { title: "Apply bookkeeping batch", description: "Applies or resumes only the exact approved run and reviewed plan hash; it never replans or approves. Requires actor attribution and confirm:true; retry resumes the durable run. write-irreversible.", inputSchema: { company:z.string().min(1),runId:z.number().int().positive(),planHash:z.string().regex(/^[a-f0-9]{64}$/),confirm:confirmField }, outputSchema: envelopeShape, annotations: { readOnlyHint:false, destructiveHint:false, idempotentHint:true, openWorldHint:false } }, withCompanyDbConfirmed<any>(server,"bookkeeping_batch_apply",({db,actor,args}) => wrapCoreResult({ ...applyBookkeepingBatch(db,{runId:args.runId,planHash:args.planHash,actor:actor.createdBy,principal:principal()}),runId:args.runId,planHash:args.planHash,state:state(db,args.runId) })));
 server.registerTool("bookkeeping_batch_status", { title:"Read bookkeeping batch evidence",description:"Read parsed run, events, attempts, receipts and final checks.",inputSchema:{company:z.string().min(1),runId:z.number().int().positive()},outputSchema:envelopeShape,annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},withCompanyDb<any>(server,({db,args})=>wrapCoreResult({ok:true,state:state(db,args.runId)})));
}
