/** MCP parity for the workspace party and corporate-record registries (#573/#575).
 * `company` is an explicit visibility anchor.  The core registry remains
 * workspace-scoped, while the adapter filters before pagination/readback so a
 * caller never learns an inaccessible company relationship. */
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { resolveConfiguredWorkspaceRoot } from "../../core/workspace";
import { openWorkspaceControlDb, openWorkspaceControlReadOnlyDb } from "../../core/workspace-control";
import { approvePartyMerge, createParty, inspectVisibleParty, linkPartyRole, proposePartyMerge, searchParties } from "../../core/party-registry";
import { enrichCorporateRecord, ingestCorporateRecord, inspectCorporateRecord, inspectVisibleCorporateRecord, linkCorporateRecord, listCorporateRecords, readCorporateRecordBytes, supersedeCorporateRecord } from "../../core/corporate-records";
import { companyKnowledgeHistory, inspectCompanyKnowledgeAssertion, proposeCompanyKnowledge, queryCompanyKnowledge, reviewCompanyKnowledge, supersedeCompanyKnowledge, COMPANY_KNOWLEDGE_PREDICATES } from "../../core/company-knowledge";
import { applyOwnershipSnapshot, ownershipHistory, proposeOwnershipSnapshot, queryOwnershipGraph, reviewOwnershipSnapshot } from "../../core/ownership-graph";
import { authorizeWorkspaceRoute } from "../../core/workspace-access";
import { getAccountingApprovalPolicy, setAccountingApprovalPolicy } from "../../core/accounting-approval-policy";
import { currentMcpAuthenticatedPrincipal } from "../security";
import { envelopeShape, errorEnvelope, successEnvelope } from "../envelope";
import { confirmField, withCompanyDb, withCompanyDbConfirmed } from "../tool-runtime";

const company = z.string().min(1);
const bytes = z.string().min(1).max(24 * 1024 * 1024).transform((value, ctx) => { try { return new Uint8Array(Buffer.from(value, "base64")); } catch { ctx.addIssue({ code:"custom", message:"bytesBase64 must be base64" }); return z.NEVER; } });
const workspace = () => resolveConfiguredWorkspaceRoot() ?? (() => { throw new Error("RENTEMESTER_WORKSPACE is required for workspace registry tools"); })();
function visibleParty(id:string, slug:string) { const db=openWorkspaceControlReadOnlyDb(workspace()); try { return inspectVisibleParty(db,id,new Set([slug])); } finally {db.close();} }
function visibleRecord(id:string, slug:string) { const db=openWorkspaceControlReadOnlyDb(workspace()); try { return inspectVisibleCorporateRecord(db,id,new Set([slug])); } finally {db.close();} }
const write = { readOnlyHint:false, destructiveHint:false, idempotentHint:false, openWorldHint:false } as const;
const read = { readOnlyHint:true, destructiveHint:false, idempotentHint:true, openWorldHint:false } as const;
const knowledgePrincipal=()=>{const p=currentMcpAuthenticatedPrincipal();return p?{kind:"service_account" as const,id:p.subjectId}:{kind:"local_operator" as const,id:"localhost"};};
const ownershipFact = z.object({owner:z.discriminatedUnion("kind",[z.object({kind:z.literal("company"),companySlug:z.string().min(1)}),z.object({kind:z.literal("party"),partyId:z.string().min(3)})]),ownedCompanySlug:z.string().min(1),validFrom:z.string().min(10),validToExclusive:z.string().min(10).optional(),economicBasisPoints:z.number().int().min(0).max(10000).optional(),economicIntervalBasisPoints:z.object({min:z.number().int().min(0).max(10000),max:z.number().int().min(0).max(10000)}).optional(),votingBasisPoints:z.number().int().min(0).max(10000).optional(),controlType:z.enum(["equity","voting","board","agreement","other"]),shareClass:z.string().min(1).optional(),jurisdiction:z.string().length(2),evidenceRefs:z.array(z.string().min(1)).min(1).max(32)});
function visibleOwnershipSnapshot(snapshot:any):boolean { const principal=currentMcpAuthenticatedPrincipal(); if(!principal||typeof snapshot?.snapshotId!=="string")return false; const db=openWorkspaceControlReadOnlyDb(workspace()); try { const row=db.query("SELECT canonical_facts FROM rm_ownership_source_snapshots WHERE snapshot_id=?").get(snapshot.snapshotId) as {canonical_facts?:string}|null; let facts:any[]=[]; try { facts=JSON.parse(row?.canonical_facts??"[]"); } catch { return false; } const endpoints=new Set<string>(); for(const fact of facts){if(typeof fact?.ownedCompanySlug==="string")endpoints.add(fact.ownedCompanySlug);if(fact?.owner?.kind==="company"&&typeof fact.owner.companySlug==="string")endpoints.add(fact.owner.companySlug);} return endpoints.size>0&&[...endpoints].every(companySlug=>authorizeWorkspaceRoute(db,workspace(),{userId:principal.subjectId,companySlug,permission:"company.ownership.read"}).allowed); } finally {db.close();} }

export function registerWorkspaceRegistryTools(server:McpServer):void {
  server.registerTool("accounting_approval_policy_get", { title: "Read company approval policy", description: "Reads the effective versioned company approval policy. Absence means the fail-safe independent-review default. Historical elevated policies are explicitly reported as not enforced; this never changes a ledger.", inputSchema: { company, riskClass: z.enum(["normal", "elevated"]).optional() }, outputSchema: envelopeShape, annotations: read }, withCompanyDb<any>(server, ({ args }) => {
    const db = openWorkspaceControlReadOnlyDb(workspace());
    try { return successEnvelope({ policy: getAccountingApprovalPolicy(db, args.company, args.riskClass) }); }
    finally { db.close(); }
  }));
  server.registerTool("accounting_approval_policy_set", { title: "Set company approval policy", description: "Appends a company-scoped normal approval policy version. Elevated activation is rejected as ELEVATED_APPROVAL_POLICY_UNSUPPORTED until a canonical risk classifier exists. It requires an authenticated principal with company-admin membership, actor attribution and confirm:true; it never authorizes by actor alone or changes a ledger.", inputSchema: { company, riskClass: z.enum(["normal", "elevated"]).optional(), reviewMode: z.enum(["sole_authorized_bookkeeper", "independent_reviewer"]), expectedEventHash: z.string().regex(/^[a-f0-9]{64}$/).nullable().optional(), confirm: confirmField }, outputSchema: envelopeShape, annotations: write }, withCompanyDbConfirmed<any>(server, "accounting_approval_policy_set", ({ args, actor }) => {
    const principal = currentMcpAuthenticatedPrincipal();
    if (!principal) throw new Error("authenticated workspace service principal is required");
    const db = openWorkspaceControlDb(workspace());
    try {
      return successEnvelope(setAccountingApprovalPolicy(db, workspace(), {
        scope: { kind: "company", companySlug: args.company }, riskClass: args.riskClass ?? "normal", reviewMode: args.reviewMode,
        expectedEventHash: args.expectedEventHash ?? null, principalId: principal.subjectId, actor: actor.createdBy, confirm: true,
      }));
    } finally { db.close(); }
  }));
  server.registerTool("workspace_party_search",{title:"Search visible workspace parties",description:"Lists canonical parties only when they have a role in the explicitly authorized company. Filtering occurs before pagination.",inputSchema:{company,query:z.string().optional(),cursor:z.number().int().nonnegative().optional(),limit:z.number().int().min(1).max(100).optional()},outputSchema:envelopeShape,annotations:read},withCompanyDb<any>(server,({args})=>{const db=openWorkspaceControlReadOnlyDb(workspace());try{return successEnvelope(searchParties(db,{query:args.query,companySlugs:new Set([args.company]),cursor:args.cursor,limit:args.limit}));}finally{db.close();}}));
  server.registerTool("workspace_party_inspect",{title:"Inspect a visible workspace party",description:"Returns canonical/provenance evidence with inaccessible company roles removed.",inputSchema:{company,partyId:z.string().min(3)},outputSchema:envelopeShape,annotations:read},withCompanyDb<any>(server,({args})=>{const party=visibleParty(args.partyId,args.company);return party?successEnvelope({party}):errorEnvelope("party not found",{code:"PARTY_NOT_FOUND"});}));
  server.registerTool("workspace_party_create",{title:"Create canonical workspace party",description:"Creates source-backed canonical identity; it never creates a ledger record. Link a company role separately.",inputSchema:{company,kind:z.enum(["person","organization","public_authority","financial_institution"]),name:z.string().min(1),aliases:z.array(z.string()).max(16).optional(),identifiers:z.array(z.object({country:z.string(),identifier:z.string().optional(),identifierKind:z.enum(["dk_cvr","eu_vat","non_eu"])})).optional(),source:z.string().min(1),observedAt:z.string().min(1),reviewAssertion:z.string().min(1),partyId:z.string().optional(),confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"workspace_party_create",({args,actor})=>{const db=openWorkspaceControlDb(workspace());try{return successEnvelope({party:createParty(db,{...args,actor:actor.createdBy})});}finally{db.close();}}));
  server.registerTool("workspace_party_link_role",{title:"Link company-scoped party role",description:"Adds one company-local role/default profile without exposing or changing other companies.",inputSchema:{company,partyId:z.string().min(3),role:z.enum(["customer","vendor","owner","adviser","employee","authority","bank"]),defaults:z.object({account:z.string().optional(),vat:z.string().optional(),currency:z.string().optional(),paymentTermsDays:z.number().int().optional()}).optional(),confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"workspace_party_link_role",({args,actor})=>{const db=openWorkspaceControlDb(workspace());try{return successEnvelope({party:linkPartyRole(db,{partyId:args.partyId,companySlug:args.company,role:args.role,defaults:args.defaults,actor:actor.createdBy})});}finally{db.close();}}));
  server.registerTool("workspace_party_propose_merge",{title:"Propose party merge",description:"Records a reviewable duplicate proposal. It never auto-merges based on name or amount.",inputSchema:{company,fromPartyId:z.string().min(3),intoPartyId:z.string().min(3),reviewAssertion:z.string().min(1),confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"workspace_party_propose_merge",({args,actor})=>{if(!visibleParty(args.fromPartyId,args.company)||!visibleParty(args.intoPartyId,args.company))return errorEnvelope("party not found",{code:"PARTY_NOT_FOUND"});const db=openWorkspaceControlDb(workspace());try{return successEnvelope({proposalHash:proposePartyMerge(db,{...args,actor:actor.createdBy})});}finally{db.close();}}));
  server.registerTool("workspace_party_approve_merge",{title:"Approve party merge",description:"Approves exactly one proposal hash and supersedes the source party append-only.",inputSchema:{company,fromPartyId:z.string().min(3),proposalHash:z.string().regex(/^[a-f0-9]{64}$/),confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"workspace_party_approve_merge",({args,actor})=>{if(!visibleParty(args.fromPartyId,args.company))return errorEnvelope("party not found",{code:"PARTY_NOT_FOUND"});const db=openWorkspaceControlDb(workspace());try{return successEnvelope({party:approvePartyMerge(db,{fromPartyId:args.fromPartyId,proposalHash:args.proposalHash,actor:actor.createdBy})});}finally{db.close();}}));

  server.registerTool("corporate_record_list",{title:"List visible corporate records",description:"Lists only records whose entire declared company scope is authorized, before pagination.",inputSchema:{company,cursor:z.number().int().nonnegative().optional(),limit:z.number().int().min(1).max(100).optional()},outputSchema:envelopeShape,annotations:read},withCompanyDb<any>(server,({args})=>{const db=openWorkspaceControlReadOnlyDb(workspace());try{return successEnvelope(listCorporateRecords(db,{companySlugs:new Set([args.company]),cursor:args.cursor,limit:args.limit}));}finally{db.close();}}));
  server.registerTool("corporate_record_inspect",{title:"Inspect a visible corporate record",description:"Returns metadata, source hash, links and append-only history; original bytes are separate.",inputSchema:{company,recordId:z.string().min(3)},outputSchema:envelopeShape,annotations:read},withCompanyDb<any>(server,({args})=>{const record=visibleRecord(args.recordId,args.company);return record?successEnvelope({record}):errorEnvelope("corporate record not found",{code:"CORPORATE_RECORD_NOT_FOUND"});}));
  server.registerTool("corporate_record_download",{title:"Download verified corporate record bytes",description:"Returns original immutable bytes only after SHA-256 verification and scope authorization.",inputSchema:{company,recordId:z.string().min(3)},outputSchema:envelopeShape,annotations:read},withCompanyDb<any>(server,({args})=>{if(!visibleRecord(args.recordId,args.company))return errorEnvelope("corporate record not found",{code:"CORPORATE_RECORD_NOT_FOUND"});const db=openWorkspaceControlReadOnlyDb(workspace());try{return successEnvelope({bytesBase64:Buffer.from(readCorporateRecordBytes(db,args.recordId)).toString("base64"),sha256:inspectCorporateRecord(db,args.recordId)?.sha256});}finally{db.close();}}));
  server.registerTool("corporate_record_ingest",{title:"Ingest immutable corporate evidence",description:"Stores governance evidence bytes/hash and metadata. It never posts, files or changes group state.",inputSchema:{company,recordId:z.string().optional(),type:z.enum(["incorporation","articles","registration","shareholder_register","shareholder_agreement","board_resolution","general_meeting_minutes","capital_or_dividend_resolution","annual_report","auditor_deliverable","intercompany_agreement","ownership_register","share_transfer","authority_letter","bank_mandate","tax_registration","other"]),bytesBase64:bytes,filename:z.string().min(1),source:z.string().min(1),receivedAt:z.string().min(1),recordDate:z.string().optional(),retentionUntil:z.string().optional(),uploader:z.string().min(1),sensitivity:z.enum(["normal","confidential","restricted"]).optional(),links:z.array(z.object({type:z.enum(["company","party","ownership","disposition","legacy_evidence_ref"]),id:z.string().min(1)})).optional(),confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"corporate_record_ingest",({args,actor})=>{const db=openWorkspaceControlDb(workspace());try{const {bytesBase64,...input}=args;return successEnvelope({record:ingestCorporateRecord(db,{...input,bytes:bytesBase64,actor:actor.createdBy})});}finally{db.close();}}));
  server.registerTool("corporate_record_link",{title:"Link corporate record",description:"Adds an audited typed link without altering original evidence bytes.",inputSchema:{company,recordId:z.string().min(3),type:z.enum(["company","party","ownership","disposition","legacy_evidence_ref"]),id:z.string().min(1),confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"corporate_record_link",({args,actor})=>{if(!visibleRecord(args.recordId,args.company))return errorEnvelope("corporate record not found",{code:"CORPORATE_RECORD_NOT_FOUND"});const db=openWorkspaceControlDb(workspace());try{return successEnvelope({record:linkCorporateRecord(db,{...args,actor:actor.createdBy})});}finally{db.close();}}));
  server.registerTool("corporate_record_enrich",{title:"Enrich corporate record metadata",description:"Appends a source assertion without changing immutable original bytes or source hash.",inputSchema:{company,recordId:z.string().min(3),assertion:z.string().min(1).max(2000),confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"corporate_record_enrich",({args,actor})=>{if(!visibleRecord(args.recordId,args.company))return errorEnvelope("corporate record not found",{code:"CORPORATE_RECORD_NOT_FOUND"});const db=openWorkspaceControlDb(workspace());try{return successEnvelope({payloadHash:enrichCorporateRecord(db,{...args,actor:actor.createdBy})});}finally{db.close();}}));
  server.registerTool("corporate_record_supersede",{title:"Supersede corporate record",description:"Appends a correction chain; it never replaces or deletes original bytes.",inputSchema:{company,recordId:z.string().min(3),replacementRecordId:z.string().min(3),reason:z.string().min(1),confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"corporate_record_supersede",({args,actor})=>{if(!visibleRecord(args.recordId,args.company)||!visibleRecord(args.replacementRecordId,args.company))return errorEnvelope("corporate record not found",{code:"CORPORATE_RECORD_NOT_FOUND"});const db=openWorkspaceControlDb(workspace());try{return successEnvelope({payloadHash:supersedeCorporateRecord(db,{...args,actor:actor.createdBy})});}finally{db.close();}}));
  server.registerTool("company_knowledge_context",{title:"Get source-backed company operating context",description:"Returns a compact as-of assertion context. Conflicting approved singleton facts are marked conflict and never silently selected.",inputSchema:{company,asOf:z.string().min(1).optional(),includeProposed:z.boolean().optional()},outputSchema:envelopeShape,annotations:read},withCompanyDb<any>(server,({args})=>{const db=openWorkspaceControlReadOnlyDb(workspace());try{return successEnvelope({context:queryCompanyKnowledge(db,{companySlug:args.company,asOf:args.asOf??new Date().toISOString(),includeProposed:args.includeProposed}),history:companyKnowledgeHistory(db,args.company)});}finally{db.close();}}));
  server.registerTool("company_knowledge_propose",{title:"Propose dated company operating knowledge",description:"Creates a source-backed assertion only. It cannot change ledger, VAT or legal group state.",inputSchema:{company,predicate:z.enum(COMPANY_KNOWLEDGE_PREDICATES),value:z.unknown(),source:z.object({kind:z.enum(["user","registry","party","corporate_record","external_snapshot","canonical_setting"]),ref:z.string().min(1)}),validFrom:z.string().min(1),validToExclusive:z.string().optional(),certainty:z.enum(["confirmed","probable","uncertain"]).optional(),assertionId:z.string().optional(),confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"company_knowledge_propose",({args,actor})=>{const db=openWorkspaceControlDb(workspace());try{return successEnvelope({assertion:proposeCompanyKnowledge(db,{...args,companySlug:args.company,actor:actor.createdBy,principal:knowledgePrincipal()})});}finally{db.close();}}));
  server.registerTool("company_knowledge_review",{title:"Review company knowledge assertion",description:"Approves or rejects exactly one proposed assertion; history remains append-only.",inputSchema:{company,assertionId:z.string().min(3),decision:z.enum(["approved","rejected"]),reason:z.string().max(1000).optional(),confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"company_knowledge_review",({args,actor})=>{const db=openWorkspaceControlDb(workspace());try{if(inspectCompanyKnowledgeAssertion(db,args.assertionId)?.companySlug!==args.company)return errorEnvelope("company knowledge assertion not found",{code:"COMPANY_KNOWLEDGE_NOT_FOUND"});return successEnvelope({assertion:reviewCompanyKnowledge(db,{...args,actor:actor.createdBy,principal:knowledgePrincipal()})});}finally{db.close();}}));
  server.registerTool("company_knowledge_supersede",{title:"Supersede approved company knowledge",description:"Creates a new proposed assertion and append-only supersession link; it never edits history.",inputSchema:{company,assertionId:z.string().min(3),replacement:z.object({predicate:z.enum(COMPANY_KNOWLEDGE_PREDICATES),value:z.unknown(),source:z.object({kind:z.enum(["user","registry","party","corporate_record","external_snapshot","canonical_setting"]),ref:z.string().min(1)}),validFrom:z.string().min(1),validToExclusive:z.string().optional(),certainty:z.enum(["confirmed","probable","uncertain"]).optional(),assertionId:z.string().optional()}),confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"company_knowledge_supersede",({args,actor})=>{const db=openWorkspaceControlDb(workspace());try{if(inspectCompanyKnowledgeAssertion(db,args.assertionId)?.companySlug!==args.company)return errorEnvelope("company knowledge assertion not found",{code:"COMPANY_KNOWLEDGE_NOT_FOUND"});return successEnvelope(supersedeCompanyKnowledge(db,{assertionId:args.assertionId,replacement:args.replacement as any,actor:actor.createdBy,principal:knowledgePrincipal()}));}finally{db.close();}}));

  server.registerTool("ownership_graph_query",{title:"Query approved ownership and control facts",description:"Reads an as-of, party-aware legal ownership graph. Hidden company endpoints are removed before counts and aggregation; it never represents a consolidation.",inputSchema:{company,asOf:z.string().min(10)},outputSchema:envelopeShape,annotations:read},withCompanyDb<any>(server,({args})=>{const db=openWorkspaceControlReadOnlyDb(workspace());try{return successEnvelope(queryOwnershipGraph(db,{asOf:args.asOf,visibleCompanySlugs:new Set([args.company])}));}finally{db.close();}}));
  server.registerTool("ownership_snapshot_history",{title:"Read redacted ownership snapshot history",description:"Returns immutable ownership snapshot history only when every legal-company endpoint remains authorized. Inaccessible snapshots are omitted, never counted or described.",inputSchema:{company,snapshotId:z.string().min(3).optional()},outputSchema:envelopeShape,annotations:read},withCompanyDb<any>(server,({args})=>{const db=openWorkspaceControlReadOnlyDb(workspace());try{const history=ownershipHistory(db,args.snapshotId).filter(Boolean).filter(visibleOwnershipSnapshot);return successEnvelope({history});}finally{db.close();}}));
  server.registerTool("ownership_snapshot_propose",{title:"Propose source-backed ownership snapshot",description:"Stores a source-hashed registry observation and deterministic diff only. It cannot overwrite approved facts or update the v1 group manifest. The authenticated principal needs ownership permission for every company endpoint.",inputSchema:{company,snapshotId:z.string().min(3).optional(),source:z.string().min(1),observedAt:z.string().min(10),facts:z.array(ownershipFact).min(1).max(2048),confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"ownership_snapshot_propose",({args,actor})=>{const db=openWorkspaceControlDb(workspace());try{return successEnvelope({snapshot:proposeOwnershipSnapshot(db,{...args,actor:actor.createdBy,principal:knowledgePrincipal()})});}finally{db.close();}}));
  server.registerTool("ownership_snapshot_review",{title:"Review ownership snapshot",description:"Approves or rejects exactly one immutable registry snapshot. Approval alone does not apply ownership facts.",inputSchema:{company,snapshotId:z.string().min(3),decision:z.enum(["approved","rejected"]),confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"ownership_snapshot_review",({args,actor})=>{const db=openWorkspaceControlDb(workspace());try{return successEnvelope({snapshot:reviewOwnershipSnapshot(db,{...args,actor:actor.createdBy,principal:knowledgePrincipal()})});}finally{db.close();}}));
  server.registerTool("ownership_snapshot_apply",{title:"Apply exact approved ownership diff",description:"Applies only the reviewed snapshot/diff hashes with an authenticated principal and confirmation. It never overwrites history or mutates a company ledger.",inputSchema:{company,snapshotId:z.string().min(3),snapshotHash:z.string().regex(/^[a-f0-9]{64}$/),diffHash:z.string().regex(/^[a-f0-9]{64}$/),confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"ownership_snapshot_apply",({args,actor})=>{const db=openWorkspaceControlDb(workspace());try{return successEnvelope(applyOwnershipSnapshot(db,{...args,actor:actor.createdBy,principal:knowledgePrincipal(),authorized:true}));}finally{db.close();}}));
}
