import type { ServerConfig } from "../config";
import { ApiError } from "../errors";
import { withCompanyMutation } from "../mutations";
import { okResponse } from "./_shared";
import { companyRootForSlug } from "../../core/workspace";
import { companyPaths } from "../../core/paths";
import { migrate, openDb } from "../../core/db";
import { openWorkspaceControlDb } from "../../core/workspace-control";
import { applyBookkeepingBatch, approveBookkeepingBatchPlan, createBookkeepingBatchRun, getBookkeepingBatchState, planBookkeepingBatch } from "../../core/bookkeeping-batch";
function scope(body: Record<string, unknown>) { const get=(k:string)=>body[k]; if (!Number.isInteger(get("companyId")) || !["accountingFrom","accountingTo","bankFrom","bankTo"].every(k=>typeof get(k)==="string")) throw ApiError.badRequest("companyId and four ISO date bounds are required"); return { companyId:get("companyId") as number, accountingFrom:get("accountingFrom") as string, accountingTo:get("accountingTo") as string, bankFrom:get("bankFrom") as string, bankTo:get("bankTo") as string }; }
export function handleBookkeepingBatchDryRun(config:ServerConfig, slug:string, url:URL):Response { const s=scope({companyId:Number(url.searchParams.get("companyId")),accountingFrom:url.searchParams.get("accountingFrom"),accountingTo:url.searchParams.get("accountingTo"),bankFrom:url.searchParams.get("bankFrom"),bankTo:url.searchParams.get("bankTo")}); const db=openDb(companyPaths(companyRootForSlug(config.workspaceRoot,slug)).db); try { migrate(db); return okResponse({dryRun:true,plan:planBookkeepingBatch(db,s)}); } finally { db.close(); } }
const state=getBookkeepingBatchState;
function runId(body:Record<string,unknown>){if(!Number.isInteger(body.runId)||Number(body.runId)<=0)throw ApiError.badRequest("runId is required");return Number(body.runId)}
function planHash(body:Record<string,unknown>){if(typeof body.planHash!=="string"||!/^[a-f0-9]{64}$/.test(body.planHash))throw ApiError.badRequest("planHash is required");return body.planHash}
function principal(ctx:{principal:{via:string;userId?:string;serviceAccountId?:string}}){const p=ctx.principal;if(p.via==="service-principal"&&p.serviceAccountId)return {kind:"service-account" as const,subjectId:p.serviceAccountId};if(p.userId)return {kind:"user" as const,subjectId:p.userId};return {kind:"local-trusted" as const,subjectId:"server-local"};}
export async function handleBookkeepingBatchPersistDryRun(config:ServerConfig,request:Request,slug:string):Promise<Response>{const result=await withCompanyMutation(request,config,slug,({db,actor,principal:requestPrincipal},body)=>{if(typeof body.runKey!=="string"||!body.runKey)throw ApiError.badRequest("runKey is required");const plan=planBookkeepingBatch(db,scope(body));const run=createBookkeepingBatchRun(db,{...plan,runKey:body.runKey,actor:actor.createdBy,principal:principal({principal:requestPrincipal})});return {ok:true,dryRun:true,runId:run.runId,duplicate:run.duplicate,plan:run.plan,state:state(db,run.runId)}},{requireConfirm:true});return okResponse(result)}
export async function handleBookkeepingBatchApprove(config:ServerConfig,request:Request,slug:string):Promise<Response>{return okResponse(await withCompanyMutation(request,config,slug,({db,actor,principal:requestPrincipal},body)=>{const control=openWorkspaceControlDb(config.workspaceRoot);try{return {...approveBookkeepingBatchPlan(db,{runId:runId(body),planHash:planHash(body),actor:actor.createdBy,principal:principal({principal:requestPrincipal}),approval:{controlDb:control,workspaceRoot:config.workspaceRoot,companySlug:slug,expectedPolicyEventHash:typeof body.expectedPolicyEventHash==="string"?body.expectedPolicyEventHash:null}}),state:state(db,runId(body))};}finally{control.close();}},{requireConfirm:true}))}
export async function handleBookkeepingBatchApply(config:ServerConfig, request:Request, slug:string):Promise<Response> { return okResponse(await withCompanyMutation(request,config,slug,({db,actor,principal:requestPrincipal},body)=>({...applyBookkeepingBatch(db,{runId:runId(body),planHash:planHash(body),actor:actor.createdBy,principal:principal({principal:requestPrincipal})}),runId:runId(body),planHash:planHash(body),state:state(db,runId(body))}),{requireConfirm:true})); }
export function handleBookkeepingBatchStatus(config:ServerConfig,slug:string,run:number):Response{const db=openDb(companyPaths(companyRootForSlug(config.workspaceRoot,slug)).db);try{migrate(db);return okResponse({state:state(db,run)})}finally{db.close()}}
