import type { ServerConfig } from "../config";
import { ApiError } from "../errors";
import { withCompanyMutation } from "../mutations";
import { companyRootForSlug } from "../../core/workspace";
import { companyPaths } from "../../core/paths";
import { openLedgerReadOnly } from "../../core/ledger-inspection";
import { createPurchaseCase, getPurchaseCase, listPurchaseCases, reassessPurchaseCase, reviewPurchaseCase, reviewPurchaseCaseGroup, type DocumentationOutcome, type PurchaseCaseGroupMember, type PurchaseCaseSource } from "../../core/purchase-cases";
import { buildPurchaseOverview, purchaseCaseSourceFact } from "../../core/purchase-overview";
import { okResponse } from "./_shared";
import { openWorkspaceControlDb } from "../../core/workspace-control";

const outcomes=new Set<DocumentationOutcome>(["unresolved","ordinary_evidence_sufficient","alternative_evidence_assessed"]);
function source(body:Record<string,unknown>):PurchaseCaseSource { const raw=body.source; if(!raw||typeof raw!=="object"||Array.isArray(raw))throw ApiError.badRequest("source is required"); const value=raw as Record<string,unknown>; if((value.kind!=="document"&&value.kind!=="bank_transaction"&&value.kind!=="payable")||!Number.isInteger(value.id)||Number(value.id)<=0)throw ApiError.badRequest("source must be a typed positive document, bank_transaction, or payable reference"); return {kind:value.kind,id:Number(value.id)} as PurchaseCaseSource; }
function outcome(value:unknown):DocumentationOutcome { if(!outcomes.has(value as DocumentationOutcome))throw ApiError.badRequest("documentationOutcome is required"); return value as DocumentationOutcome; }
function optionalNote(value:unknown){if(value===undefined)return undefined;if(typeof value!=="string"||value.length>2000)throw ApiError.badRequest("note must be at most 2000 characters");return value;}
function members(value:unknown):PurchaseCaseGroupMember[]{if(!Array.isArray(value)||value.length<1||value.length>100)throw ApiError.badRequest("members must contain 1 to 100 exact cases");const ids=new Set<string>();return value.map(item=>{if(!item||typeof item!=="object"||Array.isArray(item))throw ApiError.badRequest("each member must be an object");const member=item as Record<string,unknown>;if(typeof member.caseId!=="string"||!Number.isInteger(member.expectedVersion)||Number(member.expectedVersion)<1||typeof member.expectedSourceFingerprint!=="string"||!/^[a-f0-9]{64}$/.test(member.expectedSourceFingerprint)||ids.has(member.caseId))throw ApiError.badRequest("each member requires a unique caseId, expectedVersion and expectedSourceFingerprint");ids.add(member.caseId);return {caseId:member.caseId,expectedVersion:Number(member.expectedVersion),expectedSourceFingerprint:member.expectedSourceFingerprint};});}
function principalId(principal:any):string { const id=principal?.serviceAccountId??principal?.userId; if(typeof id!=="string"||!id.trim())throw ApiError.unauthorized("missing or invalid credentials"); return id; }
export async function handlePurchaseCaseCreate(config:ServerConfig,request:Request,slug:string){return okResponse(await withCompanyMutation(request,config,slug,({db,actor,principal},body)=>createPurchaseCase(db,{caseId:typeof body.caseId==="string"?body.caseId:undefined,source:source(body),documentationOutcome:body.documentationOutcome===undefined?undefined:outcome(body.documentationOutcome),note:optionalNote(body.note),actor,principalId:principalId(principal)}),{requireConfirm:true,keyIdempotent:"purchase_case_create",requireIdempotencyKey:true}));}
export async function handlePurchaseCaseReview(config:ServerConfig,request:Request,slug:string,id:string){return okResponse(await withCompanyMutation(request,config,slug,({db,actor,principal},body)=>{if(!Number.isInteger(body.expectedVersion)||typeof body.expectedSourceFingerprint!=="string"||!/^[a-f0-9]{64}$/.test(body.expectedSourceFingerprint))throw ApiError.badRequest("expectedVersion and expectedSourceFingerprint are required");const control=openWorkspaceControlDb(config.workspaceRoot);try{return reviewPurchaseCase(db,{caseId:id,expectedVersion:Number(body.expectedVersion),expectedSourceFingerprint:body.expectedSourceFingerprint,documentationOutcome:outcome(body.documentationOutcome),note:optionalNote(body.note),actor,approval:{controlDb:control,workspaceRoot:config.workspaceRoot,companySlug:slug,principalId:principalId(principal),expectedPolicyEventHash:typeof body.expectedPolicyEventHash==="string"?body.expectedPolicyEventHash:null}});}finally{control.close();}},{requireConfirm:true,keyIdempotent:"purchase_case_review",requireIdempotencyKey:true}));}
export async function handlePurchaseCaseReassess(config:ServerConfig,request:Request,slug:string,id:string){return okResponse(await withCompanyMutation(request,config,slug,({db,actor,principal},body)=>{if(!Number.isInteger(body.expectedVersion)||typeof body.expectedSourceFingerprint!=="string"||typeof body.currentSourceFingerprint!=="string"||!/^[a-f0-9]{64}$/.test(body.expectedSourceFingerprint)||!/^[a-f0-9]{64}$/.test(body.currentSourceFingerprint)||typeof body.reason!=="string"||!body.reason.trim())throw ApiError.badRequest("expectedVersion, both source fingerprints and reason are required");const control=openWorkspaceControlDb(config.workspaceRoot);try{return reassessPurchaseCase(db,{caseId:id,expectedVersion:Number(body.expectedVersion),expectedSourceFingerprint:body.expectedSourceFingerprint,currentSourceFingerprint:body.currentSourceFingerprint,documentationOutcome:outcome(body.documentationOutcome),reason:body.reason,actor,approval:{controlDb:control,workspaceRoot:config.workspaceRoot,companySlug:slug,principalId:principalId(principal),expectedPolicyEventHash:typeof body.expectedPolicyEventHash==="string"?body.expectedPolicyEventHash:null}});}finally{control.close();}},{requireConfirm:true,keyIdempotent:"purchase_case_reassess",requireIdempotencyKey:true}));}
export async function handlePurchaseCaseGroupReview(config:ServerConfig,request:Request,slug:string){return okResponse(await withCompanyMutation(request,config,slug,({db,actor,principal},body)=>{const control=openWorkspaceControlDb(config.workspaceRoot);try{return reviewPurchaseCaseGroup(db,{groupId:typeof body.groupId==="string"?body.groupId:undefined,members:members(body.members),documentationOutcome:outcome(body.documentationOutcome),note:optionalNote(body.note),actor,approval:{controlDb:control,workspaceRoot:config.workspaceRoot,companySlug:slug,principalId:principalId(principal),expectedPolicyEventHash:typeof body.expectedPolicyEventHash==="string"?body.expectedPolicyEventHash:null}});}finally{control.close();}},{requireConfirm:true,keyIdempotent:"purchase_case_group_review",requireIdempotencyKey:true}));}
export function handlePurchaseCaseList(config:ServerConfig,slug:string){const db=openLedgerReadOnly(companyPaths(companyRootForSlug(config.workspaceRoot,slug)).db);try{return okResponse({purchaseCases:listPurchaseCases(db).map(purchaseCase=>({...purchaseCase,sourceFact:purchaseCaseSourceFact(db,purchaseCase)}))});}finally{db.close();}}
export function handlePurchaseCaseGet(config:ServerConfig,slug:string,id:string){const db=openLedgerReadOnly(companyPaths(companyRootForSlug(config.workspaceRoot,slug)).db);try{const purchaseCase=getPurchaseCase(db,id);return okResponse({purchaseCase:purchaseCase?{...purchaseCase,sourceFact:purchaseCaseSourceFact(db,purchaseCase)}:null});}finally{db.close();}}
export function handlePurchaseOverview(config:ServerConfig,slug:string,url:URL){const from=url.searchParams.get("from"),to=url.searchParams.get("to");if(!from||!to)throw ApiError.badRequest("from and to are required ISO dates");const raw=url.searchParams.get("includeProvisional");if(raw!==null&&raw!=="true"&&raw!=="false")throw ApiError.badRequest("includeProvisional must be true or false");const db=openLedgerReadOnly(companyPaths(companyRootForSlug(config.workspaceRoot,slug)).db);try{return okResponse({overview:buildPurchaseOverview(db,{from,to,includeProvisional:raw===null?undefined:raw==="true"})});}finally{db.close();}}
