/** Compact Cockpit HTTP adapter for #573/#575.  Company slug is the access
 * anchor; workspace records stay shared but are projected through the caller's
 * full live company membership set before pagination or inspection. */
import type { ServerConfig } from "../config";
import { ApiError } from "../errors";
import { withCompanyMutation } from "../mutations";
import { okResponse, readJsonBody, requireString } from "./_shared";
import { listWorkspaceCompanies, resolveWorkspaceSlug } from "../../core/workspace";
import { authorizeWorkspaceRoute } from "../../core/workspace-access";
import { openWorkspaceControlDb, openWorkspaceControlReadOnlyDb } from "../../core/workspace-control";
import { approvePartyMerge, createParty, inspectVisibleParty, linkPartyRole, proposePartyMerge, searchParties } from "../../core/party-registry";
import { enrichCorporateRecord, ingestCorporateRecord, inspectCorporateRecord, inspectVisibleCorporateRecord, linkCorporateRecord, listCorporateRecords, readCorporateRecordBytes, supersedeCorporateRecord } from "../../core/corporate-records";
import { companyKnowledgeHistory, inspectCompanyKnowledgeAssertion, proposeCompanyKnowledge, queryCompanyKnowledge, reviewCompanyKnowledge, supersedeCompanyKnowledge } from "../../core/company-knowledge";
import { applyOwnershipSnapshot, ownershipHistory, projectExactCompanyOwnership, proposeOwnershipSnapshot, queryOwnershipGraph, reviewOwnershipSnapshot } from "../../core/ownership-graph";
import { applyLegacyPartyMapping, inspectLegacyPartyMappings, planLegacyPartyMapping, supersedeLegacyPartyMapping } from "../../core/legacy-party-mapping";
import { applyVendorIdentityEnrichment, listVendorIdentityEnrichments, planVendorIdentityEnrichment } from "../../core/vendor-identity-enrichment";
import { openLedgerReadOnly } from "../../core/ledger-inspection";
import { companyPaths } from "../../core/paths";

function visibleCompanies(config:ServerConfig, permission:"company.read"|"company.master-data"|"company.review"|"company.ownership.read", anchor:string):Set<string> {
  const principal=config.requestPrincipal;
  if (!config.betterAuthProvider || !principal?.userId) return new Set([anchor]);
  const db=openWorkspaceControlReadOnlyDb(config.workspaceRoot); try { return new Set(listWorkspaceCompanies(config.workspaceRoot).filter(c=>authorizeWorkspaceRoute(db,config.workspaceRoot,{userId:principal.userId!,companySlug:c.slug,permission}).allowed).map(c=>c.slug)); } finally {db.close();}
}
function partyVisible(config:ServerConfig,slug:string,id:string){const db=openWorkspaceControlReadOnlyDb(config.workspaceRoot);try{return inspectVisibleParty(db,id,visibleCompanies(config,"company.read",slug));}finally{db.close();}}
function recordVisible(config:ServerConfig,slug:string,id:string){const db=openWorkspaceControlReadOnlyDb(config.workspaceRoot);try{const record=inspectVisibleCorporateRecord(db,id,visibleCompanies(config,"company.read",slug));if(!record)return null;if(record.sensitivity!=="normal"){const principal=config.requestPrincipal;const admin=principal?.userId?visibleCompanies(config,"company.master-data",slug):new Set<string>();const companyScopes=record.links.filter((link:any)=>link.type==="company").map((link:any)=>link.id);if(!companyScopes.every((company:string)=>admin.has(company)))return null;}return record;}finally{db.close();}}
function assertRecordWriteScopes(config:ServerConfig,principal:any,db:ReturnType<typeof openWorkspaceControlReadOnlyDb>,record:any){const userId=principal?.userId;if(!userId)throw ApiError.unauthorized("missing or invalid credentials");for(const companySlug of record.links.filter((link:any)=>link.type==="company").map((link:any)=>link.id))if(!authorizeWorkspaceRoute(db,config.workspaceRoot,{userId,companySlug,permission:"company.master-data"}).allowed)throw ApiError.unauthorized("missing or invalid credentials");}
function assertCompanyWriteScopes(config:ServerConfig,principal:any,db:ReturnType<typeof openWorkspaceControlReadOnlyDb>,companySlugs:Iterable<string>){const userId=principal?.userId;if(!userId)throw ApiError.unauthorized("missing or invalid credentials");for(const companySlug of companySlugs)if(!authorizeWorkspaceRoute(db,config.workspaceRoot,{userId,companySlug,permission:"company.master-data"}).allowed)throw ApiError.unauthorized("missing or invalid credentials");}
const positive=(raw:string|null, fallback:number)=>{const n=Number(raw??fallback);return Number.isSafeInteger(n)&&n>=0?n:fallback;};
const legacyInput=(slug:string,body:Record<string,unknown>)=>({companySlug:slug,legacyKind:body.legacyKind as any,legacyId:requireString(body,"legacyId"),partyId:requireString(body,"partyId"),role:body.role as any,documentId:Number(body.documentId),reviewedLegacyReference:requireString(body,"reviewedLegacyReference")});
const vendorIdentityInput=(slug:string,body:Record<string,unknown>)=>({companySlug:slug,vendorId:Number(body.vendorId),documentId:Number(body.documentId),countryCode:requireString(body,"countryCode"),identifierKind:requireString(body,"identifierKind") as any,identifier:typeof body.identifier==="string"?body.identifier:undefined,reviewedReference:requireString(body,"reviewedReference")});
export async function handleVendorIdentityEnrichmentPlan(config:ServerConfig,slug:string,request:Request):Promise<Response>{const body=await readJsonBody(request),root=resolveWorkspaceSlug(config.workspaceRoot,slug);if(!root)throw ApiError.notFound("company not found");const db=openLedgerReadOnly(companyPaths(root).db);try{return okResponse(planVendorIdentityEnrichment(db,root,vendorIdentityInput(slug,body)));}finally{db.close();}}
export function handleVendorIdentityEnrichments(config:ServerConfig,slug:string,request:Request):Response{const root=resolveWorkspaceSlug(config.workspaceRoot,slug);if(!root)throw ApiError.notFound("company not found");const db=openLedgerReadOnly(companyPaths(root).db);try{return okResponse({rows:listVendorIdentityEnrichments(db,{vendorId:new URL(request.url).searchParams.get("vendorId")?Number(new URL(request.url).searchParams.get("vendorId")):undefined})});}finally{db.close();}}
export async function handleVendorIdentityEnrichmentApply(config:ServerConfig,slug:string,request:Request):Promise<Response>{const root=resolveWorkspaceSlug(config.workspaceRoot,slug);if(!root)throw ApiError.notFound("company not found");const result=await withCompanyMutation(request,config,slug,(ctx,body)=>{if(!ctx.principal?.userId&&!ctx.principal?.serviceAccountId)throw ApiError.unauthorized("missing or invalid credentials");return applyVendorIdentityEnrichment(ctx.db,root,{...vendorIdentityInput(slug,body),planHash:requireString(body,"planHash"),idempotencyKey:requireString(body,"idempotencyKey"),confirm:true,actor:ctx.actor.createdBy,principal:ctx.principal.serviceAccountId??ctx.principal.userId});},{requireConfirm:true});return okResponse(result);}

export async function handleLegacyPartyMappingPlan(config:ServerConfig,slug:string,request:Request):Promise<Response>{const body=await readJsonBody(request),root=resolveWorkspaceSlug(config.workspaceRoot,slug);if(!root)throw ApiError.notFound("company not found");const ledger=openLedgerReadOnly(companyPaths(root).db),control=openWorkspaceControlReadOnlyDb(config.workspaceRoot);try{return okResponse(planLegacyPartyMapping(ledger,control,legacyInput(slug,body)));}finally{control.close();ledger.close();}}
export function handleLegacyPartyMappings(config:ServerConfig,slug:string,request:Request):Response{const url=new URL(request.url),control=openWorkspaceControlReadOnlyDb(config.workspaceRoot);try{return okResponse({rows:inspectLegacyPartyMappings(control,{companySlug:slug,legacyKind:(url.searchParams.get("legacyKind")??undefined) as any,legacyId:url.searchParams.get("legacyId")??undefined})});}finally{control.close();}}
export async function handleLegacyPartyMappingApply(config:ServerConfig,slug:string,request:Request):Promise<Response>{const result=await withCompanyMutation(request,config,slug,(ctx,body)=>{const principal=knowledgePrincipal(ctx.principal),control=openWorkspaceControlDb(config.workspaceRoot);try{return applyLegacyPartyMapping(ctx.db,control,{...legacyInput(slug,body),planHash:requireString(body,"planHash"),idempotencyKey:requireString(body,"idempotencyKey"),confirm:true,actor:ctx.actor.createdBy,principal:principal.id});}finally{control.close();}},{requireConfirm:true});return okResponse(result);}
export async function handleLegacyPartyMappingSupersede(config:ServerConfig,slug:string,request:Request):Promise<Response>{const result=await withCompanyMutation(request,config,slug,(ctx,body)=>{const principal=knowledgePrincipal(ctx.principal),control=openWorkspaceControlDb(config.workspaceRoot);try{return supersedeLegacyPartyMapping(control,{companySlug:slug,legacyKind:body.legacyKind as any,legacyId:requireString(body,"legacyId"),planHash:requireString(body,"planHash"),reason:requireString(body,"reason"),idempotencyKey:requireString(body,"idempotencyKey"),confirm:true,actor:ctx.actor.createdBy,principal:principal.id});}finally{control.close();}},{requireConfirm:true});return okResponse(result);}

export function handleRegistryParties(config:ServerConfig,slug:string,request:Request):Response {const u=new URL(request.url),db=openWorkspaceControlReadOnlyDb(config.workspaceRoot);try{return okResponse(searchParties(db,{query:u.searchParams.get("query")??undefined,companySlugs:visibleCompanies(config,"company.read",slug),cursor:positive(u.searchParams.get("cursor"),0),limit:Math.min(100,Math.max(1,positive(u.searchParams.get("limit"),25)))}));}finally{db.close();}}
export function handleRegistryParty(config:ServerConfig,slug:string,id:string):Response {const party=partyVisible(config,slug,id);if(!party)throw ApiError.notFound("party not found");return okResponse({party});}
export async function handleRegistryPartyCreate(config:ServerConfig,slug:string,request:Request):Promise<Response>{const result=await withCompanyMutation(request,config,slug,(ctx,body)=>{const db=openWorkspaceControlDb(config.workspaceRoot);try{const role=requireString(body,"role");const party=createParty(db,{...body,actor:ctx.actor.createdBy}as any);return {ok:true,party:linkPartyRole(db,{partyId:(party as any).partyId,companySlug:slug,role:role as any,defaults:body.defaults as any,actor:ctx.actor.createdBy})};}finally{db.close();}},{requireConfirm:true});return okResponse(result);}
export async function handleRegistryPartyRole(config:ServerConfig,slug:string,id:string,request:Request):Promise<Response>{const result=await withCompanyMutation(request,config,slug,(ctx,body)=>{if(!partyVisible(config,slug,id))throw ApiError.notFound("party not found");const db=openWorkspaceControlDb(config.workspaceRoot);try{return {ok:true,party:linkPartyRole(db,{partyId:id,companySlug:slug,role:requireString(body,"role") as any,defaults:body.defaults as any,actor:ctx.actor.createdBy})};}finally{db.close();}},{requireConfirm:true});return okResponse(result);}
export async function handleRegistryPartyMerge(config:ServerConfig,slug:string,request:Request,approve:boolean):Promise<Response>{const result=await withCompanyMutation(request,config,slug,(ctx,body)=>{const from= requireString(body,"fromPartyId");if(!partyVisible(config,slug,from))throw ApiError.notFound("party not found");const db=openWorkspaceControlDb(config.workspaceRoot);try{if(approve)return {ok:true,party:approvePartyMerge(db,{fromPartyId:from,proposalHash:requireString(body,"proposalHash"),actor:ctx.actor.createdBy})};const into=requireString(body,"intoPartyId");if(!partyVisible(config,slug,into))throw ApiError.notFound("party not found");return {ok:true,proposalHash:proposePartyMerge(db,{fromPartyId:from,intoPartyId:into,reviewAssertion:requireString(body,"reviewAssertion"),actor:ctx.actor.createdBy})};}finally{db.close();}},{requireConfirm:true});return okResponse(result);}

export function handleRegistryRecords(config:ServerConfig,slug:string,request:Request):Response {const u=new URL(request.url),db=openWorkspaceControlReadOnlyDb(config.workspaceRoot);try{return okResponse(listCorporateRecords(db,{companySlugs:visibleCompanies(config,"company.read",slug),cursor:positive(u.searchParams.get("cursor"),0),limit:Math.min(100,Math.max(1,positive(u.searchParams.get("limit"),25)))}));}finally{db.close();}}
export function handleRegistryRecord(config:ServerConfig,slug:string,id:string):Response {const record=recordVisible(config,slug,id);if(!record)throw ApiError.notFound("corporate record not found");return okResponse({record});}
export function handleRegistryRecordDownload(config:ServerConfig,slug:string,id:string):Response {if(!recordVisible(config,slug,id))throw ApiError.notFound("corporate record not found");const db=openWorkspaceControlReadOnlyDb(config.workspaceRoot);try{return okResponse({bytesBase64:Buffer.from(readCorporateRecordBytes(db,id)).toString("base64"),sha256:inspectCorporateRecord(db,id)?.sha256});}finally{db.close();}}
export async function handleRegistryRecordIngest(config:ServerConfig,slug:string,request:Request):Promise<Response>{const result=await withCompanyMutation(request,config,slug,(ctx,body)=>{if(typeof body.bytesBase64!=="string")throw ApiError.badRequest("bytesBase64 is required");const db=openWorkspaceControlDb(config.workspaceRoot);try{const links=Array.isArray(body.links)?body.links:[];if(links.some((l:any)=>!l||typeof l!=="object"))throw ApiError.badRequest("initial links are invalid");assertCompanyWriteScopes(config,ctx.principal,db,[slug,...links.filter((l:any)=>l.type==="company").map((l:any)=>l.id)]);return {ok:true,record:ingestCorporateRecord(db,{...body,bytes:new Uint8Array(Buffer.from(body.bytesBase64,"base64")),links:[...links,{type:"company",id:slug}],actor:ctx.actor.createdBy}as any)};}finally{db.close();}},{requireConfirm:true});return okResponse(result);}
export async function handleRegistryRecordAction(config:ServerConfig,slug:string,id:string,request:Request,action:"link"|"enrich"|"supersede"):Promise<Response>{const result=await withCompanyMutation(request,config,slug,(ctx,body)=>{if(!recordVisible(config,slug,id))throw ApiError.notFound("corporate record not found");const db=openWorkspaceControlDb(config.workspaceRoot);try{const record=inspectCorporateRecord(db,id)!;assertRecordWriteScopes(config,ctx.principal,db,record);if(action==="enrich")return {ok:true,payloadHash:enrichCorporateRecord(db,{recordId:id,assertion:requireString(body,"assertion"),actor:ctx.actor.createdBy})};if(action==="supersede"){const replacement=inspectCorporateRecord(db,requireString(body,"replacementRecordId"));if(!replacement)throw ApiError.notFound("corporate record not found");assertRecordWriteScopes(config,ctx.principal,db,replacement);return {ok:true,payloadHash:supersedeCorporateRecord(db,{recordId:id,replacementRecordId:replacement.recordId,reason:requireString(body,"reason"),actor:ctx.actor.createdBy})};}const type=requireString(body,"type");if(type==="company")assertCompanyWriteScopes(config,ctx.principal,db,[requireString(body,"id")]);return {ok:true,record:linkCorporateRecord(db,{recordId:id,type:type as any,id:requireString(body,"id"),actor:ctx.actor.createdBy})};}finally{db.close();}},{requireConfirm:true});return okResponse(result);}

const knowledgePrincipal=(principal:any)=>principal?.serviceAccountId?{kind:"service_account" as const,id:principal.serviceAccountId}:principal?.userId?{kind:"user" as const,id:principal.userId}:{kind:"local_operator" as const,id:"localhost"};
export function handleCompanyKnowledge(config:ServerConfig,slug:string,request:Request):Response {const u=new URL(request.url),db=openWorkspaceControlReadOnlyDb(config.workspaceRoot);try{return okResponse({context:queryCompanyKnowledge(db,{companySlug:slug,asOf:u.searchParams.get("asOf")??new Date().toISOString(),includeProposed:u.searchParams.get("includeProposed")==="true"}),history:companyKnowledgeHistory(db,slug)});}finally{db.close();}}
export async function handleCompanyKnowledgeAction(config:ServerConfig,slug:string,request:Request,action:"propose"|"review"|"supersede"):Promise<Response>{const result=await withCompanyMutation(request,config,slug,(ctx,body)=>{const db=openWorkspaceControlDb(config.workspaceRoot);try{const principal=knowledgePrincipal(ctx.principal);if(action==="propose")return {ok:true,assertion:proposeCompanyKnowledge(db,{...body,companySlug:slug,actor:ctx.actor.createdBy,principal}as any)};const assertionId=requireString(body,"assertionId");if(inspectCompanyKnowledgeAssertion(db,assertionId)?.companySlug!==slug)throw ApiError.notFound("company knowledge assertion not found");if(action==="review")return {ok:true,assertion:reviewCompanyKnowledge(db,{assertionId,decision:requireString(body,"decision") as any,reason:typeof body.reason==="string"?body.reason:undefined,actor:ctx.actor.createdBy,principal})};return {ok:true,...supersedeCompanyKnowledge(db,{assertionId,replacement:body.replacement as any,actor:ctx.actor.createdBy,principal})};}finally{db.close();}},{requireConfirm:true});return okResponse(result);}

function ownershipEndpointSlugs(db:ReturnType<typeof openWorkspaceControlReadOnlyDb>, body:Record<string,unknown>):Set<string>{let facts:any[];if(Array.isArray(body.facts))facts=body.facts;else {const id=typeof body.snapshotId==="string"?body.snapshotId:"";const row=db.query("SELECT canonical_facts FROM rm_ownership_source_snapshots WHERE snapshot_id=?").get(id)as any;if(!row)throw ApiError.notFound("ownership snapshot not found");try{facts=JSON.parse(row.canonical_facts);}catch{throw ApiError.badRequest("ownership snapshot is invalid");}}const slugs=new Set<string>();for(const fact of facts){if(!fact||typeof fact.ownedCompanySlug!=="string")throw ApiError.badRequest("ownership fact requires ownedCompanySlug");slugs.add(fact.ownedCompanySlug);if(fact.owner?.kind==="company"){if(typeof fact.owner.companySlug!=="string")throw ApiError.badRequest("company owner requires companySlug");slugs.add(fact.owner.companySlug);}}return slugs;}
function assertOwnershipEndpoints(config:ServerConfig,principal:any,db:ReturnType<typeof openWorkspaceControlReadOnlyDb>,body:Record<string,unknown>,permission:"company.ownership.read"|"company.ownership.manage"|"company.admin"){const userId=principal?.userId;if(!userId)throw ApiError.unauthorized("missing or invalid credentials");for(const companySlug of ownershipEndpointSlugs(db,body))if(!authorizeWorkspaceRoute(db,config.workspaceRoot,{userId,companySlug,permission}).allowed)throw ApiError.unauthorized("missing or invalid credentials");}
export function handleOwnershipQuery(config:ServerConfig,slug:string,request:Request):Response{const u=new URL(request.url),db=openWorkspaceControlReadOnlyDb(config.workspaceRoot);try{return okResponse(queryOwnershipGraph(db,{asOf:requireString(Object.fromEntries(u.searchParams),"asOf"),visibleCompanySlugs:visibleCompanies(config,"company.ownership.read",slug)}));}finally{db.close();}}
export function handleOwnershipHistory(config:ServerConfig,slug:string,request:Request):Response{const u=new URL(request.url),db=openWorkspaceControlReadOnlyDb(config.workspaceRoot);try{const visible=visibleCompanies(config,"company.ownership.read",slug),history=ownershipHistory(db,u.searchParams.get("snapshotId")??undefined).filter((snapshot:any)=>{try{return [...ownershipEndpointSlugs(db,{snapshotId:snapshot.snapshotId})].every(company=>visible.has(company));}catch{return false;}});const asOf=u.searchParams.get("asOf");const graph=asOf?queryOwnershipGraph(db,{asOf,visibleCompanySlugs:visible}):null;return okResponse({history,projection:asOf&&!graph!.partial?projectExactCompanyOwnership(db,asOf):undefined});}finally{db.close();}}
export async function handleOwnershipAction(config:ServerConfig,slug:string,request:Request,action:"propose"|"review"|"apply"):Promise<Response>{const result=await withCompanyMutation(request,config,slug,(ctx,body)=>{const db=openWorkspaceControlDb(config.workspaceRoot);try{assertOwnershipEndpoints(config,ctx.principal,db,body,action==="propose"?"company.ownership.manage":"company.admin");const principal=knowledgePrincipal(ctx.principal);if(action==="propose")return {ok:true,snapshot:proposeOwnershipSnapshot(db,{...body,actor:ctx.actor.createdBy,principal}as any)};if(action==="review")return {ok:true,snapshot:reviewOwnershipSnapshot(db,{snapshotId:requireString(body,"snapshotId"),decision:requireString(body,"decision") as any,actor:ctx.actor.createdBy,principal})};return {ok:true,...applyOwnershipSnapshot(db,{snapshotId:requireString(body,"snapshotId"),snapshotHash:requireString(body,"snapshotHash"),diffHash:requireString(body,"diffHash"),actor:ctx.actor.createdBy,principal,authorized:true})};}finally{db.close();}},{requireConfirm:true});return okResponse(result);}
