// All CSS is generated by the shared StyleX precompiler. Documents remain offline.
import { documentCss, documentFontScript } from "../../design/document-html";
export function buildStyle(): string { return documentCss; }
export function fontLink(): string { return documentFontScript(); }
