import { Button, Dialog, Input, Select } from "./ui";
import { useMutationOutcome } from "../lib/useMutationOutcome";
import { useDiscardGuard } from "../lib/useDiscardGuard";
import { useRef, useState } from "react";
import { api } from "../lib/api";
import type { BankAccount } from "../lib/types";
type Props={slug:string;accounts:BankAccount[];onApplied:()=>void;onClose:()=>void};
/** Controlled one-time bank binding: this screen never offers a remap. */
export function LegacyBankBindingModal({slug,accounts,onApplied,onClose: onDismiss}:Props){const [bankAccountId,setBankAccountId]=useState(accounts.find(a=>a.ledgerAccountNo===null)?.id??0);const [ledgerAccountNo,setLedgerAccountNo]=useState("");const [cutoff,setCutoff]=useState("");const [planHash,setPlanHash]=useState("");const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);const input={bankAccountId,ledgerAccountNo,cutoff};const review=async()=>{setBusy(true);setError(null);try{setPlanHash((await api.planLegacyBinding(slug,input)).planHash);}catch(e){setError(e instanceof Error?e.message:"Planen kunne ikke oprettes");}finally{setBusy(false);}};const outcome=useMutationOutcome(onApplied);const guard=useDiscardGuard(Boolean(ledgerAccountNo || cutoff || planHash),onDismiss);const {onClose}=guard;const operationKey=useRef<string>();const apply=async()=>{if(outcome.isBlocked())return;if(!operationKey.current)operationKey.current=crypto.randomUUID();setBusy(true);setError(null);try{await outcome.run(() => api.applyLegacyBinding(slug,{...input,planHash,idempotencyKey:operationKey.current!}));onApplied();guard.dismiss();}catch(e){setError(e instanceof Error?e.message:"Binding kunne ikke gennemføres");}finally{setBusy(false);}};const ready=bankAccountId>0&&ledgerAccountNo.trim()&&cutoff;return <Dialog title="Bind tidligere uforbundet bankkonto" onClose={onClose} busy={busy}>{outcome.feedback}{guard.confirmation}<div className="page-head"><div><p className="muted">Kun NULL → bekræftet bankkonto. En eksisterende binding kan aldrig ændres her.</p></div><Button type="button" className="btn secondary" onClick={onClose}>Luk</Button></div><div className="form-grid"><label>Bankkonto<Select value={bankAccountId} onChange={e=>{setBankAccountId(Number(e.target.value));setPlanHash("");}}>{accounts.filter(a=>a.ledgerAccountNo===null).map(a=><option key={a.id} value={a.id}>{a.name} · #{a.id}</option>)}</Select></label><label>Finanskonto<Input value={ledgerAccountNo} onChange={e=>{setLedgerAccountNo(e.target.value);setPlanHash("");}} /></label><label>Cutoff<Input type="date" value={cutoff} onChange={e=>{setCutoff(e.target.value);setPlanHash("");}} /></label></div>{error&&<p className="error" role="alert">{error}</p>}{planHash&&<p className="muted">Reviewet plan {planHash.slice(0,12)}…</p>}<div className="row-actions"><Button type="button" className="btn secondary" disabled={!ready||busy} onClick={review}>{busy?"Arbejder…":"Opret plan"}</Button><Button type="button" className="btn danger" requiredPermission="company.ledger.post" disabled={outcome.blocked || !planHash||busy} onClick={apply}>Bekræft binding</Button></div></Dialog>;}
