import { Button, Dialog, Input } from "./ui";
import { useMutationOutcome } from "../lib/useMutationOutcome";
import { useDiscardGuard } from "../lib/useDiscardGuard";
import { useRef, useState } from "react";
import { api } from "../lib/api";
import type { LegacyPayableBackfillInput, LegacyPayableBackfillPlan } from "../lib/types";
type Props={slug:string;onApplied:()=>void;onClose:()=>void};
/** A deliberately explicit cockpit surface: IDs are entered, never discovered by amount. */
export function LegacyPayableBackfillModal({slug,onApplied,onClose: onDismiss}:Props){const [input,setInput]=useState<LegacyPayableBackfillInput>({purchaseJournalEntryId:0,paymentJournalEntryId:0,documentId:0,bankTransactionId:0});const [plan,setPlan]=useState<LegacyPayableBackfillPlan|null>(null);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);const update=(key:keyof LegacyPayableBackfillInput,value:string)=>{setInput({...input,[key]:Number(value)});setPlan(null);};const review=async()=>{setBusy(true);setError(null);try{setPlan(await api.planLegacyPayableBackfill(slug,input));}catch(e){setError(e instanceof Error?e.message:"Planen kunne ikke oprettes");}finally{setBusy(false);}};const outcome=useMutationOutcome(onApplied);const guard=useDiscardGuard(Object.values(input).some(value => value > 0),onDismiss);const {onClose}=guard;const operationKey=useRef<string>();const apply=async()=>{if(outcome.isBlocked())return;if(!operationKey.current)operationKey.current=crypto.randomUUID();if(!plan)return;setBusy(true);setError(null);try{await api.applyLegacyPayableBackfill(slug,{...input,planHash:plan.planHash,idempotencyKey:operationKey.current!}).catch(outcome.reject);onApplied();guard.dismiss();}catch(e){setError(e instanceof Error?e.message:"Backfill kunne ikke gennemføres");}finally{setBusy(false);}};const ready=Object.values(input).every(n=>Number.isInteger(n)&&n>0);return <Dialog title="Adoptér eksisterende kreditorbetaling" onClose={onClose} busy={busy}>{outcome.feedback}{guard.confirmation}<div className="page-head"><div><p className="muted">Kun for verificerede migrerede data. Systemet søger aldrig på beløb.</p></div><Button type="button" className="btn secondary" onClick={onClose}>Luk</Button></div><div className="form-grid">{([['purchaseJournalEntryId','Købsjournal-id'],['paymentJournalEntryId','Betalingsjournal-id'],['documentId','Bilags-id'],['bankTransactionId','Banktransaktions-id']] as const).map(([key,label])=><label key={key}>{label}<Input inputMode="numeric" value={input[key]||""} onChange={e=>update(key,e.target.value)} /></label>)}</div>{error&&<p className="error" role="alert">{error}</p>}{plan&&<p className="muted">Reviewet plan {plan.planHash.slice(0,12)}… binder præcis de indtastede identiteter.</p>}<div className="row-actions"><Button type="button" className="btn secondary" disabled={!ready||busy} onClick={review}>{busy?"Arbejder…":"Opret plan"}</Button><Button type="button" className="btn danger" requiredPermission="company.ledger.post" disabled={outcome.blocked || !plan||busy} onClick={apply}>Bekræft backfill</Button></div></Dialog>;}
