import type { CommandSpec } from "./_shared";

export const documentsSpecs: CommandSpec[] = [
  { key: "documents ingest", usage: "documents ingest --company <path> --file <path> --metadata <file.json> [--vendor-id <n>] [--force]", description: "Indlæser og validerer et bilag med metadata.", allowedFlags: ["--company", "--file", "--metadata", "--vendor-id", "--force"], examplePath: "examples/vendor-invoice.metadata.json", exampleNote: "Eksemplet er KUN --metadata-payloaden, ikke et komplet kald: gem det til en fil og send den med --metadata sammen med --company og --file." },
  { key: "documents enrich", usage: "documents enrich --company <path> --document-id <n> --metadata <file.json> --confirm yes", description: "Udfylder manglende metadata på et ubogført legacy-bilag.", allowedFlags: ["--company", "--document-id", "--metadata", "--confirm"] },
  { key: "documents set-company-context", usage: "documents set-company-context --company <path> --document-id <n> --source-reference <text> --business-use-reason <text> --confirm yes", description: "Registrerer en append-only, hash-bundet virksomheds- og forretningskontekst for et dansk forenklet købsbilag eller et ufuldstændigt standardkøbsbilag. Det ændrer aldrig fakturaens modtagerfelter og er ikke en moms-godkendelse.", allowedFlags: ["--company", "--document-id", "--source-reference", "--business-use-reason", "--confirm"] },
  { key: "documents list", usage: "documents list --company <path>", description: "Lister gemte bilag.", allowedFlags: ["--company"] },
  { key:"documents party-link-plan", usage:"documents party-link-plan --company <path> --workspace <path> --company-slug <slug> --document-id <n> --role <role> (--jurisdiction <DK> --identifier-kind <kind> --identifier <id> | --legacy-kind <kind> --legacy-id <id> --reviewed-legacy-reference <ref>)", description:"Planlægger en ikke-mutérende, evidensbundet partskobling.", allowedFlags:["--company","--workspace","--company-slug","--document-id","--role","--party-id","--jurisdiction","--identifier-kind","--identifier","--legacy-kind","--legacy-id","--reviewed-legacy-reference"] },
  { key:"documents party-link-apply", usage:"documents party-link-apply --company <path> --workspace <path> --company-slug <slug> --document-id <n> --role <role> --plan-hash <hash> [--principal service-account:<verified-id>] --confirm yes", description:"Kræver autentificeret service-token og company.master-data; principal udledes fra token, actor er separat. Anvender en eksakt, bekræftet dokument-part-plan.", allowedFlags:["--company","--workspace","--company-slug","--document-id","--role","--party-id","--jurisdiction","--identifier-kind","--identifier","--legacy-kind","--legacy-id","--reviewed-legacy-reference","--plan-hash","--principal","--idempotency-key","--confirm"] },
  { key:"documents party-link-supersede", usage:"documents party-link-supersede --company <path> --document-id <n> --role <role> --plan-hash <hash> --reason <text> [--principal service-account:<verified-id>] --confirm yes", description:"Kræver autentificeret service-token og company.master-data; principal udledes fra token, actor er separat. Superseder append-only en aktuel dokument-part-kobling.", allowedFlags:["--company","--document-id","--role","--plan-hash","--reason","--principal","--confirm"] },
  { key:"documents party-link-inspect", usage:"documents party-link-inspect --company <path> --document-id <n>", description:"Viser aktuel part og provenance for et bilag.", allowedFlags:["--company","--document-id"] },
  { key:"documents party-link-list", usage:"documents party-link-list --company <path> [--status linked|unlinked]", description:"Lister bilag med eller uden aktuel partskobling.", allowedFlags:["--company","--status"] },
  { key:"documents internal-no-external-party", usage:"documents internal-no-external-party --company <path> --document-id <n> --reason <text> [--principal service-account:<verified-id>] --idempotency-key <key> --confirm yes --actor <id>", description:"Kræver autentificeret service-token og company.master-data; principal udledes fra token, actor er separat. Bekræfter append-only, hash-bundet at et internt bilag bevidst ikke har ekstern modpart.", allowedFlags:["--company","--document-id","--reason","--principal","--idempotency-key","--confirm","--actor"] },
  { key:"documents internal-no-external-party-supersede", usage:"documents internal-no-external-party-supersede --company <path> --document-id <n> --decision-hash <hash> --reason <text> [--principal service-account:<verified-id>] --confirm yes --actor <id>", description:"Kræver autentificeret service-token og company.master-data; principal udledes fra token, actor er separat. Supersederer den eksakte aktuelle ingen-ekstern-modpart-beslutning append-only.", allowedFlags:["--company","--document-id","--decision-hash","--reason","--principal","--confirm","--actor"] },
  { key: "documents extract-invoice", usage: "documents extract-invoice --company <path> --document-id <n>", description: "Udtrækker citerbar fakturaevidens fra et gemt PDF-bilag.", allowedFlags: ["--company", "--document-id"] },
  { key: "documents invoice-extraction", usage: "documents invoice-extraction --company <path> --document-id <n>", description: "Viser fakturaudtræk og undtagelsesstatus uden filsti.", allowedFlags: ["--company", "--document-id"] },
  { key: "documents parse", usage: "documents parse --company <path> --document-id <n> --confirm yes", description: "Parser et allerede gemt PDF-bilag offline; udfører ingen bogføring.", allowedFlags: ["--company", "--document-id", "--confirm"] },
  { key: "documents parse-pending", usage: "documents parse-pending --company <path> --confirm yes [--limit <n>] [--cursor <n>]", description: "Parser op til 100 gemte PDF-bilag uden en aktuel parse; genoptag med nextCursor som --cursor.", allowedFlags: ["--company", "--confirm", "--limit", "--cursor"] },
  { key: "documents parse-status", usage: "documents parse-status --company <path> --document-id <n>", description: "Viser den seneste PDF-parserstatus uden filsti eller child-stderr.", allowedFlags: ["--company", "--document-id"] },
  { key: "documents parsed-text", usage: "documents parsed-text --company <path> --document-id <n> [--offset <n>] [--limit <n>]", description: "Viser højst 10 parse-sider ad gangen.", allowedFlags: ["--company", "--document-id", "--offset", "--limit"] },
];
