import type { CommandSpec } from "./_shared";

export const invoiceSpecs: CommandSpec[] = [
  {
    key: "invoice validate",
    usage: "invoice validate --input <file.json>",
    description: "Validerer en faktura-payload uden at gemme den.",
    allowedFlags: ["--input"],
    examplePath: "examples/full-invoice.dk.json",
    exampleHint: "rentemester invoice validate --example > faktura.json",
    inputNotes: [
      'invoiceType: "full" | "simplified"',
      'vatTreatment: "standard" | "domestic_reverse_charge" | "foreign_reverse_charge"',
      "issueDate: YYYY-MM-DD",
      "seller, buyer, lines, totals, currency",
      "Alle beløbsfelter er i KRONER (decimal, fx 1000.00) — ikke øre",
    ],
  },
  {
    key: "invoice issue",
    usage: "invoice issue --company <path> --input <file.json> [--customer-id <n>]",
    description: "Udsteder en kundefaktura og gemmer et immutabelt snapshot.",
    allowedFlags: ["--company", "--input", "--customer-id"],
    examplePath: "examples/full-invoice.dk.json",
    exampleHint: "rentemester invoice issue --example > faktura.json",
    inputNotes: [
      'invoiceType: "full" | "simplified"',
      'vatTreatment: "standard" | "domestic_reverse_charge" | "foreign_reverse_charge"',
      "issueDate: YYYY-MM-DD",
      "invoiceNumber: valgfri; udelad for automatisk nummerering",
      "seller: { name, address, vatOrCvr }",
      "buyer: { name, address, ... }",
      "lines: [{ description, quantity, unitPriceExVat, lineTotalExVat }]",
      "totals: { netAmount, vatRate, vatAmount, grossAmount }",
      "Beløbsfelter (unitPriceExVat, lineTotalExVat, netAmount, vatAmount, grossAmount) er i KRONER (decimal) — ikke øre.",
      "totals.vatRate er en BRØK, ikke en procent: 25% moms skrives som 0.25 (ikke 25). Se examples/full-invoice.dk.json.",
      'currency: "DKK"',
      "dueDate: YYYY-MM-DD",
    ],
  },
  {
    key: "invoice create",
    usage:
      "invoice create --company <path> --issue-date <YYYY-MM-DD> --line \"beskrivelse|antal|stykpris\" [--line ... adskilt med ;] [--vat-rate <pct>] [--customer-id <n>] [--buyer-name <text>] [--buyer-address <text>] [--buyer-vat <DK...>] [--seller-name <text>] [--seller-address <text>] [--seller-vat <DK...>] [--currency <ISO>] [--due-date <YYYY-MM-DD>] [--invoice-number <no>]",
    description:
      "Udsteder en kundefaktura uden at du selv skriver JSON eller regner moms. Du angiver kun det nødvendige — kunde og pr. linje beskrivelse, antal og stykpris ekskl. moms — og Rentemester beregner linjetotaler, nettobeløb, momsbeløb og bruttobeløb, validerer og udsteder.",
    allowedFlags: [
      "--company",
      "--issue-date",
      "--line",
      "--vat-rate",
      "--customer-id",
      "--buyer-name",
      "--buyer-address",
      "--buyer-vat",
      "--seller-name",
      "--seller-address",
      "--seller-vat",
      "--currency",
      "--due-date",
      "--invoice-number",
    ],
    inputNotes: [
      "--line angiver fakturalinjer som \"beskrivelse|antal|stykpris\"; flere linjer adskilles med ; (fx \"Bogføring|2|800;Momsafstemning|1|500\")",
      "Stykpris er EKSKL. moms i KRONER (decimal). Du regner aldrig selv linjetotal, moms eller brutto.",
      "--vat-rate er momssatsen i PROCENT (fx 25 for 25%; standard 25 hvis udeladt). Bemærk: dette CLI-flag er en procent — payload-feltet totals.vatRate i 'invoice issue' er derimod en brøk (0.25).",
      "Køber: brug enten --customer-id (henter navn/adresse fra kundekartoteket) eller --buyer-name/--buyer-address direkte",
      "Sælger: --seller-name/--seller-address/--seller-vat — påkrævet hvis ikke allerede sat i payloaden",
      "Udelad --invoice-number for automatisk fortløbende nummerering",
    ],
  },
  { key: "invoice render", usage: "invoice render --company <path> (--document-id <n> | --invoice-number <no>)", description: "Returnerer og hash-verificerer den immutabelt udstedte PDF; manglende eller manipuleret evidens genskabes aldrig.", allowedFlags: ["--company", "--document-id", "--invoice-number"] },
  { key: "invoice export-public", usage: "invoice export-public --company <path> (--document-id <n> | --invoice-number <no>) --out <file.xml>", description: "Eksporterer en deterministisk preview-artifact til offentlig EAN/GLN e-faktura uden PEPPOL-transport.", allowedFlags: ["--company", "--document-id", "--invoice-number", "--out"] },
  { key: "invoice export-public-oioubl", usage: "invoice export-public-oioubl --company <path> (--document-id <n> | --invoice-number <no>) --out <file.xml>", description: "Eksporterer et deterministisk OIOUBL-handoff-artifact til offentlig e-faktura uden direkte PEPPOL-submission.", allowedFlags: ["--company", "--document-id", "--invoice-number", "--out"] },
  // PEPPOL submission (#128)
  { key: "invoice submit-public-peppol", usage: "invoice submit-public-peppol --company <path> (--document-id <n> | --invoice-number <no>) --access-point <file.json> [--out <file.xml>]", description: "Bygger en deterministisk, idempotent PEPPOL-submission-envelope oven på OIOUBL-handoff-artifaktet. Access-point-config læses fra fil; credentials gemmes aldrig i bogføringstilstanden.", allowedFlags: ["--company", "--document-id", "--invoice-number", "--access-point", "--out"] },
  // Digisense e-faktura-transport (#efaktura)
  {
    key: "invoice transmit-digisense",
    usage: "invoice transmit-digisense --company <path> (--document-id <n> | --invoice-number <no>) --confirm yes [--digisense-company-key <key>]",
    description:
      "Sender en offentlig e-faktura gennem Digisense' access point: validate-document (schematron) -> deliver-document -> poll til delivered, og bogfører en succes som en acknowledged PEPPOL-submission. License-key hentes fra secret-laget (config/digisense.json) — gem den først med `efaktura konfigurer`. companyKey resolves fra Digisense-state eller --digisense-company-key.",
    allowedFlags: ["--company", "--document-id", "--invoice-number", "--digisense-company-key", "--confirm"],
    inputNotes: [
      "INTET --access-point: for Digisense ER access point'et Digisense selv (routing på companyKey + license-key). Access-point-identiteten udledes deterministisk af companyKey, så gentaget transmit af samme faktura er idempotent og aldrig leverer dobbelt.",
      "--confirm yes: påkrævet bekræftelse; kommandoen kræver også en actor.",
      "Forudsætter en gemt license-key (`efaktura konfigurer --api-license-key ...`) og en registreret virksomhed (`efaktura registrer`).",
    ],
  },
  {
    key: "invoice credit-note",
    usage: "invoice credit-note --company <path> --input <file.json>",
    description: "Udsteder en kreditnota mod en eksisterende faktura.",
    allowedFlags: ["--company", "--input"],
    examplePath: "examples/credit-note.json",
    inputNotes: [
      "originalInvoiceNumber: fakturanummer (fx \"2026-0001\") ELLER originalInvoiceDocumentId: heltal — én af dem påkrævet",
      "issueDate: YYYY-MM-DD (påkrævet)",
      "reason: tekst (påkrævet)",
      "grossAmount: valgfrit beløb i KRONER (decimal) — udelad for fuld kreditering af fakturaen",
      "creditNoteNumber: valgfri; udelad for automatisk nummerering",
    ],
  },
  { key: "invoice post", usage: "invoice post --company <path> (--document-id <n> | --invoice-number <no>)", description: "Bogfører en udstedt faktura i finansen.", allowedFlags: ["--company", "--document-id", "--invoice-number"] },
  {
    key: "invoice repair-posting",
    usage: "invoice repair-posting --company <path> (--document-id <n> | --invoice-number <no>) --legacy-journal-entry-id <n> --reason <text>",
    description: "Erstatter atomisk én navngivet, uklassificeret legacy-fakturajournal med den kanoniske bogføring og en modpostering.",
    allowedFlags: ["--company", "--document-id", "--invoice-number", "--legacy-journal-entry-id", "--reason"],
    inputNotes: [
      "Administrativ reparationssti: journal-id'et skal angives eksplicit og må ikke have betalinger, krav, kreditnotaer eller anden følge-evidens.",
      "Både fakturadatoens og legacy-journalens regnskabsperioder skal være åbne; lukkede perioder skal genåbnes særskilt af en autoriseret bruger.",
    ],
  },
  {
    key: "invoice settle-bank",
    usage: "invoice settle-bank --company <path> --input <file.json>",
    description: "Matcher en bankbetaling mod en faktura.",
    allowedFlags: ["--company", "--input"],
    examplePath: "examples/invoice-settlement.json",
    inputNotes: [
      "invoiceNumber: fakturanummer (fx \"2026-0001\") ELLER invoiceDocumentId: heltal — én af dem påkrævet",
      "bankTransactionReference: bankpostens reference ELLER bankTransactionId: heltal — én af dem påkrævet",
      "paymentDate: valgfri YYYY-MM-DD — udelad for at bruge bankpostens dato",
      "amount: valgfrit beløb i KRONER (decimal) — udelad for at bruge bankpostens beløb",
      "bankAccountNo / receivableAccountNo: valgfri kontonumre (standard 2000 / 1100)",
    ],
  },
  {
    key: "invoice settle-claim-bank",
    usage: "invoice settle-claim-bank --company <path> --input <file.json>",
    description: "Matcher en bankbetaling mod fakturakrav.",
    allowedFlags: ["--company", "--input"],
    examplePath: "examples/invoice-claim-settlement.json",
    inputNotes: [
      "invoiceNumber: fakturanummer (fx \"2026-0001\") ELLER invoiceDocumentId: heltal — én af dem påkrævet",
      "bankTransactionReference: bankpostens reference ELLER bankTransactionId: heltal — én af dem påkrævet",
      "paymentDate: valgfri YYYY-MM-DD — udelad for at bruge bankpostens dato",
      "amount: valgfrit beløb i KRONER (decimal) — udelad for at bruge bankpostens beløb",
      "bankAccountNo / receivableAccountNo: valgfri kontonumre (standard 2000 / 1100)",
    ],
  },
  {
    key: "invoice write-off-bad-debt",
    usage: "invoice write-off-bad-debt --company <path> --input <file.json>",
    description: "Bogfører tab på debitor.",
    allowedFlags: ["--company", "--input"],
    examplePath: "examples/invoice-bad-debt-writeoff.json",
    inputNotes: [
      "invoiceNumber: fakturanummer (fx \"2026-0001\") ELLER invoiceDocumentId: heltal — én af dem påkrævet",
      "writeOffDate: YYYY-MM-DD (påkrævet)",
      "grossAmount: valgfrit positivt beløb i KRONER (decimal) — udelad for at afskrive hele den åbne saldo",
      "expenseAccountNo / receivableAccountNo / vatAccountNo: valgfri kontonumre",
      "note: valgfri tekst",
    ],
  },
  {
    key: "invoice refund-bank",
    usage: "invoice refund-bank --company <path> --input <file.json>",
    description: "Bogfører refundering til kunden fra banken.",
    allowedFlags: ["--company", "--input"],
    examplePath: "examples/invoice-refund.json",
    inputNotes: [
      "invoiceNumber: fakturanummer (fx \"2026-0001\") ELLER invoiceDocumentId: heltal — én af dem påkrævet",
      "bankTransactionReference: bankpostens reference ELLER bankTransactionId: heltal — én af dem påkrævet (skal være en udgående postering)",
      "refundDate: valgfri YYYY-MM-DD — udelad for at bruge bankpostens dato",
      "amount: valgfrit beløb i KRONER (decimal) — udelad for at bruge bankpostens beløb (numerisk værdi)",
      "bankAccountNo / receivableAccountNo: valgfri kontonumre (standard 2000 / 1100)",
    ],
  },
  {
    key: "invoice apply-payment",
    usage: "invoice apply-payment --company <path> --input <file.json>",
    description: "Registrerer en fakturabetaling direkte fra payload.",
    allowedFlags: ["--company", "--input"],
    examplePath: "examples/invoice-payment.json",
    inputNotes: [
      "invoiceNumber: fakturanummer (fx \"2026-0001\") ELLER invoiceDocumentId: heltal — én af dem påkrævet",
      "paymentDate: YYYY-MM-DD (påkrævet)",
      "amount: positivt beløb i KRONER (decimal, fx 1250.00) — påkrævet",
      "bankTransactionId / journalEntryId: valgfri heltal — knytter betalingen til en bankpost/finanspostering",
      "bankAccountNo / receivableAccountNo: valgfri kontonumre",
      "note: valgfri tekst",
    ],
  },
  { key: "invoice remind", usage: "invoice remind --company <path> (--document-id <n> | --invoice-number <no>) --date <YYYY-MM-DD> [--fee <n>] [--note <text>]", description: "Registrerer en rykker på en forfalden faktura.", allowedFlags: ["--company", "--document-id", "--invoice-number", "--date", "--fee", "--note"] },
  { key: "invoice post-reminder", usage: "invoice post-reminder --company <path> (--document-id <n> | --invoice-number <no>) [--reminder-id <n>] [--date <YYYY-MM-DD>]", description: "Bogfører en registreret rykker.", allowedFlags: ["--company", "--document-id", "--invoice-number", "--reminder-id", "--date"] },
  { key: "invoice status", usage: "invoice status --company <path> (--document-id <n> | --invoice-number <no>) [--as-of <YYYY-MM-DD>]", description: "Viser åben saldo og status på en faktura.", allowedFlags: ["--company", "--document-id", "--invoice-number", "--as-of"] },
  {
    key: "invoice list",
    usage:
      "invoice list --company <path> [--status open|paid|credited|refunded|overpaid|written_off|overdue|all] [--from <YYYY-MM-DD>] [--to <YYYY-MM-DD>] [--customer-cvr <DK...>] [--customer <text>] [--invoice-number <no>] [--min-amount <n>] [--max-amount <n>] [--as-of <YYYY-MM-DD>]",
    description: "Lister udstedte fakturaer med filtre for status, kunde og dato.",
    allowedFlags: ["--company", "--status", "--from", "--to", "--customer-cvr", "--customer", "--invoice-number", "--min-amount", "--max-amount", "--as-of"],
  },
  { key: "invoice imported-receivables", usage: "invoice imported-receivables --company <path> --as-of <YYYY-MM-DD>", description: "Lister kildebeviste importerede tilgodehavender. De er ikke Rentemester-udstedte fakturaer.", allowedFlags: ["--company", "--as-of"] },
  { key: "invoice imported-receivables-backfill-plan", usage: "invoice imported-receivables-backfill-plan --company <path> --input <artifact.json>", description: "Planlægger read-only en hash-bundet legacy Dinero-debitorbackfill uden at genafspille importen.", allowedFlags: ["--company", "--input"] },
  { key: "invoice imported-receivables-backfill-apply", usage: "invoice imported-receivables-backfill-apply --company <path> --input <artifact.json> --plan-hash <sha256> --idempotency-key <key> --principal-kind user|service-account --principal-subject-id <id> --confirm yes", description: "Appender den eksakt reviewede legacy Dinero-debitorplan uden at ændre journaler, dokumenter eller arkivår.", allowedFlags: ["--company", "--input", "--plan-hash", "--idempotency-key", "--principal-kind", "--principal-subject-id", "--confirm"] },
  { key: "invoice imported-receivable-settlement-plan", usage: "invoice imported-receivable-settlement-plan --company <path> --input <settlement.json>", description: "Planlægger read-only en hash-bundet afregning af ét importeret DKK-tilgodehavende mod én bankpost.", allowedFlags: ["--company", "--input"] },
  { key: "invoice imported-receivable-settlement-apply", usage: "invoice imported-receivable-settlement-apply --company <path> --input <settlement.json> --plan-hash <sha256> --idempotency-key <key> --principal-kind user|service-account --principal-subject-id <id> --confirm yes", description: "Bogfører og afstemmer præcis den reviewede importerede debitorafregning append-only.", allowedFlags: ["--company", "--input", "--plan-hash", "--idempotency-key", "--principal-kind", "--principal-subject-id", "--confirm"] },
  { key: "invoice imported-receivable-settlement-status", usage: "invoice imported-receivable-settlement-status --company <path> --bank-transaction-id <n>", description: "Læser den immutable afregning bundet til en bankpost.", allowedFlags: ["--company", "--bank-transaction-id"] },
  { key: "invoice find", usage: "invoice find --company <path> [<query>] [--customer <text>] [--amount <n>] [--invoice-number <no>] [--as-of <YYYY-MM-DD>]", description: "Finder udstedte fakturaer via nummer, kunde eller beløb.", allowedFlags: ["--company", "--customer", "--amount", "--invoice-number", "--as-of"] },
  { key: "invoice overdue", usage: "invoice overdue --company <path> [--as-of <YYYY-MM-DD>] [--min-days <n>]", description: "Lister forfaldne udstedte fakturaer som ikke er fuldt afregnet.", allowedFlags: ["--company", "--as-of", "--min-days"] },
  { key: "invoice interest", usage: "invoice interest --company <path> (--document-id <n> | --invoice-number <no>) --as-of <YYYY-MM-DD> --reference-rate <pct>", description: "Beregner morarente på en faktura.", allowedFlags: ["--company", "--document-id", "--invoice-number", "--as-of", "--reference-rate"] },
  { key: "invoice claim-interest", usage: "invoice claim-interest --company <path> (--document-id <n> | --invoice-number <no>) --as-of <YYYY-MM-DD> --reference-rate <pct> [--note <text>]", description: "Registrerer et morarentekrav.", allowedFlags: ["--company", "--document-id", "--invoice-number", "--as-of", "--reference-rate", "--note"] },
  { key: "invoice post-interest", usage: "invoice post-interest --company <path> (--document-id <n> | --invoice-number <no>) [--claim-id <n>] [--date <YYYY-MM-DD>]", description: "Bogfører et registreret morarentekrav.", allowedFlags: ["--company", "--document-id", "--invoice-number", "--claim-id", "--date"] },
  { key: "invoice interest-correction", usage: "invoice interest-correction --company <path> (--document-id <n> | --invoice-number <no>)", description: "Foreslår en korrektion af for meget opkrævet morarente (fx efter en bagud-dateret betaling).", allowedFlags: ["--company", "--document-id", "--invoice-number"] },
  { key: "invoice post-interest-correction", usage: "invoice post-interest-correction --company <path> (--document-id <n> | --invoice-number <no>) [--date <YYYY-MM-DD>] [--reason <text>]", description: "Bogfører en korrektion af for meget opkrævet morarente.", allowedFlags: ["--company", "--document-id", "--invoice-number", "--date", "--reason"] },
  { key: "invoice compensation", usage: "invoice compensation --company <path> (--document-id <n> | --invoice-number <no>) --as-of <YYYY-MM-DD> [--amount-dkk <n>]", description: "Beregner kompensationskrav for sen betaling.", allowedFlags: ["--company", "--document-id", "--invoice-number", "--as-of", "--amount-dkk"] },
  { key: "invoice claim-compensation", usage: "invoice claim-compensation --company <path> (--document-id <n> | --invoice-number <no>) --as-of <YYYY-MM-DD> [--amount-dkk <n>] [--note <text>]", description: "Registrerer kompensationskrav.", allowedFlags: ["--company", "--document-id", "--invoice-number", "--as-of", "--amount-dkk", "--note"] },
  { key: "invoice post-compensation", usage: "invoice post-compensation --company <path> (--document-id <n> | --invoice-number <no>) [--date <YYYY-MM-DD>]", description: "Bogfører registreret kompensation.", allowedFlags: ["--company", "--document-id", "--invoice-number", "--date"] },
];

// ===== EMAIL DELIVERY (#180) =====
export const invoiceSendSpec: CommandSpec[] = [
  {
    key: "invoice send",
    usage: "invoice send --company <path> (--document-id <n> | --invoice-number <no>) [--kind invoice|reminder] [--to <email>]",
    description: "Sender en udstedt faktura eller en betalingspåmindelse til kundens email via SMTP med PDF'en vedhæftet, og logger afsendelsen append-only. SMTP-config læses fra config/smtp.json; credentials gemmes aldrig i bogføringstilstanden. Idempotent: en identisk afsendelse genudsendes ikke.",
    allowedFlags: ["--company", "--document-id", "--invoice-number", "--kind", "--to"],
    inputNotes: [
      "SMTP-config (host, port, fromAddress, fromName, dryRun) læses fra config/smtp.json",
      "Den indbyggede SMTP-transport er DRY-RUN: den validerer og logger afsendelsen, men sender ingen rigtig email. Reel levering kræver en ekstern SMTP-integration — afsendelsen markeres derfor i loggen, ikke i kundens indbakke.",
      "--to overstyrer modtageren; ellers slås kundens email op fra kundekartoteket",
      "--kind reminder kræver at fakturaen er udstedt; standard er invoice",
    ],
  },
];
