import type { CommandSpec } from "./_shared";

export const purchaseCaseSpecs: CommandSpec[] = [
  { key: "purchase-case list", usage: "purchase-case list --company <path>", description: "Læs de aktuelle purchase cases uden mutation.", allowedFlags: ["--company"] },
  { key: "purchase-case show", usage: "purchase-case show --company <path> --case-id <id>", description: "Læs én current purchase case uden mutation.", allowedFlags: ["--company", "--case-id"] },
  { key: "purchase-case overview", usage: "purchase-case overview --company <path> --from YYYY-MM-DD --to YYYY-MM-DD [--include-provisional yes|no]", description: "Læs forklarligt purchase-overblik og grouped human-needs uden mutation.", allowedFlags: ["--company", "--from", "--to", "--include-provisional"] },
  { key: "purchase-case create", usage: "purchase-case create --company <path> --source-kind <document|bank_transaction|payable> --source-id <n> --idempotency-key <key> --confirm yes --actor <actor>", description: "Opretter en kildebundet foreløbig purchase case uden ledger- eller VAT-mutation.", allowedFlags: ["--company", "--case-id", "--source-kind", "--source-id", "--documentation-outcome", "--note", "--idempotency-key", "--confirm", "--actor"] },
  { key: "purchase-case review", usage: "purchase-case review --company <path> --case-id <id> --expected-version <n> --expected-source-fingerprint <sha256> [--expected-policy-event-hash <sha256>] --documentation-outcome <outcome> --idempotency-key <key> --confirm yes --actor <actor>", description: "Appender et exact kildebundet review under den aktuelle approval-policy uden ledger- eller VAT-mutation.", allowedFlags: ["--company", "--case-id", "--expected-version", "--expected-source-fingerprint", "--expected-policy-event-hash", "--documentation-outcome", "--note", "--idempotency-key", "--confirm", "--actor"] },
  { key: "purchase-case group-review", usage: "purchase-case group-review --company <path> --members-json <json> [--expected-policy-event-hash <sha256>] --documentation-outcome <outcome> --idempotency-key <key> --confirm yes --actor <actor>", description: "Preflighter og reviewer atomisk én eksakt gruppe under den aktuelle approval-policy uden ledger- eller VAT-mutation.", allowedFlags: ["--company", "--group-id", "--members-json", "--expected-policy-event-hash", "--documentation-outcome", "--note", "--idempotency-key", "--confirm", "--actor"] },
];
