import { createHash } from "node:crypto";
import { readFile, mkdir, rename, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { transformSync } from "@babel/core";
import stylexBabelPlugin from "@stylexjs/babel-plugin";
import * as stylexRuntime from "@stylexjs/stylex";
import { compileStylex } from "../../scripts/stylex-precompile";

export const websiteRoot = join(import.meta.dir, "..");
export const websiteStyleSources = [join(websiteRoot, "src/site.stylex.ts"), join(websiteRoot, "src/og.stylex.ts"), join(websiteRoot, "../DESIGN.md")];
const dependencies = { transformSync, stylexBabelPlugin, processStylexRules: stylexBabelPlugin.processStylexRules, stylexRuntime };

async function publish(path: string, contents: string): Promise<void> {
  try { if (await readFile(path, "utf8") === contents) return; } catch {}
  await mkdir(dirname(path), { recursive: true });
  const temporary = `${path}.${process.pid}.tmp`;
  await writeFile(temporary, contents);
  await rename(temporary, path);
}

/** Publish CSS first. A failed compile cannot expose attributes without their stylesheet. */
export async function compileWebsite(root = websiteRoot): Promise<void> {
  const [siteSource, ogSource, design] = await Promise.all([
    readFile(join(root, "src/site.stylex.ts"), "utf8"),
    readFile(join(root, "src/og.stylex.ts"), "utf8"),
    readFile(join(root, "../DESIGN.md"), "utf8"),
  ]);
  const frontmatter = design.match(/^---\n([\s\S]*?)\n---/);
  if (!frontmatter) throw new Error("DESIGN.md must contain token frontmatter");
  const marketing = (Bun.YAML.parse(frontmatter[1]) as { marketing?: { colors: Record<string, string> } }).marketing;
  if (!marketing) throw new Error("DESIGN.md must contain marketing tokens");
  const alpha = Object.fromEntries(Object.entries(marketing.colors).map(([role, hex]) => {
    if (!/^#[0-9a-f]{6}$/i.test(hex)) throw new Error("Marketing colors must use six-digit hex values");
    const rgb = [1, 3, 5].map(offset => parseInt(hex.slice(offset, offset + 2), 16)).join(" ");
    return [role, Object.fromEntries(Array.from({ length: 101 }, (_, n) => [String(n / 100), "rgb(" + rgb + " / " + n / 100 + ")"]))];
  }));
  const prefix = "const marketing = " + JSON.stringify({ ...marketing, alpha }) + ";\n";
  const prepared = (source: string) => prefix + source.replace(/^declare const marketing:.*?;\s*$/m, "");
  const site = compileStylex(prepared(siteSource), "www/src/site.stylex.ts", dependencies);
  const og = compileStylex(prepared(ogSource), "www/src/og.stylex.ts", dependencies);
  const cssHash = createHash("sha256").update(site.css).digest("hex").slice(0, 16);
  const cssHref = `/_stylex/site-${cssHash}.css`;
  await publish(join(root, "public", cssHref), site.css);
  await publish(join(root, ".stylex/og-stylex.ts"), `// Generated by StyleX; edit src/og.stylex.ts.\nexport const attributes = ${JSON.stringify(og.attributes, null, 2)} as const;\nexport const css = ${JSON.stringify(og.css)};\nexport const sourceHash = ${JSON.stringify(og.sourceHash)};\n`);
  await publish(join(root, ".stylex/site-stylex.ts"), `// Generated by StyleX; edit src/site.stylex.ts.\nexport const attributes = ${JSON.stringify(site.attributes, null, 2)} as const;\nexport const cssHref = ${JSON.stringify(cssHref)};\nexport const sourceHash = ${JSON.stringify(site.sourceHash)};\n`);
}

if (import.meta.main) await compileWebsite();
