/** Explicit, reviewed MCP operation identities. Do not infer boundaries from original names. */

export type McpOperationNaming = Readonly<{
  originalName: string;
  canonicalName: string;
  domain: string;
  resource: string;
  action: string;
}>;

export const MCP_OPERATION_NAMING: Readonly<Record<string, McpOperationNaming>> = Object.freeze({
  "accounts_roles_status": {"originalName":"accounts_roles_status","canonicalName":"accounting_account_role_status","domain":"accounting","resource":"account_role","action":"status"},
  "accounts_role_confirm": {"originalName":"accounts_role_confirm","canonicalName":"accounting_account_role_confirm","domain":"accounting","resource":"account_role","action":"confirm"},
  "accounts_list": {"originalName":"accounts_list","canonicalName":"accounting_account_list","domain":"accounting","resource":"account","action":"list"},
  "accounts_add": {"originalName":"accounts_add","canonicalName":"accounting_account_add","domain":"accounting","resource":"account","action":"add"},
  "audit_verify": {"originalName":"audit_verify","canonicalName":"system_audit_verify","domain":"system","resource":"audit","action":"verify"},
  "audit_log_list": {"originalName":"audit_log_list","canonicalName":"system_log_list","domain":"system","resource":"log","action":"list"},
  "bank_legacy_binding_plan": {"originalName":"bank_legacy_binding_plan","canonicalName":"banking_legacy_binding_plan","domain":"banking","resource":"legacy_binding","action":"plan"},
  "bank_legacy_binding_apply": {"originalName":"bank_legacy_binding_apply","canonicalName":"banking_legacy_binding_apply","domain":"banking","resource":"legacy_binding","action":"apply"},
  "payable_legacy_backfill_plan": {"originalName":"payable_legacy_backfill_plan","canonicalName":"purchasing_legacy_payable_backfill_plan","domain":"purchasing","resource":"legacy_payable_backfill","action":"plan"},
  "payable_legacy_backfill_apply": {"originalName":"payable_legacy_backfill_apply","canonicalName":"purchasing_legacy_payable_backfill_apply","domain":"purchasing","resource":"legacy_payable_backfill","action":"apply"},
  "direct_bank_purchase_payable_correction_plan": {"originalName":"direct_bank_purchase_payable_correction_plan","canonicalName":"banking_bank_purchase_payable_correction_plan","domain":"banking","resource":"bank_purchase_payable_correction","action":"plan"},
  "direct_bank_purchase_payable_correction_apply": {"originalName":"direct_bank_purchase_payable_correction_apply","canonicalName":"banking_bank_purchase_payable_correction_apply","domain":"banking","resource":"bank_purchase_payable_correction","action":"apply"},
  "bank_reconciliation_correction_plan": {"originalName":"bank_reconciliation_correction_plan","canonicalName":"banking_reconciliation_correction_plan","domain":"banking","resource":"reconciliation_correction","action":"plan"},
  "bank_reconciliation_correction_apply": {"originalName":"bank_reconciliation_correction_apply","canonicalName":"banking_reconciliation_correction_apply","domain":"banking","resource":"reconciliation_correction","action":"apply"},
  "bank_account_update": {"originalName":"bank_account_update","canonicalName":"banking_account_update","domain":"banking","resource":"account","action":"update"},
  "bank_list": {"originalName":"bank_list","canonicalName":"banking_bank_list","domain":"banking","resource":"bank","action":"list"},
  "bank_suggest_matches": {"originalName":"bank_suggest_matches","canonicalName":"banking_bank_match_suggest","domain":"banking","resource":"bank_match","action":"suggest"},
  "reconcile_bank": {"originalName":"reconcile_bank","canonicalName":"banking_bank_reconcile","domain":"banking","resource":"bank","action":"reconcile"},
  "bank_import": {"originalName":"bank_import","canonicalName":"banking_bank_import","domain":"banking","resource":"bank","action":"import"},
  "bank_account_list": {"originalName":"bank_account_list","canonicalName":"banking_account_list","domain":"banking","resource":"account","action":"list"},
  "customer_list": {"originalName":"customer_list","canonicalName":"sales_customer_list","domain":"sales","resource":"customer","action":"list"},
  "customer_validate_vat": {"originalName":"customer_validate_vat","canonicalName":"sales_customer_vat_validate","domain":"sales","resource":"customer_vat","action":"validate"},
  "customer_create": {"originalName":"customer_create","canonicalName":"sales_customer_create","domain":"sales","resource":"customer","action":"create"},
  "cvr_lookup": {"originalName":"cvr_lookup","canonicalName":"workspace_vat_lookup","domain":"workspace","resource":"vat","action":"lookup"},
  "company_sync_cvr": {"originalName":"company_sync_cvr","canonicalName":"workspace_company_vat_sync","domain":"workspace","resource":"company_vat","action":"sync"},
  "party_coverage": {"originalName":"party_coverage","canonicalName":"workspace_party_coverage_report","domain":"workspace","resource":"party_coverage","action":"report"},
  "party_coverage_plan": {"originalName":"party_coverage_plan","canonicalName":"workspace_party_coverage_plan","domain":"workspace","resource":"party_coverage","action":"plan"},
  "party_coverage_apply": {"originalName":"party_coverage_apply","canonicalName":"workspace_party_coverage_apply","domain":"workspace","resource":"party_coverage","action":"apply"},
  "documents_party_link_plan": {"originalName":"documents_party_link_plan","canonicalName":"documents_party_link_plan","domain":"documents","resource":"party_link","action":"plan"},
  "documents_party_link_list": {"originalName":"documents_party_link_list","canonicalName":"documents_party_link_list","domain":"documents","resource":"party_link","action":"list"},
  "documents_party_link_inspect": {"originalName":"documents_party_link_inspect","canonicalName":"documents_party_link_inspect","domain":"documents","resource":"party_link","action":"inspect"},
  "documents_party_link_apply": {"originalName":"documents_party_link_apply","canonicalName":"documents_party_link_apply","domain":"documents","resource":"party_link","action":"apply"},
  "documents_party_link_supersede": {"originalName":"documents_party_link_supersede","canonicalName":"documents_party_link_supersede","domain":"documents","resource":"party_link","action":"supersede"},
  "documents_internal_no_external_party": {"originalName":"documents_internal_no_external_party","canonicalName":"documents_internal_party_classify","domain":"documents","resource":"internal_party","action":"classify"},
  "documents_internal_no_external_party_supersede": {"originalName":"documents_internal_no_external_party_supersede","canonicalName":"documents_internal_party_supersede","domain":"documents","resource":"internal_party","action":"supersede"},
  "documents_set_company_context": {"originalName":"documents_set_company_context","canonicalName":"documents_company_context_set","domain":"documents","resource":"company_context","action":"set"},
  "documents_review_purchase_vat_evidence": {"originalName":"documents_review_purchase_vat_evidence","canonicalName":"documents_purchase_vat_evidence_review","domain":"documents","resource":"purchase_vat_evidence","action":"review"},
  "documents_review_non_eu_reverse_charge_evidence": {"originalName":"documents_review_non_eu_reverse_charge_evidence","canonicalName":"documents_non_eu_reverse_charge_evidence_review","domain":"documents","resource":"non_eu_reverse_charge_evidence","action":"review"},
  "documents_enrich": {"originalName":"documents_enrich","canonicalName":"documents_document_enrich","domain":"documents","resource":"document","action":"enrich"},
  "documents_parse": {"originalName":"documents_parse","canonicalName":"documents_document_parse","domain":"documents","resource":"document","action":"parse"},
  "documents_parse_pending": {"originalName":"documents_parse_pending","canonicalName":"documents_parse_pending_status","domain":"documents","resource":"parse_pending","action":"status"},
  "documents_parse_status": {"originalName":"documents_parse_status","canonicalName":"documents_parse_status","domain":"documents","resource":"parse","action":"status"},
  "documents_parsed_text": {"originalName":"documents_parsed_text","canonicalName":"documents_parsed_text_read","domain":"documents","resource":"parsed_text","action":"read"},
  "documents_invoice_extraction": {"originalName":"documents_invoice_extraction","canonicalName":"documents_invoice_extraction_get","domain":"documents","resource":"invoice_extraction","action":"get"},
  "documents_extract_invoice": {"originalName":"documents_extract_invoice","canonicalName":"documents_invoice_extract","domain":"documents","resource":"invoice","action":"extract"},
  "documents_list": {"originalName":"documents_list","canonicalName":"documents_document_list","domain":"documents","resource":"document","action":"list"},
  "documents_ingest": {"originalName":"documents_ingest","canonicalName":"documents_document_ingest","domain":"documents","resource":"document","action":"ingest"},
  "dimension_assignment_plan": {"originalName":"dimension_assignment_plan","canonicalName":"accounting_assignment_plan","domain":"accounting","resource":"assignment","action":"plan"},
  "dimension_assignment_list": {"originalName":"dimension_assignment_list","canonicalName":"accounting_assignment_list","domain":"accounting","resource":"assignment","action":"list"},
  "dimension_definition_list": {"originalName":"dimension_definition_list","canonicalName":"accounting_definition_list","domain":"accounting","resource":"definition","action":"list"},
  "dimension_member_list": {"originalName":"dimension_member_list","canonicalName":"accounting_member_list","domain":"accounting","resource":"member","action":"list"},
  "dimension_definition_create": {"originalName":"dimension_definition_create","canonicalName":"accounting_definition_create","domain":"accounting","resource":"definition","action":"create"},
  "dimension_member_create": {"originalName":"dimension_member_create","canonicalName":"accounting_member_create","domain":"accounting","resource":"member","action":"create"},
  "dimension_definition_lifecycle": {"originalName":"dimension_definition_lifecycle","canonicalName":"accounting_definition_review","domain":"accounting","resource":"definition","action":"review"},
  "dimension_member_lifecycle": {"originalName":"dimension_member_lifecycle","canonicalName":"accounting_member_review","domain":"accounting","resource":"member","action":"review"},
  "dimension_assignment_apply": {"originalName":"dimension_assignment_apply","canonicalName":"accounting_assignment_apply","domain":"accounting","resource":"assignment","action":"apply"},
  "dimension_assignment_replace": {"originalName":"dimension_assignment_replace","canonicalName":"accounting_assignment_replace","domain":"accounting","resource":"assignment","action":"replace"},
  "dimension_assignment_supersede": {"originalName":"dimension_assignment_supersede","canonicalName":"accounting_assignment_supersede","domain":"accounting","resource":"assignment","action":"supersede"},
  "dimension_budget_plan": {"originalName":"dimension_budget_plan","canonicalName":"accounting_budget_plan","domain":"accounting","resource":"budget","action":"plan"},
  "dimension_budget_apply": {"originalName":"dimension_budget_apply","canonicalName":"accounting_budget_apply","domain":"accounting","resource":"budget","action":"apply"},
  "dimension_budget_list": {"originalName":"dimension_budget_list","canonicalName":"accounting_budget_list","domain":"accounting","resource":"budget","action":"list"},
  "exceptions_list": {"originalName":"exceptions_list","canonicalName":"accounting_exception_list","domain":"accounting","resource":"exception","action":"list"},
  "exception_resolve": {"originalName":"exception_resolve","canonicalName":"accounting_exception_resolve","domain":"accounting","resource":"exception","action":"resolve"},
  "expense_vat_preflight": {"originalName":"expense_vat_preflight","canonicalName":"expenses_vat_preflight","domain":"expenses","resource":"vat","action":"preflight"},
  "expense_vat_preflight_apply": {"originalName":"expense_vat_preflight_apply","canonicalName":"expenses_vat_preflight_apply","domain":"expenses","resource":"vat_preflight","action":"apply"},
  "expense_book": {"originalName":"expense_book","canonicalName":"purchasing_expense_book","domain":"purchasing","resource":"expense","action":"book"},
  "invoice_imported_receivables": {"originalName":"invoice_imported_receivables","canonicalName":"sales_imported_receivable_list","domain":"sales","resource":"imported_receivable","action":"list"},
  "invoice_validate": {"originalName":"invoice_validate","canonicalName":"sales_invoice_validate","domain":"sales","resource":"invoice","action":"validate"},
  "invoice_status": {"originalName":"invoice_status","canonicalName":"sales_invoice_status","domain":"sales","resource":"invoice","action":"status"},
  "invoice_list": {"originalName":"invoice_list","canonicalName":"sales_invoice_list","domain":"sales","resource":"invoice","action":"list"},
  "invoice_find": {"originalName":"invoice_find","canonicalName":"sales_invoice_find","domain":"sales","resource":"invoice","action":"find"},
  "invoice_overdue": {"originalName":"invoice_overdue","canonicalName":"sales_invoice_overdue","domain":"sales","resource":"invoice","action":"overdue"},
  "invoice_interest_calc": {"originalName":"invoice_interest_calc","canonicalName":"sales_invoice_interest_calculate","domain":"sales","resource":"invoice_interest","action":"calculate"},
  "invoice_interest_correction_calc": {"originalName":"invoice_interest_correction_calc","canonicalName":"sales_invoice_interest_correction_calculate","domain":"sales","resource":"invoice_interest_correction","action":"calculate"},
  "invoice_compensation_calc": {"originalName":"invoice_compensation_calc","canonicalName":"sales_invoice_compensation_calculate","domain":"sales","resource":"invoice_compensation","action":"calculate"},
  "invoice_imported_receivables_backfill_plan": {"originalName":"invoice_imported_receivables_backfill_plan","canonicalName":"sales_imported_receivable_backfill_plan","domain":"sales","resource":"imported_receivable_backfill","action":"plan"},
  "invoice_imported_receivables_backfill_apply": {"originalName":"invoice_imported_receivables_backfill_apply","canonicalName":"sales_imported_receivable_backfill_apply","domain":"sales","resource":"imported_receivable_backfill","action":"apply"},
  "invoice_imported_receivable_settlement_plan": {"originalName":"invoice_imported_receivable_settlement_plan","canonicalName":"sales_imported_receivable_settlement_plan","domain":"sales","resource":"imported_receivable_settlement","action":"plan"},
  "invoice_imported_receivable_settlement_apply": {"originalName":"invoice_imported_receivable_settlement_apply","canonicalName":"sales_imported_receivable_settlement_apply","domain":"sales","resource":"imported_receivable_settlement","action":"apply"},
  "invoice_imported_receivable_settlement_status": {"originalName":"invoice_imported_receivable_settlement_status","canonicalName":"sales_imported_receivable_settlement_status","domain":"sales","resource":"imported_receivable_settlement","action":"status"},
  "invoice_issue": {"originalName":"invoice_issue","canonicalName":"sales_invoice_issue","domain":"sales","resource":"invoice","action":"issue"},
  "invoice_render": {"originalName":"invoice_render","canonicalName":"sales_invoice_render","domain":"sales","resource":"invoice","action":"render"},
  "invoice_credit_note": {"originalName":"invoice_credit_note","canonicalName":"sales_credit_note_create","domain":"sales","resource":"credit_note","action":"create"},
  "invoice_post": {"originalName":"invoice_post","canonicalName":"sales_invoice_post","domain":"sales","resource":"invoice","action":"post"},
  "invoice_settle_bank": {"originalName":"invoice_settle_bank","canonicalName":"sales_invoice_bank_settle","domain":"sales","resource":"invoice_bank","action":"settle"},
  "invoice_settle_claim_bank": {"originalName":"invoice_settle_claim_bank","canonicalName":"sales_invoice_claim_bank_settle","domain":"sales","resource":"invoice_claim_bank","action":"settle"},
  "invoice_write_off_bad_debt": {"originalName":"invoice_write_off_bad_debt","canonicalName":"sales_invoice_bad_debt_writeoff","domain":"sales","resource":"invoice_bad_debt","action":"writeoff"},
  "invoice_apply_payment": {"originalName":"invoice_apply_payment","canonicalName":"sales_invoice_payment_apply","domain":"sales","resource":"invoice_payment","action":"apply"},
  "invoice_refund_bank": {"originalName":"invoice_refund_bank","canonicalName":"sales_invoice_bank_refund","domain":"sales","resource":"invoice_bank","action":"refund"},
  "invoice_remind": {"originalName":"invoice_remind","canonicalName":"sales_invoice_remind","domain":"sales","resource":"invoice","action":"remind"},
  "invoice_post_reminder": {"originalName":"invoice_post_reminder","canonicalName":"sales_invoice_reminder_post","domain":"sales","resource":"invoice_reminder","action":"post"},
  "invoice_claim_interest": {"originalName":"invoice_claim_interest","canonicalName":"sales_invoice_interest_claim","domain":"sales","resource":"invoice_interest","action":"claim"},
  "invoice_post_interest": {"originalName":"invoice_post_interest","canonicalName":"sales_invoice_interest_post","domain":"sales","resource":"invoice_interest","action":"post"},
  "invoice_post_interest_correction": {"originalName":"invoice_post_interest_correction","canonicalName":"sales_invoice_interest_correction_correct","domain":"sales","resource":"invoice_interest_correction","action":"correct"},
  "invoice_claim_compensation": {"originalName":"invoice_claim_compensation","canonicalName":"sales_invoice_compensation_claim","domain":"sales","resource":"invoice_compensation","action":"claim"},
  "invoice_post_compensation": {"originalName":"invoice_post_compensation","canonicalName":"sales_invoice_compensation_post","domain":"sales","resource":"invoice_compensation","action":"post"},
  "journal_post": {"originalName":"journal_post","canonicalName":"accounting_journal_post","domain":"accounting","resource":"journal","action":"post"},
  "journal_dry_run": {"originalName":"journal_dry_run","canonicalName":"accounting_journal_preview","domain":"accounting","resource":"journal","action":"preview"},
  "journal_reverse": {"originalName":"journal_reverse","canonicalName":"accounting_journal_reverse","domain":"accounting","resource":"journal","action":"reverse"},
  "journal_list": {"originalName":"journal_list","canonicalName":"accounting_journal_list","domain":"accounting","resource":"journal","action":"list"},
  "peppol_submit_public_invoice": {"originalName":"peppol_submit_public_invoice","canonicalName":"external_peppol_invoice_submit","domain":"external","resource":"peppol_invoice","action":"submit"},
  "period_close_readiness": {"originalName":"period_close_readiness","canonicalName":"accounting_period_readiness","domain":"accounting","resource":"period","action":"readiness"},
  "period_close_status": {"originalName":"period_close_status","canonicalName":"accounting_period_status","domain":"accounting","resource":"period","action":"status"},
  "period_close_review": {"originalName":"period_close_review","canonicalName":"accounting_period_review","domain":"accounting","resource":"period","action":"review"},
  "period_list": {"originalName":"period_list","canonicalName":"accounting_period_list","domain":"accounting","resource":"period","action":"list"},
  "period_close": {"originalName":"period_close","canonicalName":"accounting_period_close","domain":"accounting","resource":"period","action":"close"},
  "retention_status": {"originalName":"retention_status","canonicalName":"system_retention_status","domain":"system","resource":"retention","action":"status"},
  "gdpr_discover": {"originalName":"gdpr_discover","canonicalName":"privacy_gdpr_discover","domain":"privacy","resource":"gdpr","action":"discover"},
  "gdpr_export": {"originalName":"gdpr_export","canonicalName":"privacy_gdpr_export","domain":"privacy","resource":"gdpr","action":"export"},
  "gdpr_audit_log": {"originalName":"gdpr_audit_log","canonicalName":"privacy_gdpr_audit_list","domain":"privacy","resource":"gdpr_audit","action":"list"},
  "system_healthcheck": {"originalName":"system_healthcheck","canonicalName":"system_server_healthcheck","domain":"system","resource":"server","action":"healthcheck"},
  "system_backup_status": {"originalName":"system_backup_status","canonicalName":"system_backup_status","domain":"system","resource":"backup","action":"status"},
  "system_backup": {"originalName":"system_backup","canonicalName":"system_backup_execute","domain":"system","resource":"backup","action":"execute"},
  "system_backup_archive": {"originalName":"system_backup_archive","canonicalName":"system_backup_archive","domain":"system","resource":"backup","action":"archive"},
  "system_backup_governance": {"originalName":"system_backup_governance","canonicalName":"system_backup_governance","domain":"system","resource":"backup","action":"governance"},
  "system_backup_destination_list": {"originalName":"system_backup_destination_list","canonicalName":"system_backup_destination_list","domain":"system","resource":"backup_destination","action":"list"},
  "system_backup_destination_add": {"originalName":"system_backup_destination_add","canonicalName":"system_backup_destination_add","domain":"system","resource":"backup_destination","action":"add"},
  "system_backup_destination_remove": {"originalName":"system_backup_destination_remove","canonicalName":"system_backup_destination_remove","domain":"system","resource":"backup_destination","action":"remove"},
  "system_backup_place": {"originalName":"system_backup_place","canonicalName":"system_backup_place","domain":"system","resource":"backup","action":"place"},
  "system_backup_confirm_placement": {"originalName":"system_backup_confirm_placement","canonicalName":"system_backup_placement_confirm","domain":"system","resource":"backup_placement","action":"confirm"},
  "system_backup_verify_remote_placement": {"originalName":"system_backup_verify_remote_placement","canonicalName":"system_backup_remote_placement_verify","domain":"system","resource":"backup_remote_placement","action":"verify"},
  "system_backup_lock": {"originalName":"system_backup_lock","canonicalName":"system_backup_lock","domain":"system","resource":"backup","action":"lock"},
  "system_export_authority": {"originalName":"system_export_authority","canonicalName":"system_export_authorize","domain":"system","resource":"export","action":"authorize"},
  "system_restore_backup": {"originalName":"system_restore_backup","canonicalName":"system_backup_restore","domain":"system","resource":"backup","action":"restore"},
  "vat_report": {"originalName":"vat_report","canonicalName":"tax_vat_report","domain":"tax","resource":"vat","action":"report"},
  "vat_filing": {"originalName":"vat_filing","canonicalName":"tax_vat_file","domain":"tax","resource":"vat","action":"file"},
  "vat_filing_evidence_record": {"originalName":"vat_filing_evidence_record","canonicalName":"tax_vat_filing_evidence_record","domain":"tax","resource":"vat_filing_evidence","action":"record"},
  "vat_eu_sales_list": {"originalName":"vat_eu_sales_list","canonicalName":"tax_eu_sale_list","domain":"tax","resource":"eu_sale","action":"list"},
  "vat_oss_report": {"originalName":"vat_oss_report","canonicalName":"tax_oss_filing_report","domain":"tax","resource":"oss_filing","action":"report"},
  "vat_post_eu_service_purchase": {"originalName":"vat_post_eu_service_purchase","canonicalName":"tax_eu_service_purchase_post","domain":"tax","resource":"eu_service_purchase","action":"post"},
  "vat_post_representation_purchase": {"originalName":"vat_post_representation_purchase","canonicalName":"tax_representation_purchase_post","domain":"tax","resource":"representation_purchase","action":"post"},
  "vendor_list": {"originalName":"vendor_list","canonicalName":"purchasing_vendor_list","domain":"purchasing","resource":"vendor","action":"list"},
  "vendor_create": {"originalName":"vendor_create","canonicalName":"purchasing_vendor_create","domain":"purchasing","resource":"vendor","action":"create"},
  "recurring_invoice_run_workspace": {"originalName":"recurring_invoice_run_workspace","canonicalName":"sales_recurring_invoice_run","domain":"sales","resource":"recurring_invoice","action":"run"},
  "recurring_invoice_create": {"originalName":"recurring_invoice_create","canonicalName":"sales_invoice_create","domain":"sales","resource":"invoice","action":"create"},
  "recurring_invoice_generate": {"originalName":"recurring_invoice_generate","canonicalName":"sales_invoice_generate","domain":"sales","resource":"invoice","action":"generate"},
  "recurring_invoice_list": {"originalName":"recurring_invoice_list","canonicalName":"sales_recurring_invoice_list","domain":"sales","resource":"recurring_invoice","action":"list"},
  "mail_intake_ingest": {"originalName":"mail_intake_ingest","canonicalName":"documents_intake_ingest","domain":"documents","resource":"intake","action":"ingest"},
  "imap_intake_poll": {"originalName":"imap_intake_poll","canonicalName":"documents_intake_poll","domain":"documents","resource":"intake","action":"poll"},
  "efaktura_modtag_workspace": {"originalName":"efaktura_modtag_workspace","canonicalName":"external_efaktura_workspace_receive","domain":"external","resource":"efaktura_workspace","action":"receive"},
  "efaktura_onboarding_status": {"originalName":"efaktura_onboarding_status","canonicalName":"external_efaktura_onboarding_status","domain":"external","resource":"efaktura_onboarding","action":"status"},
  "efaktura_onboard": {"originalName":"efaktura_onboard","canonicalName":"external_efaktura_onboard","domain":"external","resource":"efaktura","action":"onboard"},
  "efaktura_registrer": {"originalName":"efaktura_registrer","canonicalName":"external_efaktura_register","domain":"external","resource":"efaktura","action":"register"},
  "efaktura_modtag": {"originalName":"efaktura_modtag","canonicalName":"external_efaktura_receive","domain":"external","resource":"efaktura","action":"receive"},
  "efaktura_konfigurer": {"originalName":"efaktura_konfigurer","canonicalName":"external_efaktura_configure","domain":"external","resource":"efaktura","action":"configure"},
  "efaktura_send": {"originalName":"efaktura_send","canonicalName":"external_efaktura_send","domain":"external","resource":"efaktura","action":"send"},
  "efaktura_status": {"originalName":"efaktura_status","canonicalName":"external_efaktura_status","domain":"external","resource":"efaktura","action":"status"},
  "mileage_list": {"originalName":"mileage_list","canonicalName":"expenses_mileage_list","domain":"expenses","resource":"mileage","action":"list"},
  "mileage_report": {"originalName":"mileage_report","canonicalName":"expenses_mileage_report","domain":"expenses","resource":"mileage","action":"report"},
  "mileage_log": {"originalName":"mileage_log","canonicalName":"expenses_mileage_record","domain":"expenses","resource":"mileage","action":"record"},
  "mileage_export": {"originalName":"mileage_export","canonicalName":"expenses_mileage_export","domain":"expenses","resource":"mileage","action":"export"},
  "asset_register": {"originalName":"asset_register","canonicalName":"accounting_asset_register","domain":"accounting","resource":"asset","action":"register"},
  "asset_depreciate": {"originalName":"asset_depreciate","canonicalName":"accounting_asset_depreciate","domain":"accounting","resource":"asset","action":"depreciate"},
  "asset_write_off": {"originalName":"asset_write_off","canonicalName":"accounting_asset_writeoff","domain":"accounting","resource":"asset","action":"writeoff"},
  "asset_register_report": {"originalName":"asset_register_report","canonicalName":"accounting_asset_register_report","domain":"accounting","resource":"asset_register","action":"report"},
  "company_add": {"originalName":"company_add","canonicalName":"workspace_company_add","domain":"workspace","resource":"company","action":"add"},
  "portfolio_overview": {"originalName":"portfolio_overview","canonicalName":"workspace_portfolio_overview","domain":"workspace","resource":"portfolio","action":"overview"},
  "cfo_analytics_query": {"originalName":"cfo_analytics_query","canonicalName":"reporting_analytic_query","domain":"reporting","resource":"analytic","action":"query"},
  "supplier_commitment_plan": {"originalName":"supplier_commitment_plan","canonicalName":"purchasing_commitment_plan","domain":"purchasing","resource":"commitment","action":"plan"},
  "supplier_commitment_apply": {"originalName":"supplier_commitment_apply","canonicalName":"purchasing_commitment_apply","domain":"purchasing","resource":"commitment","action":"apply"},
  "supplier_commitment_list": {"originalName":"supplier_commitment_list","canonicalName":"purchasing_commitment_list","domain":"purchasing","resource":"commitment","action":"list"},
  "supplier_commitment_change": {"originalName":"supplier_commitment_change","canonicalName":"purchasing_commitment_change","domain":"purchasing","resource":"commitment","action":"change"},
  "supplier_commitment_match": {"originalName":"supplier_commitment_match","canonicalName":"purchasing_commitment_match","domain":"purchasing","resource":"commitment","action":"match"},
  "supplier_commitment_matches": {"originalName":"supplier_commitment_matches","canonicalName":"purchasing_supplier_commitment_match","domain":"purchasing","resource":"supplier_commitment","action":"match"},
  "supplier_commitment_alerts": {"originalName":"supplier_commitment_alerts","canonicalName":"purchasing_supplier_commitment_alert","domain":"purchasing","resource":"supplier_commitment","action":"alert"},
  "invoice_send_email": {"originalName":"invoice_send_email","canonicalName":"sales_invoice_email_send","domain":"sales","resource":"invoice_email","action":"send"},
  "import_archive_list": {"originalName":"import_archive_list","canonicalName":"system_import_archive_list","domain":"system","resource":"import_archive","action":"list"},
  "import_archive_year": {"originalName":"import_archive_year","canonicalName":"system_import_archive_year_read","domain":"system","resource":"import_archive_year","action":"read"},
  "tax_return_prepare": {"originalName":"tax_return_prepare","canonicalName":"tax_return_prepare","domain":"tax","resource":"return","action":"prepare"},
  "accrual_register": {"originalName":"accrual_register","canonicalName":"accounting_accrual_register","domain":"accounting","resource":"accrual","action":"register"},
  "accrual_recognize": {"originalName":"accrual_recognize","canonicalName":"accounting_accrual_recognize","domain":"accounting","resource":"accrual","action":"recognize"},
  "accrual_register_report": {"originalName":"accrual_register_report","canonicalName":"accrual_register_report","domain":"accrual","resource":"register","action":"report"},
  "budget_set": {"originalName":"budget_set","canonicalName":"planning_budget_set","domain":"planning","resource":"budget","action":"set"},
  "budget_list": {"originalName":"budget_list","canonicalName":"planning_budget_list","domain":"planning","resource":"budget","action":"list"},
  "budget_vs_actual": {"originalName":"budget_vs_actual","canonicalName":"planning_budget_actual_compare","domain":"planning","resource":"budget_actual","action":"compare"},
  "budget_forecast": {"originalName":"budget_forecast","canonicalName":"planning_budget_forecast","domain":"planning","resource":"budget","action":"forecast"},
  "liquidity_forecast_13_week": {"originalName":"liquidity_forecast_13_week","canonicalName":"planning_liquidity_forecast","domain":"planning","resource":"liquidity","action":"forecast"},
  "payable_register": {"originalName":"payable_register","canonicalName":"purchasing_payable_register","domain":"purchasing","resource":"payable","action":"register"},
  "payable_pay": {"originalName":"payable_pay","canonicalName":"purchasing_payable_pay","domain":"purchasing","resource":"payable","action":"pay"},
  "payable_list": {"originalName":"payable_list","canonicalName":"purchasing_payable_list","domain":"purchasing","resource":"payable","action":"list"},
  "company_profile_get": {"originalName":"company_profile_get","canonicalName":"workspace_company_profile_get","domain":"workspace","resource":"company_profile","action":"get"},
  "meta_about": {"originalName":"meta_about","canonicalName":"system_server_about","domain":"system","resource":"server","action":"about"},
  "posting_rule_propose": {"originalName":"posting_rule_propose","canonicalName":"accounting_rule_propose","domain":"accounting","resource":"rule","action":"propose"},
  "posting_rule_approve": {"originalName":"posting_rule_approve","canonicalName":"accounting_rule_approve","domain":"accounting","resource":"rule","action":"approve"},
  "posting_rule_explain": {"originalName":"posting_rule_explain","canonicalName":"accounting_rule_explain","domain":"accounting","resource":"rule","action":"explain"},
  "bookkeeping_batch_plan": {"originalName":"bookkeeping_batch_plan","canonicalName":"accounting_batch_plan","domain":"accounting","resource":"batch","action":"plan"},
  "bookkeeping_batch_persist": {"originalName":"bookkeeping_batch_persist","canonicalName":"bookkeeping_batch_persist","domain":"bookkeeping","resource":"batch","action":"persist"},
  "bookkeeping_batch_dry_run": {"originalName":"bookkeeping_batch_dry_run","canonicalName":"bookkeeping_batch_persist","domain":"bookkeeping","resource":"batch","action":"persist"},
  "bookkeeping_batch_approve": {"originalName":"bookkeeping_batch_approve","canonicalName":"accounting_batch_approve","domain":"accounting","resource":"batch","action":"approve"},
  "bookkeeping_batch_apply": {"originalName":"bookkeeping_batch_apply","canonicalName":"accounting_batch_apply","domain":"accounting","resource":"batch","action":"apply"},
  "bookkeeping_batch_status": {"originalName":"bookkeeping_batch_status","canonicalName":"accounting_batch_status","domain":"accounting","resource":"batch","action":"status"},
  "purchase_case_create": {"originalName":"purchase_case_create","canonicalName":"purchasing_case_create","domain":"purchasing","resource":"case","action":"create"},
  "purchase_case_review": {"originalName":"purchase_case_review","canonicalName":"purchasing_case_review","domain":"purchasing","resource":"case","action":"review"},
  "purchase_case_reassess": {"originalName":"purchase_case_reassess","canonicalName":"purchasing_case_reassess","domain":"purchasing","resource":"case","action":"reassess"},
  "purchase_case_get": {"originalName":"purchase_case_get","canonicalName":"purchasing_case_get","domain":"purchasing","resource":"case","action":"get"},
  "purchase_case_list": {"originalName":"purchase_case_list","canonicalName":"purchasing_case_list","domain":"purchasing","resource":"case","action":"list"},
  "purchase_overview": {"originalName":"purchase_overview","canonicalName":"purchasing_purchase_overview","domain":"purchasing","resource":"purchase","action":"overview"},
  "purchase_case_group_review": {"originalName":"purchase_case_group_review","canonicalName":"purchasing_case_group_review","domain":"purchasing","resource":"case_group","action":"review"},
  "bookkeeping_workbench": {"originalName":"bookkeeping_workbench","canonicalName":"accounting_bookkeeping_inspect","domain":"accounting","resource":"bookkeeping","action":"inspect"},
  "vendor_identity_enrichment_plan": {"originalName":"vendor_identity_enrichment_plan","canonicalName":"purchasing_identity_enrichment_plan","domain":"purchasing","resource":"identity_enrichment","action":"plan"},
  "vendor_identity_enrichment_list": {"originalName":"vendor_identity_enrichment_list","canonicalName":"purchasing_identity_enrichment_list","domain":"purchasing","resource":"identity_enrichment","action":"list"},
  "vendor_identity_enrichment_apply": {"originalName":"vendor_identity_enrichment_apply","canonicalName":"purchasing_identity_enrichment_apply","domain":"purchasing","resource":"identity_enrichment","action":"apply"},
  "legacy_party_mapping_plan": {"originalName":"legacy_party_mapping_plan","canonicalName":"workspace_party_mapping_plan","domain":"workspace","resource":"party_mapping","action":"plan"},
  "legacy_party_mapping_list": {"originalName":"legacy_party_mapping_list","canonicalName":"workspace_party_mapping_list","domain":"workspace","resource":"party_mapping","action":"list"},
  "legacy_party_mapping_apply": {"originalName":"legacy_party_mapping_apply","canonicalName":"workspace_party_mapping_apply","domain":"workspace","resource":"party_mapping","action":"apply"},
  "legacy_party_mapping_supersede": {"originalName":"legacy_party_mapping_supersede","canonicalName":"workspace_party_mapping_supersede","domain":"workspace","resource":"party_mapping","action":"supersede"},
  "accounting_approval_policy_get": {"originalName":"accounting_approval_policy_get","canonicalName":"accounting_approval_policy_get","domain":"accounting","resource":"approval_policy","action":"get"},
  "accounting_approval_policy_set": {"originalName":"accounting_approval_policy_set","canonicalName":"accounting_approval_policy_set","domain":"accounting","resource":"approval_policy","action":"set"},
  "workspace_party_search": {"originalName":"workspace_party_search","canonicalName":"workspace_party_search","domain":"workspace","resource":"party","action":"search"},
  "workspace_party_inspect": {"originalName":"workspace_party_inspect","canonicalName":"workspace_party_inspect","domain":"workspace","resource":"party","action":"inspect"},
  "workspace_party_create": {"originalName":"workspace_party_create","canonicalName":"workspace_party_create","domain":"workspace","resource":"party","action":"create"},
  "workspace_party_link_role": {"originalName":"workspace_party_link_role","canonicalName":"workspace_party_role_link","domain":"workspace","resource":"party_role","action":"link"},
  "workspace_party_propose_merge": {"originalName":"workspace_party_propose_merge","canonicalName":"workspace_party_merge_propose","domain":"workspace","resource":"party_merge","action":"propose"},
  "workspace_party_approve_merge": {"originalName":"workspace_party_approve_merge","canonicalName":"workspace_party_merge_approve","domain":"workspace","resource":"party_merge","action":"approve"},
  "corporate_record_list": {"originalName":"corporate_record_list","canonicalName":"workspace_record_list","domain":"workspace","resource":"record","action":"list"},
  "corporate_record_inspect": {"originalName":"corporate_record_inspect","canonicalName":"workspace_record_inspect","domain":"workspace","resource":"record","action":"inspect"},
  "corporate_record_download": {"originalName":"corporate_record_download","canonicalName":"workspace_record_download","domain":"workspace","resource":"record","action":"download"},
  "corporate_record_ingest": {"originalName":"corporate_record_ingest","canonicalName":"workspace_corporate_record_ingest","domain":"workspace","resource":"corporate_record","action":"ingest"},
  "corporate_record_link": {"originalName":"corporate_record_link","canonicalName":"workspace_record_link","domain":"workspace","resource":"record","action":"link"},
  "corporate_record_enrich": {"originalName":"corporate_record_enrich","canonicalName":"workspace_record_enrich","domain":"workspace","resource":"record","action":"enrich"},
  "corporate_record_supersede": {"originalName":"corporate_record_supersede","canonicalName":"workspace_record_supersede","domain":"workspace","resource":"record","action":"supersede"},
  "company_knowledge_context": {"originalName":"company_knowledge_context","canonicalName":"workspace_company_knowledge_set","domain":"workspace","resource":"company_knowledge","action":"set"},
  "company_knowledge_propose": {"originalName":"company_knowledge_propose","canonicalName":"workspace_knowledge_propose","domain":"workspace","resource":"knowledge","action":"propose"},
  "company_knowledge_review": {"originalName":"company_knowledge_review","canonicalName":"workspace_knowledge_review","domain":"workspace","resource":"knowledge","action":"review"},
  "company_knowledge_supersede": {"originalName":"company_knowledge_supersede","canonicalName":"workspace_knowledge_supersede","domain":"workspace","resource":"knowledge","action":"supersede"},
  "ownership_graph_query": {"originalName":"ownership_graph_query","canonicalName":"ownership_graph_query","domain":"ownership","resource":"graph","action":"query"},
  "ownership_snapshot_history": {"originalName":"ownership_snapshot_history","canonicalName":"ownership_snapshot_history","domain":"ownership","resource":"snapshot","action":"history"},
  "ownership_snapshot_propose": {"originalName":"ownership_snapshot_propose","canonicalName":"ownership_snapshot_propose","domain":"ownership","resource":"snapshot","action":"propose"},
  "ownership_snapshot_review": {"originalName":"ownership_snapshot_review","canonicalName":"ownership_snapshot_review","domain":"ownership","resource":"snapshot","action":"review"},
  "ownership_snapshot_apply": {"originalName":"ownership_snapshot_apply","canonicalName":"ownership_snapshot_apply","domain":"ownership","resource":"snapshot","action":"apply"},
  "intercompany_disposition_plan": {"originalName":"intercompany_disposition_plan","canonicalName":"ownership_disposition_plan","domain":"ownership","resource":"disposition","action":"plan"},
  "intercompany_disposition_propose": {"originalName":"intercompany_disposition_propose","canonicalName":"ownership_disposition_propose","domain":"ownership","resource":"disposition","action":"propose"},
  "intercompany_disposition_approve": {"originalName":"intercompany_disposition_approve","canonicalName":"ownership_disposition_approve","domain":"ownership","resource":"disposition","action":"approve"},
  "intercompany_disposition_link": {"originalName":"intercompany_disposition_link","canonicalName":"ownership_disposition_link","domain":"ownership","resource":"disposition","action":"link"},
  "intercompany_disposition_status": {"originalName":"intercompany_disposition_status","canonicalName":"ownership_disposition_status","domain":"ownership","resource":"disposition","action":"status"},
  "intercompany_disposition_settle": {"originalName":"intercompany_disposition_settle","canonicalName":"ownership_disposition_settle","domain":"ownership","resource":"disposition","action":"settle"},
  "intercompany_disposition_reopen": {"originalName":"intercompany_disposition_reopen","canonicalName":"ownership_disposition_reopen","domain":"ownership","resource":"disposition","action":"reopen"},
  "intercompany_disposition_supersede": {"originalName":"intercompany_disposition_supersede","canonicalName":"ownership_disposition_supersede","domain":"ownership","resource":"disposition","action":"supersede"},
  "workspace_inbox_list": {"originalName":"workspace_inbox_list","canonicalName":"workspace_inbox_list","domain":"workspace","resource":"inbox","action":"list"},
  "workspace_inbox_inspect": {"originalName":"workspace_inbox_inspect","canonicalName":"workspace_inbox_inspect","domain":"workspace","resource":"inbox","action":"inspect"},
  "workspace_inbox_status": {"originalName":"workspace_inbox_status","canonicalName":"workspace_inbox_status","domain":"workspace","resource":"inbox","action":"status"},
  "workspace_inbox_ingest": {"originalName":"workspace_inbox_ingest","canonicalName":"workspace_inbox_ingest","domain":"workspace","resource":"inbox","action":"ingest"},
  "workspace_inbox_assign": {"originalName":"workspace_inbox_assign","canonicalName":"workspace_inbox_assign","domain":"workspace","resource":"inbox","action":"assign"},
  "workspace_inbox_complete": {"originalName":"workspace_inbox_complete","canonicalName":"workspace_inbox_complete","domain":"workspace","resource":"inbox","action":"complete"},
  "agent_capability_search": {"originalName":"agent_capability_search","canonicalName":"agent_capability_search","domain":"agent","resource":"capability","action":"search"},
  "agent_workflow_describe": {"originalName":"agent_workflow_describe","canonicalName":"agent_workflow_describe","domain":"agent","resource":"workflow","action":"describe"},
});

export const MCP_OPERATION_NAMING_ENTRIES: readonly McpOperationNaming[] = Object.freeze(Object.values(MCP_OPERATION_NAMING));

export const CONTROLLED_MCP_ACTIONS: ReadonlySet<string> = Object.freeze(new Set<string>(
[
  "about",
  "add",
  "alert",
  "apply",
  "approve",
  "archive",
  "assign",
  "authorize",
  "book",
  "calculate",
  "change",
  "claim",
  "classify",
  "close",
  "compare",
  "complete",
  "configure",
  "confirm",
  "correct",
  "create",
  "depreciate",
  "describe",
  "discover",
  "download",
  "enrich",
  "execute",
  "explain",
  "export",
  "extract",
  "file",
  "find",
  "forecast",
  "generate",
  "get",
  "governance",
  "healthcheck",
  "history",
  "import",
  "ingest",
  "inspect",
  "issue",
  "link",
  "list",
  "lock",
  "lookup",
  "match",
  "onboard",
  "overdue",
  "overview",
  "parse",
  "pay",
  "persist",
  "place",
  "plan",
  "poll",
  "post",
  "preflight",
  "prepare",
  "preview",
  "propose",
  "query",
  "read",
  "readiness",
  "reassess",
  "receive",
  "recognize",
  "reconcile",
  "record",
  "refund",
  "register",
  "remind",
  "remove",
  "render",
  "reopen",
  "replace",
  "report",
  "resolve",
  "restore",
  "reverse",
  "review",
  "run",
  "search",
  "send",
  "set",
  "settle",
  "status",
  "submit",
  "suggest",
  "supersede",
  "sync",
  "update",
  "validate",
  "verify",
  "writeoff"
]
));
