import { canonicalJson } from "./canonical-json";
/**
 * Workspace-only evidence lifecycle for a two-sided intercompany disposition.
 * It deliberately opens legal ledgers read-only: normal company booking remains
 * the only way to create or reverse a journal.
 */
import type { Database } from "bun:sqlite";
import { createHash, randomUUID } from "node:crypto";
import { companyPaths } from "./paths";
import { companyRootForSlug } from "./workspace";
import { inspectCorporateRecord } from "./corporate-records";
import { inspectParty } from "./party-registry";
import { insertWorkspaceAudit } from "./workspace-control";
import { openCurrentLedgerReadOnly } from "./ledger-inspection";

const sha=(value:string)=>createHash("sha256").update(value).digest("hex");
const canonical = canonicalJson;
const text=(value:unknown,name:string,max=160)=>{const result=typeof value==="string"?value.trim().normalize("NFC"):"";if(!result||result.length>max)throw new Error(`${name} is required and bounded`);return result;};
const date=(value:unknown,name:string)=>{const result=text(value,name,10);if(!/^\d{4}-\d\d-\d\d$/.test(result)||Number.isNaN(Date.parse(`${result}T00:00:00Z`)))throw new Error(`${name} must be YYYY-MM-DD`);return result;};
const amount=(value:unknown,name:string)=>{if(typeof value!=="number"||!Number.isFinite(value)||value<=0||Math.round(value*100)!==value*100)throw new Error(`${name} must be a positive two-decimal amount`);return value;};
export type DispositionPrincipal={kind:"user"|"service";id:string};
export type DispositionSide="left"|"right";
export type IntercompanyDisposition={dispositionId:string;type:"invoice"|"reimbursement"|"loan"|"capital"|"dividend"|"repayment"|"other";economicDate:string;amount:number;currency:string;settlementDueDate?:string;partyIds:string[];evidenceRecordIds:string[];left:{companySlug:string;role:string;expectedSide:"receivable"|"payable"};right:{companySlug:string;role:string;expectedSide:"receivable"|"payable"}};

function parse(input:unknown):IntercompanyDisposition {const row=input&&typeof input==="object"&&!Array.isArray(input)?input as any:{};const side=(name:DispositionSide)=>{const item=row[name]??{};const companySlug=text(item.companySlug,`${name}.companySlug`,120);const expectedSide=text(item.expectedSide,`${name}.expectedSide`,20);if(expectedSide!=="receivable"&&expectedSide!=="payable")throw new Error(`${name}.expectedSide must be receivable or payable`);return {companySlug,role:text(item.role,`${name}.role`,80),expectedSide:expectedSide as "receivable"|"payable"};};const left=side("left"),right=side("right");if(left.companySlug===right.companySlug)throw new Error("disposition sides must reference distinct legal companies");if(left.expectedSide===right.expectedSide)throw new Error("disposition sides must be complementary");const type=text(row.type,"type",20);if(!["invoice","reimbursement","loan","capital","dividend","repayment","other"].includes(type))throw new Error("unsupported disposition type");const ids=(value:unknown,name:string)=>{if(!Array.isArray(value)||!value.length||value.length>64)throw new Error(`${name} requires 1 through 64 source-linked references`);const out=value.map((v,i)=>text(v,`${name}[${i}]`,160));if(new Set(out).size!==out.length)throw new Error(`${name} must be unique`);return out.sort();};return {dispositionId:row.dispositionId?text(row.dispositionId,"dispositionId",80):`icd-${randomUUID()}`,type:type as any,economicDate:date(row.economicDate,"economicDate"),amount:amount(row.amount,"amount"),currency:text(row.currency,"currency",3).toUpperCase(),...(row.settlementDueDate?{settlementDueDate:date(row.settlementDueDate,"settlementDueDate")}:{ }),partyIds:ids(row.partyIds,"partyIds"),evidenceRecordIds:ids(row.evidenceRecordIds,"evidenceRecordIds"),left,right};}
function event(db:Database,id:string,type:string,payload:unknown,actor:string,principal:DispositionPrincipal){const previous=db.query("SELECT event_hash FROM rm_intercompany_disposition_events ORDER BY id DESC LIMIT 1").get() as any;const body=canonical(payload),digest=sha(body),at=new Date().toISOString(),hash=sha(canonical({previousHash:previous?.event_hash??null,dispositionId:id,type,payloadHash:digest,actor,principal,at}));db.query("INSERT INTO rm_intercompany_disposition_events(disposition_id,event_type,payload_hash,canonical_payload,actor,principal_kind,principal_id,previous_hash,event_hash,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").run(id,type,digest,body,text(actor,"actor",160),principal.kind,text(principal.id,"principal id",160),previous?.event_hash??null,hash,at);insertWorkspaceAudit(db,{createdBy:actor,createdByProgram:"rentemester",eventType:`intercompany_disposition_${type}`,entityType:"intercompany_disposition",entityId:id});return {payloadHash:digest,eventHash:hash};}
/** Later lifecycle facts have their own append-only stream so the v27 event
 * grammar remains immutable.  They are still bound to the original payload
 * and audit identity; this is evidence, never a cross-company ledger write. */
function lifecycle(db:Database,id:string,type:"settled"|"superseded"|"reopened"|"exception"|"exception_resolved",payload:unknown,actor:string,principal:DispositionPrincipal){const previous=db.query("SELECT event_hash FROM rm_intercompany_disposition_lifecycle_events ORDER BY id DESC LIMIT 1").get() as any;const body=canonical(payload),digest=sha(body),at=new Date().toISOString(),hash=sha(canonical({previousHash:previous?.event_hash??null,dispositionId:id,type,payloadHash:digest,actor,principal,at}));db.query("INSERT INTO rm_intercompany_disposition_lifecycle_events(disposition_id,event_type,payload_hash,canonical_payload,actor,principal_kind,principal_id,previous_hash,event_hash,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").run(id,type,digest,body,text(actor,"actor",160),principal.kind,text(principal.id,"principal id",160),previous?.event_hash??null,hash,at);insertWorkspaceAudit(db,{createdBy:actor,createdByProgram:"rentemester",eventType:`intercompany_disposition_${type}`,entityType:"intercompany_disposition",entityId:id});return {payloadHash:digest,eventHash:hash};}
function requireRecordAndParties(db:Database,row:IntercompanyDisposition){for(const id of row.partyIds)if(!inspectParty(db,id))throw new Error("disposition party does not exist");for(const id of row.evidenceRecordIds)if(!inspectCorporateRecord(db,id))throw new Error("disposition corporate evidence does not exist");}
function snapshot(workspace:string,companySlug:string,journalEntryId:number){const db=openCurrentLedgerReadOnly(companyPaths(companyRootForSlug(workspace,companySlug)).db);try{const company=db.query("SELECT currency FROM companies WHERE id=1").get() as any;const entry=db.query("SELECT id,entry_no,transaction_date,entry_hash,status,reversal_of_entry_id FROM journal_entries WHERE id=?").get(journalEntryId)as any;if(!company||!entry||entry.status!=="posted"||entry.reversal_of_entry_id!=null)throw new Error("journal must be an active posted journal entry");const reversed=db.query("SELECT 1 FROM journal_entries WHERE reversal_of_entry_id=? LIMIT 1").get(journalEntryId);if(reversed)throw new Error("journal entry has been reversed");const lines=db.query("SELECT debit_amount,credit_amount FROM journal_lines WHERE journal_entry_id=?").all(journalEntryId)as any[];const head=db.query("SELECT entry_hash FROM journal_entries ORDER BY id DESC LIMIT 1").get()as any;return {currency:String(company.currency).toUpperCase(),entry,lines,ledgerHeadHash:head?.entry_hash??null};}finally{db.close();}}
function state(db:Database,id:string){const row=db.query("SELECT canonical_payload,payload_hash FROM rm_intercompany_dispositions WHERE disposition_id=?").get(id)as any;if(!row)return null;const events=db.query("SELECT event_type,actor,principal_kind,principal_id,payload_hash,canonical_payload,created_at FROM rm_intercompany_disposition_events WHERE disposition_id=? ORDER BY id").all(id)as any[];const lifecycleEvents=db.query("SELECT event_type,actor,principal_kind,principal_id,payload_hash,canonical_payload,created_at FROM rm_intercompany_disposition_lifecycle_events WHERE disposition_id=? ORDER BY id").all(id)as any[];const links=db.query("SELECT side,company_slug,journal_entry_id,journal_entry_no,journal_entry_hash,ledger_head_hash,linked_at,actor,principal_kind,principal_id FROM rm_intercompany_disposition_journal_links WHERE disposition_id=? ORDER BY side").all(id)as any[];let status=events.some(event=>event.event_type==="approved")?"approved":"proposed";for(const item of lifecycleEvents){if(item.event_type==="settled"||item.event_type==="superseded")status=item.event_type;if(item.event_type==="reopened")status="approved";}if(status==="approved"){if(links.length===1)status="partly_posted";if(links.length===2)status="posted";}return {disposition:JSON.parse(row.canonical_payload),payloadHash:row.payload_hash,status,events,lifecycleEvents,links};}
export function proposeIntercompanyDisposition(db:Database,input:unknown,audit:{actor:string;principal:DispositionPrincipal}){const value=parse(input);requireRecordAndParties(db,value);return db.transaction(()=>{const exists=state(db,value.dispositionId);const payload=canonical(value);if(exists){if(exists.payloadHash===sha(payload)&&exists.status==="proposed")return exists;throw new Error("disposition id already exists with a different or completed lifecycle");}db.query("INSERT INTO rm_intercompany_dispositions(disposition_id,canonical_payload,payload_hash,created_at) VALUES(?,?,?,?)").run(value.dispositionId,payload,sha(payload),new Date().toISOString());event(db,value.dispositionId,"proposed",value,audit.actor,audit.principal);return state(db,value.dispositionId)!;}).immediate();}
export function approveIntercompanyDisposition(db:Database,id:string,payloadHash:string,audit:{actor:string;principal:DispositionPrincipal}){return db.transaction(()=>{const current=state(db,text(id,"disposition id",80));if(!current||current.payloadHash!==payloadHash)throw new Error("exact proposed disposition was not found");if(current.status==="approved"||current.status==="partly_posted"||current.status==="posted")return current;if(current.status!=="proposed")throw new Error("exact proposed disposition was not found");const proposer=current.events[0];if(proposer.principal_kind===audit.principal.kind&&proposer.principal_id===audit.principal.id)throw new Error("disposition approval requires a distinct stable principal");event(db,id,"approved",{payloadHash},audit.actor,audit.principal);return state(db,id)!;}).immediate();}
function assertCurrentLinks(workspace:string,current:NonNullable<ReturnType<typeof state>>){for(const link of current.links){const actual=snapshot(workspace,link.company_slug,link.journal_entry_id);if(actual.entry.entry_hash!==link.journal_entry_hash)throw new Error("linked journal entry changed; disposition requires review");if(actual.ledgerHeadHash!==link.ledger_head_hash)throw new Error("linked ledger head changed; refresh and review before state change");}}
function assertLinkMatches(current:NonNullable<ReturnType<typeof state>>,side:DispositionSide,actual:ReturnType<typeof snapshot>){const expected=current.disposition[side];if(actual.currency!==current.disposition.currency)throw new Error("journal company currency does not match disposition currency");if(actual.entry.transaction_date!==current.disposition.economicDate)throw new Error("journal date does not match disposition economic date");const expectedAmount=Math.round(current.disposition.amount*100);const matched=actual.lines.some((line:any)=>Math.round(Number(expected.expectedSide==="receivable"?line.debit_amount:line.credit_amount)*100)===expectedAmount);if(!matched)throw new Error("journal does not contain the expected amount on the expected disposition side");}
export function planIntercompanyDisposition(db:Database,input:unknown){const disposition=parse(input);requireRecordAndParties(db,disposition);return {ok:true,mode:"dry-run" as const,disposition,payloadHash:sha(canonical(disposition)),ledgerEffects:[],proposedSides:["left","right"],warnings:["Each legal company must post separately through its normal policy, document, VAT and period controls."]};}
export function linkIntercompanyDispositionJournal(db:Database,workspace:string,input:{dispositionId:string;payloadHash:string;side:DispositionSide;journalEntryId:number;expectedLedgerHeadHash:string|null;actor:string;principal:DispositionPrincipal}){return db.transaction(()=>{const current=state(db,text(input.dispositionId,"disposition id",80));if(!current||current.status!=="approved"&&current.status!=="partly_posted")throw new Error("only approved dispositions can link journals");if(current.payloadHash!==input.payloadHash)throw new Error("exact disposition hash is required");if(current.links.some((link:any)=>link.side===input.side)){const old=current.links.find((link:any)=>link.side===input.side)!;if(old.journal_entry_id===input.journalEntryId){assertCurrentLinks(workspace,current);return current;}throw new Error("disposition side already has an immutable journal link");}assertCurrentLinks(workspace,current);const expected=current.disposition[input.side];const actual=snapshot(workspace,expected.companySlug,input.journalEntryId);if(actual.ledgerHeadHash!==input.expectedLedgerHeadHash)throw new Error("ledger head changed; refresh before linking");assertLinkMatches(current,input.side,actual);db.query("INSERT INTO rm_intercompany_disposition_journal_links(disposition_id,side,company_slug,journal_entry_id,journal_entry_no,journal_entry_hash,ledger_head_hash,linked_at,actor,principal_kind,principal_id) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(input.dispositionId,input.side,expected.companySlug,input.journalEntryId,actual.entry.entry_no,actual.entry.entry_hash,actual.ledgerHeadHash,new Date().toISOString(),text(input.actor,"actor",160),input.principal.kind,text(input.principal.id,"principal id",160));lifecycle(db,input.dispositionId,"exception",{kind:"one_sided_posting",side:input.side,payloadHash:input.payloadHash},input.actor,input.principal);if(current.links.length===1)lifecycle(db,input.dispositionId,"exception_resolved",{kind:"one_sided_posting",payloadHash:input.payloadHash},input.actor,input.principal);return state(db,input.dispositionId)!;}).immediate();}
export function settleIntercompanyDisposition(db:Database,workspace:string,input:{dispositionId:string;payloadHash:string;settlementEvidenceRecordIds:string[];actor:string;principal:DispositionPrincipal}){return db.transaction(()=>{const current=state(db,text(input.dispositionId,"disposition id",80));if(!current||current.payloadHash!==input.payloadHash)throw new Error("exact fully posted disposition is required before settlement");if(current.status==="settled")return current;if(current.status!=="posted")throw new Error("exact fully posted disposition is required before settlement");if(!Array.isArray(input.settlementEvidenceRecordIds)||input.settlementEvidenceRecordIds.length<1)throw new Error("settlement requires source-linked evidence");for(const id of input.settlementEvidenceRecordIds)if(!inspectCorporateRecord(db,text(id,"settlement evidence",160)))throw new Error("settlement corporate evidence does not exist");assertCurrentLinks(workspace,current);lifecycle(db,input.dispositionId,"settled",{payloadHash:input.payloadHash,settlementEvidenceRecordIds:[...new Set(input.settlementEvidenceRecordIds)].sort()},input.actor,input.principal);return state(db,input.dispositionId)!;}).immediate();}
export function supersedeIntercompanyDisposition(db:Database,input:{dispositionId:string;payloadHash:string;replacementDispositionId:string;reason:string;actor:string;principal:DispositionPrincipal}){return db.transaction(()=>{const current=state(db,text(input.dispositionId,"disposition id",80));if(!current||current.payloadHash!==input.payloadHash||["settled","superseded"].includes(current.status))throw new Error("active exact disposition is required for supersession");const replacement=text(input.replacementDispositionId,"replacement disposition id",80);if(replacement===input.dispositionId||!state(db,replacement))throw new Error("supersession requires a distinct existing replacement disposition");lifecycle(db,input.dispositionId,"superseded",{payloadHash:input.payloadHash,replacementDispositionId:replacement,reason:text(input.reason,"supersession reason",1000)},input.actor,input.principal);return state(db,input.dispositionId)!;}).immediate();}
export function reopenIntercompanyDisposition(db:Database,workspace:string,input:{dispositionId:string;payloadHash:string;reason:string;actor:string;principal:DispositionPrincipal}){return db.transaction(()=>{const current=state(db,text(input.dispositionId,"disposition id",80));if(!current||!["settled","superseded"].includes(current.status)||current.payloadHash!==input.payloadHash)throw new Error("only exact settled or superseded dispositions can be reopened");assertCurrentLinks(workspace,current);lifecycle(db,input.dispositionId,"reopened",{payloadHash:input.payloadHash,reason:text(input.reason,"reopen reason",1000)},input.actor,input.principal);return state(db,input.dispositionId)!;}).immediate();}
export function intercompanyDispositionStatus(db:Database,workspace:string,id:string,asOf=new Date().toISOString().slice(0,10)){const current=state(db,text(id,"disposition id",80));if(!current)return null;const exceptions:any[]=[];for(const link of current.links){try{const actual=snapshot(workspace,link.company_slug,link.journal_entry_id);if(actual.entry.entry_hash!==link.journal_entry_hash||actual.ledgerHeadHash!==link.ledger_head_hash)exceptions.push({kind:"stale_or_reversed_journal",side:link.side,waivable:false});else assertLinkMatches(current,link.side,actual);}catch(error){exceptions.push({kind:"stale_or_reversed_journal",side:link.side,waivable:false});}}
if(current.status==="partly_posted")exceptions.push({kind:"one_sided_posting",side:current.links[0]?.side,waivable:false});if(current.status!=="settled"&&current.disposition.settlementDueDate&&current.disposition.settlementDueDate<date(asOf,"asOf"))exceptions.push({kind:"overdue_settlement",dueDate:current.disposition.settlementDueDate,waivable:false});return {...current,exceptions,balanced:current.status==="posted"&&exceptions.length===0,scope:"intercompany-disposition-status" as const};}
export function inspectIntercompanyDisposition(db:Database,id:string){return state(db,id);}
