import { createHash, randomUUID } from "node:crypto";
import type { Database } from "bun:sqlite";
import { canonicalJson } from "./canonical-json";

export type KnowledgeScope = { kind:"workspace" } | { kind:"company"; companySlug:string };
export type KnowledgeProvenance = { kind:"user"|"party"|"corporate_record"|"company_knowledge"|"external_snapshot"; ref:string };
export type KnowledgeRelationType = "commercial_counterparty"|"operational_dependency"|"reference";
export type KnowledgeEndpoint = { kind:"page"|"party"|"company"; ref:string };
const slug=/^[a-z0-9][a-z0-9-]{0,119}$/; const id=/^[a-z][a-z0-9-]{2,79}$/; const sha=(value:unknown)=>createHash("sha256").update(canonicalJson(value)).digest("hex");
const clean=(value:unknown,name:string,max:number)=>{const text=typeof value==="string"?value.trim():"";if(!text||text.length>max)throw new Error(`${name} is required and bounded`);return text;};
const date=(value:unknown,name:string)=>{const result=clean(value,name,64);if(Number.isNaN(new Date(result).valueOf()))throw new Error(`${name} must be ISO date/time`);return new Date(result).toISOString();};
function scope(input:KnowledgeScope){if(input.kind==="workspace")return {kind:"workspace" as const,company:null};if(input.kind!=="company"||!slug.test(input.companySlug))throw new Error("company scope requires a valid slug");return {kind:"company" as const,company:input.companySlug};}
function provenance(input:KnowledgeProvenance){const ref=clean(input.ref,"provenance ref",512);if(!["user","party","corporate_record","company_knowledge","external_snapshot"].includes(input.kind))throw new Error("unsupported provenance kind");if(input.kind==="external_snapshot"&&!safeUrl(ref))throw new Error("external snapshot provenance must be an http(s) URL");return {kind:input.kind,ref};}
export function safeUrl(value:string):boolean { try { const url=new URL(value);return (url.protocol==="https:"||url.protocol==="http:")&&!url.username&&!url.password; } catch { return false; } }
export function renderKnowledgeMarkdown(markdown:string){
  if (/\b(?:javascript|data):/i.test(markdown)) throw new Error("unsafe external URL");
  const external=[...markdown.matchAll(/https?:\/\/[^\s)\]]+/g)].map(match=>match[0]); if(external.some(url=>!safeUrl(url)))throw new Error("unsafe external URL");
  const wikilinks=[...markdown.matchAll(/\[\[([a-z0-9][a-z0-9-]{0,119})\]\]/g)].map(match=>match[1]!);
  // The renderer exposes text and links only. It never returns trusted HTML,
  // evaluates a URL or performs network I/O.
  return { text:markdown.replace(/</g,"&lt;").replace(/>/g,"&gt;"), wikilinks:[...new Set(wikilinks)].sort(), externalLinks:[...new Set(external)].sort() };
}
export function createKnowledgePage(db:Database,input:{pageId?:string;scope:KnowledgeScope;slug:string;title:string;bodyMarkdown:string;provenance:KnowledgeProvenance;effectiveFrom:string;effectiveToExclusive?:string;actor:string;principal:string}){
  const pageId=input.pageId??`page-${randomUUID()}`, target=scope(input.scope), pageSlug=clean(input.slug,"slug",120);if(!id.test(pageId)||!slug.test(pageSlug))throw new Error("invalid page id or slug");if(typeof input.bodyMarkdown!=="string"||input.bodyMarkdown.length>20000)throw new Error("body markdown is bounded");const title=clean(input.title,"title",240),body=input.bodyMarkdown;const rendered=renderKnowledgeMarkdown(body),source=provenance(input.provenance),from=date(input.effectiveFrom,"effectiveFrom"),to=input.effectiveToExclusive?date(input.effectiveToExclusive,"effectiveToExclusive"):null;if(to&&to<=from)throw new Error("effectiveToExclusive must be after effectiveFrom");const actor=clean(input.actor,"actor",160),principal=clean(input.principal,"principal",160),createdAt=new Date().toISOString();const eventHash=sha({pageId,version:1,target,pageSlug,title,body,source,from,to,actor,principal,createdAt});db.transaction(()=>{const exists=db.query("SELECT 1 FROM rm_current_knowledge_pages WHERE scope_kind=? AND company_slug IS ? AND slug=?").get(target.kind,target.company,pageSlug);if(exists)throw new Error("knowledge page slug already exists in scope");db.query("INSERT INTO rm_knowledge_page_events(page_id,version,event_type,scope_kind,company_slug,slug,title,body_markdown,provenance_kind,provenance_ref,effective_from,effective_to_exclusive,prior_event_hash,event_hash,actor,principal,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(pageId,1,"created",target.kind,target.company,pageSlug,title,body,source.kind,source.ref,from,to,null,eventHash,actor,principal,createdAt);}).immediate();return {pageId,version:1,scope:input.scope,slug:pageSlug,title,bodyMarkdown:body,rendered,provenance:source,effectiveFrom:from,effectiveToExclusive:to,eventHash};
}
export function listKnowledgePages(db:Database,input:{scope:KnowledgeScope}){const target=scope(input.scope);return (db.query("SELECT page_id,version,slug,title,body_markdown,provenance_kind,provenance_ref,effective_from,effective_to_exclusive,event_hash FROM rm_current_knowledge_pages WHERE scope_kind=? AND company_slug IS ? ORDER BY slug").all(target.kind,target.company)as any[]).map(row=>({pageId:row.page_id,version:row.version,slug:row.slug,title:row.title,rendered:renderKnowledgeMarkdown(row.body_markdown),provenance:{kind:row.provenance_kind,ref:row.provenance_ref},effectiveFrom:row.effective_from,effectiveToExclusive:row.effective_to_exclusive,eventHash:row.event_hash}));}
export const knowledgeMetricCatalogue={"knowledge-page-count":{scope:"workspace",params:[],limit:1},"knowledge-relation-count":{scope:"workspace",params:[],limit:1}} as const;
export function readKnowledgeMetric(db:Database,id:keyof typeof knowledgeMetricCatalogue){if(id==="knowledge-page-count")return {id,value:Number((db.query("SELECT COUNT(*) count FROM rm_current_knowledge_pages").get()as{count:number}).count),drilldown:"knowledge pages"};return {id,value:Number((db.query("SELECT COUNT(*) count FROM rm_current_knowledge_relations").get()as{count:number}).count),drilldown:"knowledge relations"};}
