/** Reviewed, source-byte-bound completion of legacy vendor identity typing. */
import { createHash } from "node:crypto";
import type { Database } from "bun:sqlite";
import { canonicalJson } from "./canonical-json";
import { DocumentEvidenceError, snapshotRegisteredDocument } from "./document-storage";
import { resolveSupplierIdentity, type SupplierIdentifierKind } from "./supplier-identity";

export const VENDOR_IDENTITY_ENRICHMENT_ERRORS={VENDOR_NOT_FOUND:"VENDOR_NOT_FOUND",EVIDENCE_NOT_FOUND:"EVIDENCE_NOT_FOUND",EVIDENCE_INVALID:"EVIDENCE_INVALID",IDENTITY_INVALID:"IDENTITY_INVALID",IDENTITY_CONFLICT:"IDENTITY_CONFLICT",IDENTIFIER_INVENTION:"IDENTIFIER_INVENTION",NAME_OR_ADDRESS_MISMATCH:"NAME_OR_ADDRESS_MISMATCH",PLAN_HASH_MISMATCH:"PLAN_HASH_MISMATCH",CONFIRMATION_REQUIRED:"CONFIRMATION_REQUIRED",ACTOR_REQUIRED:"ACTOR_REQUIRED",PRINCIPAL_REQUIRED:"PRINCIPAL_REQUIRED",IDEMPOTENCY_KEY_REQUIRED:"IDEMPOTENCY_KEY_REQUIRED",IDEMPOTENCY_CONFLICT:"IDEMPOTENCY_CONFLICT"} as const;
type Code=typeof VENDOR_IDENTITY_ENRICHMENT_ERRORS[keyof typeof VENDOR_IDENTITY_ENRICHMENT_ERRORS]; const fail=(e:Code)=>({ok:false as const,errors:[e]});
const text=(v:unknown,max=500)=>typeof v==="string"&&v.trim().length>0&&v.trim().length<=max?v.trim():null;
const norm=(v:unknown)=>typeof v==="string"?v.trim().replace(/\s+/g," ").toLocaleLowerCase("en-US"):"";
const ident=(v:unknown)=>typeof v==="string"?v.replace(/[^a-z0-9]/gi,"").toUpperCase():"";
const hash=(v:unknown)=>createHash("sha256").update(canonicalJson(v)).digest("hex"); const key=(v:string)=>createHash("sha256").update(v).digest("hex");
export type VendorIdentityEnrichmentInput={companySlug:string;vendorId:number;documentId:number;countryCode:string;identifierKind:SupplierIdentifierKind;identifier?:string;reviewedReference:string};
function vendor(db:Database,id:number){return db.query("SELECT id,name,address,vat_or_cvr,country_code,identifier_kind,identity_status,notes FROM vendors WHERE id=?").get(id) as any;}
function document(db:Database,id:number){return db.query("SELECT id,sha256_hash,document_type,sender_name,sender_address,sender_vat_cvr,supplier_country_code,supplier_identifier_kind,supplier_identity_status FROM documents WHERE id=?").get(id) as any;}
function planInner(db:Database,companyRoot:string,input:VendorIdentityEnrichmentInput){const v=vendor(db,input.vendorId),d=document(db,input.documentId),reference=text(input.reviewedReference);if(!v)return fail(VENDOR_IDENTITY_ENRICHMENT_ERRORS.VENDOR_NOT_FOUND);if(!d||!reference)return fail(VENDOR_IDENTITY_ENRICHMENT_ERRORS.EVIDENCE_NOT_FOUND);let source;try{source=snapshotRegisteredDocument(db,companyRoot,input.documentId);}catch(e){return fail(e instanceof DocumentEvidenceError?VENDOR_IDENTITY_ENRICHMENT_ERRORS.EVIDENCE_INVALID:VENDOR_IDENTITY_ENRICHMENT_ERRORS.EVIDENCE_NOT_FOUND);} const supplied=input.identifier?.trim()??"";const existing=String(v.vat_or_cvr??"").trim();if(!existing&&supplied)return fail(VENDOR_IDENTITY_ENRICHMENT_ERRORS.IDENTIFIER_INVENTION);if(existing&&supplied&&ident(existing)!==ident(supplied))return fail(VENDOR_IDENTITY_ENRICHMENT_ERRORS.IDENTITY_CONFLICT);const resolved=resolveSupplierIdentity({country:input.countryCode,identifier:existing||undefined,identifierKind:input.identifierKind});if(!resolved.ok)return fail(VENDOR_IDENTITY_ENRICHMENT_ERRORS.IDENTITY_INVALID);if(v.identity_status==="resolved"&&(v.country_code!==resolved.country||v.identifier_kind!==resolved.identifierKind))return fail(VENDOR_IDENTITY_ENRICHMENT_ERRORS.IDENTITY_CONFLICT);if(norm(v.name)!==norm(d.sender_name)||!norm(v.address)||norm(v.address)!==norm(d.sender_address))return fail(VENDOR_IDENTITY_ENRICHMENT_ERRORS.NAME_OR_ADDRESS_MISMATCH);if(d.sha256_hash!==source.sha256)return fail(VENDOR_IDENTITY_ENRICHMENT_ERRORS.EVIDENCE_INVALID);const payload={companySlug:input.companySlug,vendorSnapshot:v,documentSnapshot:{id:d.id,sha256:d.sha256_hash,supplierCountryCode:d.supplier_country_code,supplierIdentifierKind:d.supplier_identifier_kind,supplierIdentityStatus:d.supplier_identity_status,senderName:d.sender_name,senderAddress:d.sender_address,senderVatOrCvr:d.sender_vat_cvr},documentBytesSha256:source.sha256,proposedIdentity:{countryCode:resolved.country,identifierKind:resolved.identifierKind,identifier:resolved.identifier},reviewedReference:reference};return {ok:true as const,plan:{...payload,planHash:hash(payload)}};}
export function planVendorIdentityEnrichment(db:Database,companyRoot:string,input:VendorIdentityEnrichmentInput){return planInner(db,companyRoot,input);}
export function listVendorIdentityEnrichments(db:Database,input:{vendorId?:number}){return db.query("SELECT id,vendor_id,document_id,plan_hash,actor,principal,created_at FROM vendor_identity_enrichment_events WHERE (? IS NULL OR vendor_id=?) ORDER BY id").all(input.vendorId??null,input.vendorId??null) as any[];}
export function applyVendorIdentityEnrichment(db:Database,companyRoot:string,input:VendorIdentityEnrichmentInput&{planHash:string;idempotencyKey?:string;confirm:boolean;actor?:string;principal?:string}){if(!input.confirm)return fail(VENDOR_IDENTITY_ENRICHMENT_ERRORS.CONFIRMATION_REQUIRED);const actor=text(input.actor,160),principal=text(input.principal,160),idempotencyKey=text(input.idempotencyKey,128);if(!actor)return fail(VENDOR_IDENTITY_ENRICHMENT_ERRORS.ACTOR_REQUIRED);if(!principal)return fail(VENDOR_IDENTITY_ENRICHMENT_ERRORS.PRINCIPAL_REQUIRED);if(!idempotencyKey)return fail(VENDOR_IDENTITY_ENRICHMENT_ERRORS.IDEMPOTENCY_KEY_REQUIRED);const requestHash=hash({input:{...input,actor:undefined,principal:undefined,idempotencyKey:undefined,confirm:undefined}});return db.transaction(()=>{const old=db.query("SELECT id,plan_hash,request_hash FROM vendor_identity_enrichment_events WHERE principal=? AND idempotency_key_hash=?").get(principal,key(idempotencyKey)) as any;if(old){if(old.request_hash!==requestHash)return fail(VENDOR_IDENTITY_ENRICHMENT_ERRORS.IDEMPOTENCY_CONFLICT);return {ok:true as const,id:old.id,planHash:old.plan_hash,idempotent:true};}const planned=planInner(db,companyRoot,input);if(!planned.ok)return planned;if(input.planHash!==planned.plan.planHash)return fail(VENDOR_IDENTITY_ENRICHMENT_ERRORS.PLAN_HASH_MISMATCH);const v=vendor(db,input.vendorId);const p=planned.plan.proposedIdentity;if(v.country_code!==null||v.identifier_kind!==null||v.identity_status==="resolved")return fail(VENDOR_IDENTITY_ENRICHMENT_ERRORS.IDENTITY_CONFLICT);db.query("UPDATE vendors SET country_code=?,identifier_kind=?,identity_status='resolved' WHERE id=? AND country_code IS NULL AND identifier_kind IS NULL AND COALESCE(identity_status,'')!='resolved'").run(p.countryCode,p.identifierKind,input.vendorId);const row=db.query("INSERT INTO vendor_identity_enrichment_events(vendor_id,document_id,plan_hash,request_hash,idempotency_key_hash,actor,principal,payload_json,created_at) VALUES(?,?,?,?,?,?,?,?,?) RETURNING id").get(input.vendorId,input.documentId,input.planHash,requestHash,key(idempotencyKey),actor,principal,canonicalJson(planned.plan),new Date().toISOString()) as any;db.query("INSERT INTO audit_log(event_type,entity_type,entity_id,message,actor) VALUES(?,?,?,?,?)").run("vendor_identity_enriched","vendor",String(input.vendorId),`vendor identity enrichment ${input.planHash} principal:${principal}`,actor);return {ok:true as const,id:row.id,planHash:input.planHash,idempotent:false};}).immediate();}
