import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import babel from "@babel/core";
import plugin from "@stylexjs/babel-plugin";
import * as stylex from "@stylexjs/stylex";
import { designTokens } from "../src/design/tokens";
import { compileStylex } from "./stylex-precompile";
import { documentFonts } from "../src/design/document-fonts";

const root = resolve(import.meta.dir, "..");
const filename = "src/design/document.stylex.ts";
const source = readFileSync(resolve(root, filename), "utf8").replace(
  'import { designTokens as tokens } from "./tokens";',
  `const tokens = ${JSON.stringify(designTokens)};`,
);
const result = compileStylex(source, filename, {
  transformSync: babel.transformSync as Parameters<typeof compileStylex>[2]["transformSync"],
  stylexBabelPlugin: plugin,
  processStylexRules: plugin.processStylexRules as Parameters<typeof compileStylex>[2]["processStylexRules"],
  stylexRuntime: stylex,
});
const output = `// Generated by scripts/document-styles.ts from StyleX. Do not edit.\nexport const documentStyleSourceHash = ${JSON.stringify(result.sourceHash)};\nexport const documentCss = ${JSON.stringify(result.css)};\nexport const documentAttributes = ${JSON.stringify(result.attributes, null, 2)} as const;\n`;
const fonts = documentFonts.map(({ name, weight, file, subsetOf }) => ({
  name: subsetOf ?? name, weight,
  ...(subsetOf ? { unicodeRange: "U+0100-02FF,U+0300-036F,U+1D00-1DBF,U+1E00-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF" } : {}),
  data: readFileSync(resolve(root, "src/design/fonts", file)).toString("base64"),
}));
const fontOutput = `// Generated by scripts/document-styles.ts from locally packaged OFL fonts. Do not edit.\nexport const embeddedDocumentFonts = ${JSON.stringify(fonts)} as const;\n`;
for (const [file, expected] of [["document-styles.generated.ts", output], ["document-fonts.generated.ts", fontOutput]]) {
  const path = resolve(root, "src/design", file!);
  if (process.argv.includes("--check")) {
    if (readFileSync(path, "utf8") !== expected) throw new Error(`Document artifact ${file} is stale; run bun scripts/document-styles.ts`);
  } else writeFileSync(path, expected!);
}
