import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { applyImportedReceivableBankSettlement, applyLegacyImportedReceivableBackfill, getImportedReceivableBankSettlement, planImportedReceivableBankSettlement, planLegacyImportedReceivableBackfill } from "../../../core/imported-receivables";
import { currentMcpAuthenticatedPrincipal } from "../../security";
import { envelopeShape, wrapCoreResult } from "../../envelope";
import { confirmField, idempotencyKeyField, withCompanyDbConfirmed, withCompanyReadOnlyDb } from "../../tool-runtime";

const hash=z.string().regex(/^[a-fA-F0-9]{64}$/);
const event=z.object({id:z.string().min(1),eventKind:z.enum(["payment","credit_note"]).optional(),paymentDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),amount:z.number().positive(),paymentRef:z.string().min(1),documentHash:hash});
const schedule=z.object({contract:z.literal("rentemester-imported-receivables-v1"),sourceDocumentHash:hash,invoices:z.array(z.object({id:z.string().min(1),customerId:z.string().min(1).optional(),customerName:z.string().min(1).optional(),invoiceDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),dueDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),grossAmount:z.number().positive(),controlAccountNo:z.string().min(1),recognitionRef:z.string().min(1),documentHash:hash,payments:z.array(event).optional()})).min(1)});
const common={company:z.string().min(1),dineroImportAttemptId:z.number().int().positive(),sourceRawSha256:hash,canonicalInventorySha256:hash,controlDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),controlAccountNo:z.string().min(1),artifactSha256:hash,schedule};

export function registerInvoiceBackfillTools(server:McpServer):void{
  server.registerTool("invoice_imported_receivables_backfill_plan",{title:"Plan legacy Dinero receivable backfill",description:"Read-only. Binds one separately hash-verified schedule to the accepted Dinero source, explicit cut-over, debtors control balance, ledger head and audit head. It never replays the import.",inputSchema:common,outputSchema:envelopeShape,annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},withCompanyReadOnlyDb<any>(({db,args})=>wrapCoreResult(planLegacyImportedReceivableBackfill(db,args))));
  server.registerTool("invoice_imported_receivables_backfill_apply",{title:"Apply legacy Dinero receivable backfill",description:"Append-only apply of the exact reviewed plan. Requires an authenticated principal, actor, confirm:true and idempotencyKey. It never changes journals, documents, archive years, paths, import attempts or bank reconciliations.",inputSchema:{...common,planHash:hash,idempotencyKey:idempotencyKeyField,confirm:confirmField},outputSchema:envelopeShape,annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false}},withCompanyDbConfirmed<any>(server,"invoice_imported_receivables_backfill_apply",({db,actor,args})=>{const principal=currentMcpAuthenticatedPrincipal();return wrapCoreResult(applyLegacyImportedReceivableBackfill(db,{...args,actor:actor.createdBy,principal:principal?{kind:principal.kind,subjectId:principal.subjectId}:undefined,confirm:true}));}));
  const settlement={company:z.string().min(1),scheduleHash:hash,externalInvoiceId:z.string().min(1),bankTransactionId:z.number().int().positive(),bankAccountNo:z.string().min(1).optional()};
  server.registerTool("invoice_imported_receivable_settlement_plan",{title:"Plan imported receivable bank settlement",description:"Read-only. Hash-binds one imported receivable identity (scheduleHash + externalInvoiceId) to one immutable DKK bank receipt. It changes nothing.",inputSchema:settlement,outputSchema:envelopeShape,annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},withCompanyReadOnlyDb<any>(({db,args})=>wrapCoreResult(planImportedReceivableBankSettlement(db,args))));
  server.registerTool("invoice_imported_receivable_settlement_apply",{title:"Apply imported receivable bank settlement",description:"Posts and reconciles exactly the reviewed imported-receivable plan. Requires authenticated principal, actor, confirm:true and idempotencyKey; retry returns canonical outcome without another bank posting.",inputSchema:{...settlement,planHash:hash,idempotencyKey:idempotencyKeyField,confirm:confirmField},outputSchema:envelopeShape,annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false}},withCompanyDbConfirmed<any>(server,"invoice_imported_receivable_settlement_apply",({db,actor,args})=>{const principal=currentMcpAuthenticatedPrincipal();return wrapCoreResult(applyImportedReceivableBankSettlement(db,{...args,actor:actor.createdBy,principal:principal?{kind:principal.kind,subjectId:principal.subjectId}:undefined,confirm:true}));}));
  server.registerTool("invoice_imported_receivable_settlement_status",{title:"Read imported receivable settlement",description:"Read back the immutable settlement bound to one bank transaction.",inputSchema:{company:z.string().min(1),bankTransactionId:z.number().int().positive()},outputSchema:envelopeShape,annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},withCompanyReadOnlyDb<any>(({db,args})=>wrapCoreResult(getImportedReceivableBankSettlement(db,args.bankTransactionId))));
}
