import * as stylex from "@stylexjs/stylex";
import { designTokens as tokens } from "./tokens";

const bodyFont = `"${tokens.typography.bodyFamily}", -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif`;
const headlineFont = `"${tokens.typography.headlineFamily}", Georgia, "Times New Roman", serif`;
const monoFont = `"${tokens.typography.monoFamily}", "SF Mono", Menlo, Consolas, monospace`;

const s = stylex.create({
  faviconBackground: { fill: tokens.colors.ink },
  faviconText: { fill: tokens.colors.paper, fontSize: 18, textAnchor: "middle", fontFamily: "sans-serif" },
  base: { boxSizing: "border-box" },
  tableScroll: { maxWidth: "100%", overflowX: { default: "auto", "@media print": "visible" }, outline: { default: null, ":focus-visible": "2px solid" }, outlineColor: { default: null, ":focus-visible": tokens.colors.info } },
  body: { margin: 0, padding: 0, backgroundColor: { default: tokens.colors.paper, "@media print": "#fff" }, color: tokens.colors.ink, fontFamily: bodyFont, fontSize: tokens.typography.bodySize, lineHeight: 1.5 },
  page: { boxSizing: "border-box", maxWidth: 960, margin: "0 auto", padding: { default: "32px 24px", "@media print": 16 } },
  headline: { fontFamily: headlineFont, fontWeight: 600, letterSpacing: "-0.01em" },
  h1: { margin: "0 0 8px", fontFamily: headlineFont, fontWeight: 600, fontSize: 24 },
  h2: { fontFamily: headlineFont, fontSize: 18, fontWeight: 600, margin: "0 0 12px", borderBottom: "1px solid " + tokens.colors.inkMuted, paddingBottom: 8 },
  mono: { overflowWrap: "anywhere", fontFamily: monoFont, fontVariantNumeric: "tabular-nums", fontFeatureSettings: '"tnum" 1' },
  amount: { textAlign: "right", whiteSpace: "nowrap" },
  amountLg: { fontSize: 28, lineHeight: 1.1, color: tokens.colors.ink },
  labelSm: { fontFamily: bodyFont, fontSize: 11, letterSpacing: "0.08em", textTransform: "uppercase", color: tokens.colors.inkMuted },
  header: { backgroundColor: tokens.colors.paperRaised, border: "1px solid " + tokens.colors.inkMuted, borderRadius: 4, padding: 24, display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 24 },
  meta: { color: tokens.colors.inkMuted, fontSize: 14 },
  metrics: { display: "grid", gridTemplateColumns: { default: "repeat(4, 1fr)", "@media (max-width: 640px)": "repeat(2, 1fr)" }, gap: 12, marginBottom: 24 },
  metricCard: { backgroundColor: tokens.colors.paperRaised, border: "1px solid " + tokens.colors.inkMuted, borderRadius: 4, padding: 16 },
  accentBorder: { borderColor: tokens.colors.accent },
  dangerBorder: { borderColor: tokens.colors.danger },
  secondary: { color: tokens.colors.inkMuted, fontSize: 13, marginTop: 4 },
  metricLabel: { marginTop: 12 },
  section: { marginBottom: 24 },
  deadline: { backgroundColor: tokens.colors.paperRaised, border: "1px solid " + tokens.colors.inkMuted, borderRadius: 4, padding: 16, display: "flex", justifyContent: "space-between", alignItems: "center", gap: 16 },
  deadlineTitle: { fontSize: 18 },
  deadlineDetail: { fontSize: 13, marginTop: 4 },
  right: { textAlign: "right" },
  table: { width: "100%", borderCollapse: "collapse", backgroundColor: tokens.colors.paper },
  cell: { padding: "8px 12px", textAlign: "left", borderBottom: "1px solid " + tokens.colors.inkMuted, fontSize: 14 },
  th: { color: tokens.colors.inkMuted, fontWeight: 500, fontSize: 11, letterSpacing: "0.08em", textTransform: "uppercase" },
  tr: { backgroundColor: { default: null, ":nth-child(even)": tokens.colors.paperRaised } },
  center: { textAlign: "center" },
  pill: { display: "inline-block", padding: "2px 8px", borderRadius: 2, fontSize: 12, fontWeight: 500, letterSpacing: "0.02em", color: tokens.colors.ink },
  success: { backgroundColor: tokens.colors.successSoft },
  warning: { backgroundColor: tokens.colors.warningSoft },
  danger: { backgroundColor: tokens.colors.dangerSoft },
  neutral: { backgroundColor: tokens.colors.paperRaised, border: "1px solid " + tokens.colors.inkMuted },
  statusRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "12px 0", borderBottom: { default: "1px solid " + tokens.colors.inkMuted, ":last-child": "none" } },
  label: { color: tokens.colors.ink, fontWeight: 500 },
  detail: { color: tokens.colors.inkMuted, fontSize: 13 },
  muted: { color: tokens.colors.inkMuted },
  empty: { color: tokens.colors.inkMuted, fontStyle: "italic", padding: "12px 0" },
  footer: { backgroundColor: tokens.colors.paperRaised, border: "1px solid " + tokens.colors.inkMuted, borderRadius: 4, padding: 16, color: tokens.colors.inkMuted, fontSize: 12, marginTop: 24 },
  row: { display: "flex", flexWrap: "wrap", justifyContent: "space-between", gap: 16 },
  provenance: { marginTop: 8, color: tokens.colors.inkMuted, fontSize: 11 },
  summary: { cursor: "pointer", letterSpacing: "0.04em" },
  activity: { display: "grid", gridTemplateColumns: { default: "auto auto auto minmax(0, 1fr)", "@media (max-width: 640px)": "1fr" }, overflowWrap: "anywhere", gap: "8px 16px", fontSize: 14 },
  time: { color: tokens.colors.ink, whiteSpace: "nowrap" },
  event: { color: tokens.colors.ink, fontWeight: 500 },
  overflow: { marginTop: 8, fontSize: 13 },
  payableSummary: { marginBottom: 12, fontSize: 13 },
  guideBody: { fontSize: 15, lineHeight: 1.55 },
  guideMain: { maxWidth: 880, padding: { default: "32px 24px 64px", "@media print": 16 } },
  backupMain: { maxWidth: 820 },
  guideH1: { fontSize: 30, margin: "0 0 4px" },
  guideH2: { fontSize: 21, margin: "32px 0 12px", borderBottom: "1px solid " + tokens.colors.border, paddingBottom: 6 },
  guideH3: { fontSize: 15, margin: "18px 0 6px" },
  sub: { color: tokens.colors.inkMuted, fontSize: 14, margin: "0 0 8px" },
  card: { backgroundColor: tokens.colors.paperRaised, border: "1px solid " + tokens.colors.border, borderRadius: 8, padding: "16px 20px", margin: "16px 0", breakInside: { default: null, "@media print": "avoid" } },
  ul: { paddingLeft: 20 },
  li: { margin: "4px 0", color: tokens.colors.inkMuted },
  code: { fontFamily: monoFont, fontSize: 13, backgroundColor: "#EFEAE0", padding: "1px 5px", borderRadius: 3, color: tokens.colors.ink },
  guideTable: { margin: "8px 0", fontSize: 13 },
  guideCell: { textAlign: "left", padding: "6px 8px", borderBottom: "1px solid " + tokens.colors.border, verticalAlign: "top" },
  guideTh: { color: tokens.colors.ink, fontWeight: 600, fontSize: 12, textTransform: "uppercase", letterSpacing: "0.04em" },
  guidePill: { padding: "2px 10px", borderRadius: 999, fontSize: 13, fontWeight: 600 },
  ok: { color: tokens.colors.success },
  warn: { color: tokens.colors.warning },
  bad: { color: tokens.colors.danger },
  metric: { display: "flex", flexWrap: "wrap", gap: 8, justifyContent: "space-between", borderBottom: { default: "1px solid " + tokens.colors.border, ":last-child": "none" }, padding: "6px 0" },
  law: { color: tokens.colors.inkMuted, fontSize: 13, marginTop: 8, borderLeft: "3px solid " + tokens.colors.accent, padding: "4px 10px", backgroundColor: "#F8F2E9" },
  guideFooter: { marginTop: 40, color: tokens.colors.inkMuted, fontSize: 13, borderTop: "1px solid " + tokens.colors.border, paddingTop: 16 },
  lockReason: { color: tokens.colors.danger, marginTop: 12 },
  hidden: { display: "none" },
  pdfBody: { margin: 0, padding: 0, color: tokens.colors.ink, fontFamily: bodyFont, fontSize: 13, lineHeight: 1.4 },
  pdfHeader: { display: "flex", flexDirection: "row", justifyContent: "space-between", borderBottom: "1px solid " + tokens.colors.border, paddingBottom: 16, marginBottom: 24, breakInside: "avoid" },
  pdfHeaderTitle: { fontFamily: headlineFont, fontSize: 28, fontWeight: 600, margin: 0 },
  pdfSubtitle: { color: tokens.colors.inkMuted, fontSize: 12, marginTop: 4 },
  pdfParties: { display: "flex", flexDirection: "row", gap: 24, marginBottom: 24, breakInside: "avoid" },
  pdfParty: { flexGrow: 1, flexBasis: 0 },
  pdfLabel: { fontSize: 11, fontWeight: 600, color: tokens.colors.inkMuted, marginBottom: 8 },
  pdfParagraph: { margin: "0 0 4px", whiteSpace: "pre-wrap" },
  pdfTable: { width: "100%", borderCollapse: "collapse", marginBottom: 16 },
  pdfCell: { padding: "8px 6px", borderBottom: "1px solid " + tokens.colors.border, fontSize: 12, verticalAlign: "top" },
  pdfTh: { backgroundColor: tokens.colors.paper, color: tokens.colors.inkMuted, fontWeight: 600, textAlign: "left" },
  pdfRow: { breakInside: "avoid" },
  pdfStripe: { backgroundColor: tokens.colors.paperRaised },
  pdfDescription: { width: "46%", overflowWrap: "anywhere" },
  pdfNumber: { textAlign: "right", fontFamily: monoFont, whiteSpace: "nowrap" },
  pdfTotals: { marginLeft: "auto", width: "60%", breakInside: "avoid", marginBottom: 24 },
  pdfTotal: { fontWeight: 600, backgroundColor: tokens.colors.paper },
  pdfSection: { breakInside: "avoid", marginTop: 16 },
  pdfFooter: { fontFamily: bodyFont, fontSize: 10, color: tokens.colors.inkMuted, textAlign: "center" },
  pdfSectionRow: { fontWeight: 600 },
});

export const attributes = {
  faviconBackground: stylex.attrs(s.faviconBackground),
  faviconText: stylex.attrs(s.faviconText),
  root: stylex.attrs(s.base),
  tableScroll: stylex.attrs(s.base, s.tableScroll),
  body: stylex.attrs(s.base, s.body),
  page: stylex.attrs(s.base, s.page),
  h1: stylex.attrs(s.base, s.h1),
  h2: stylex.attrs(s.base, s.h2),
  headline: stylex.attrs(s.base, s.headline),
  mono: stylex.attrs(s.base, s.mono),
  amount: stylex.attrs(s.base, s.mono, s.amount),
  amountLg: stylex.attrs(s.base, s.mono, s.amountLg),
  labelSm: stylex.attrs(s.base, s.labelSm),
  header: stylex.attrs(s.base, s.header),
  meta: stylex.attrs(s.base, s.meta),
  cvr: stylex.attrs(s.base, s.mono, s.meta),
  metrics: stylex.attrs(s.base, s.metrics),
  metricCard: stylex.attrs(s.base, s.metricCard),
  metricAccent: stylex.attrs(s.base, s.metricCard, s.accentBorder),
  metricDanger: stylex.attrs(s.base, s.metricCard, s.dangerBorder),
  secondary: stylex.attrs(s.base, s.secondary),
  metricLabel: stylex.attrs(s.base, s.labelSm, s.metricLabel),
  section: stylex.attrs(s.base, s.section),
  deadline: stylex.attrs(s.base, s.deadline),
  deadlineTitle: stylex.attrs(s.base, s.headline, s.deadlineTitle),
  deadlineDetail: stylex.attrs(s.base, s.muted, s.deadlineDetail),
  right: stylex.attrs(s.base, s.right),
  table: stylex.attrs(s.base, s.table),
  cell: stylex.attrs(s.base, s.cell),
  th: stylex.attrs(s.base, s.cell, s.th),
  tr: stylex.attrs(s.base, s.tr),
  cellMono: stylex.attrs(s.base, s.cell, s.mono),
  cellAmount: stylex.attrs(s.base, s.cell, s.mono, s.amount),
  cellCenter: stylex.attrs(s.base, s.cell, s.center),
  thAmount: stylex.attrs(s.base, s.cell, s.th, s.mono, s.amount),
  thCenter: stylex.attrs(s.base, s.cell, s.th, s.center),
  pillSuccess: stylex.attrs(s.base, s.pill, s.success),
  pillWarning: stylex.attrs(s.base, s.pill, s.warning),
  pillDanger: stylex.attrs(s.base, s.pill, s.danger),
  pillNeutral: stylex.attrs(s.base, s.pill, s.neutral),
  statusRow: stylex.attrs(s.base, s.statusRow),
  label: stylex.attrs(s.base, s.label),
  detail: stylex.attrs(s.base, s.detail),
  muted: stylex.attrs(s.base, s.muted),
  empty: stylex.attrs(s.base, s.empty),
  footer: stylex.attrs(s.base, s.footer),
  row: stylex.attrs(s.base, s.row),
  provenance: stylex.attrs(s.base, s.provenance),
  summary: stylex.attrs(s.base, s.summary),
  activity: stylex.attrs(s.base, s.activity),
  time: stylex.attrs(s.base, s.mono, s.time),
  event: stylex.attrs(s.base, s.event),
  overflow: stylex.attrs(s.base, s.muted, s.overflow),
  payableSummary: stylex.attrs(s.base, s.muted, s.payableSummary),
  guideBody: stylex.attrs(s.base, s.body, s.guideBody),
  guideMain: stylex.attrs(s.base, s.page, s.guideMain),
  backupMain: stylex.attrs(s.base, s.page, s.guideMain, s.backupMain),
  guideH1: stylex.attrs(s.base, s.h1, s.guideH1),
  guideH2: stylex.attrs(s.base, s.h2, s.guideH2),
  guideH3: stylex.attrs(s.base, s.guideH3),
  sub: stylex.attrs(s.base, s.sub),
  card: stylex.attrs(s.base, s.card),
  ul: stylex.attrs(s.base, s.ul),
  li: stylex.attrs(s.base, s.li),
  code: stylex.attrs(s.base, s.code),
  guideTable: stylex.attrs(s.base, s.table, s.guideTable),
  guideCell: stylex.attrs(s.base, s.guideCell),
  guideTh: stylex.attrs(s.base, s.guideCell, s.guideTh),
  pillOk: stylex.attrs(s.base, s.pill, s.guidePill, s.success, s.ok),
  pillWarn: stylex.attrs(s.base, s.pill, s.guidePill, s.warning, s.warn),
  pillBad: stylex.attrs(s.base, s.pill, s.guidePill, s.danger, s.bad),
  metric: stylex.attrs(s.base, s.metric),
  metricValue: stylex.attrs(s.base, s.mono),
  law: stylex.attrs(s.base, s.law),
  guideFooter: stylex.attrs(s.base, s.guideFooter),
  lockReason: stylex.attrs(s.base, s.lockReason),
  hidden: stylex.attrs(s.base, s.hidden),
  pdfBody: stylex.attrs(s.base, s.pdfBody),
  pdfHeader: stylex.attrs(s.base, s.pdfHeader),
  pdfHeaderTitle: stylex.attrs(s.base, s.pdfHeaderTitle),
  pdfSubtitle: stylex.attrs(s.base, s.pdfSubtitle),
  pdfParties: stylex.attrs(s.base, s.pdfParties),
  pdfParty: stylex.attrs(s.base, s.pdfParty),
  pdfLabel: stylex.attrs(s.base, s.pdfLabel),
  pdfParagraph: stylex.attrs(s.base, s.pdfParagraph),
  pdfTable: stylex.attrs(s.base, s.pdfTable),
  pdfCell: stylex.attrs(s.base, s.pdfCell),
  pdfTh: stylex.attrs(s.base, s.pdfCell, s.pdfTh),
  pdfThNumber: stylex.attrs(s.base, s.pdfCell, s.pdfTh, s.pdfNumber),
  pdfRow: stylex.attrs(s.base, s.pdfRow),
  pdfRowStripe: stylex.attrs(s.base, s.pdfRow, s.pdfStripe),
  pdfDescription: stylex.attrs(s.base, s.pdfCell, s.pdfDescription),
  pdfNumber: stylex.attrs(s.base, s.pdfCell, s.pdfNumber),
  pdfTotals: stylex.attrs(s.base, s.pdfTable, s.pdfTotals),
  pdfTotal: stylex.attrs(s.base, s.pdfCell, s.pdfNumber, s.pdfTotal),
  pdfTotalLabel: stylex.attrs(s.base, s.pdfCell, s.pdfTotal),
  pdfSection: stylex.attrs(s.base, s.pdfSection),
  pdfFooter: stylex.attrs(s.base, s.pdfFooter),
  pdfSectionCell: stylex.attrs(s.base, s.pdfCell, s.pdfSectionRow),
};
