import { afterEach, describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { initWorkspace } from "../../src/core/workspace";
import { openWorkspaceControlDb } from "../../src/core/workspace-control";
import { createParty, linkLegacyPartyReference, linkPartyRole } from "../../src/core/party-registry";
import { migrate, openDb } from "../../src/core/db";
import { companyPaths } from "../../src/core/paths";
import { applyDocumentPartyLink, decideInternalNoExternalParty, documentResolution, planDocumentPartyLink, supersedeDocumentPartyLink, supersedeInternalNoExternalParty } from "../../src/core/document-party-links";
const roots:string[]=[]; const setup=()=>{const root=mkdtempSync(join(tmpdir(),"rm-doc-party-"));roots.push(root);initWorkspace(root);const registry=openWorkspaceControlDb(root);const ledger=openDb(companyPaths(root).db);migrate(ledger);ledger.query("INSERT INTO documents(document_no,sha256_hash,payload_json,upload_datetime,source,status,supplier_country_code,supplier_identifier_kind,sender_vat_cvr) VALUES(?,?,?,?,?,?,?,?,?)").run("DOC-1","a".repeat(64),"{}","2026-01-01T00:00:00.000Z","test","posted","DK","dk_cvr","DK12345678");return {root,registry,ledger};}; afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
describe("#588 document party links",()=>{
 test("fails closed for name-only, scope mismatch and unreviewed legacy evidence",()=>{const {registry,ledger}=setup();const p=createParty(registry,{kind:"organization",name:"Synthetic",identifiers:[{country:"DK",identifier:"DK12345678",identifierKind:"dk_cvr"}],source:"test",observedAt:"2026-01-01T00:00:00.000Z",reviewAssertion:"reviewed",actor:"user:test"});linkPartyRole(registry,{partyId:p.partyId,companySlug:"alpha",role:"issuer",actor:"user:test"});expect(planDocumentPartyLink(ledger,registry,{documentId:1,companySlug:"alpha",role:"issuer"})).toEqual({ok:false,errors:["NO_IDENTIFIER_EVIDENCE"]});expect(planDocumentPartyLink(ledger,registry,{documentId:1,companySlug:"alpha",role:"vendor",jurisdiction:"DK",identifierKind:"dk_cvr",identifier:"DK12345678"})).toEqual({ok:false,errors:["SCOPE_MISMATCH"]});linkLegacyPartyReference(registry,{partyId:p.partyId,companySlug:"alpha",legacyKind:"vendor",legacyId:"old",actor:"user:test"});expect(planDocumentPartyLink(ledger,registry,{documentId:1,companySlug:"alpha",role:"vendor",legacyKind:"vendor",legacyId:"old"})).toEqual({ok:false,errors:["LEGACY_REFERENCE_UNREVIEWED"]}); registry.close();ledger.close();});
 test("binds immutable evidence, applies idempotently and supersedes append-only",()=>{const {registry,ledger}=setup();const p=createParty(registry,{kind:"organization",name:"Synthetic",identifiers:[{country:"DK",identifier:"DK12345678",identifierKind:"dk_cvr"}],source:"test",observedAt:"2026-01-01T00:00:00.000Z",reviewAssertion:"reviewed",actor:"user:test"});linkPartyRole(registry,{partyId:p.partyId,companySlug:"alpha",role:"vendor",actor:"user:test"});const input={documentId:1,companySlug:"alpha",role:"vendor" as const,jurisdiction:"DK",identifierKind:"dk_cvr",identifier:"DK12345678"};const plan=planDocumentPartyLink(ledger,registry,input);expect(plan.ok).toBeTrue();if(!plan.ok)return;expect(applyDocumentPartyLink(ledger,registry,{...input,planHash:"bad",confirm:true,actor:"user:test",principal:"user:test"})).toEqual({ok:false,errors:["PLAN_HASH_MISMATCH"]});const applied=applyDocumentPartyLink(ledger,registry,{...input,planHash:plan.plan.planHash,confirm:true,actor:"user:test",principal:"user:test"});expect(applied).toMatchObject({ok:true,idempotent:false});expect(applyDocumentPartyLink(ledger,registry,{...input,planHash:plan.plan.planHash,confirm:true,actor:"user:test",principal:"user:test"})).toMatchObject({ok:true,idempotent:true});expect(()=>ledger.run("UPDATE document_party_link_events SET actor='x'")).toThrow("append-only");expect(supersedeDocumentPartyLink(ledger,{documentId:1,role:"vendor",planHash:plan.plan.planHash,reason:"corrected evidence",confirm:true,actor:"user:test",principal:"user:test"})).toMatchObject({ok:true});expect(ledger.query("SELECT count(*) n FROM current_document_party_links").get()).toEqual({n:0});registry.close();ledger.close();});
 test("records a confirmed immutable internal no-external-party decision",()=>{const {registry,ledger}=setup();ledger.run("UPDATE documents SET document_type='internal_voucher' WHERE id=1");const before=ledger.query("SELECT sha256_hash,payload_json,vat_amount FROM documents WHERE id=1").get();const first=decideInternalNoExternalParty(ledger,{documentId:1,reason:"Synthetic internal transfer",confirm:true,actor:"user:test",principal:"user:test",idempotencyKey:"internal-1"});expect(first).toMatchObject({ok:true,idempotent:false});expect(documentResolution(ledger,1).state).toBe("internal_no_external_party");expect(decideInternalNoExternalParty(ledger,{documentId:1,reason:"Synthetic internal transfer",confirm:true,actor:"user:test",principal:"user:test",idempotencyKey:"internal-1"})).toMatchObject({ok:true,idempotent:true});expect(decideInternalNoExternalParty(ledger,{documentId:1,reason:"different",confirm:true,actor:"user:test",principal:"user:test",idempotencyKey:"internal-1"})).toEqual({ok:false,errors:["IDEMPOTENCY_CONFLICT"]});expect(supersedeInternalNoExternalParty(ledger,{documentId:1,decisionHash:first.decisionHash,reason:"External evidence received",confirm:true,actor:"user:test",principal:"user:test"})).toMatchObject({ok:true});expect(documentResolution(ledger,1)).toMatchObject({state:"unresolved",reason:"NO_PARTY_DECISION"});expect(ledger.query("SELECT sha256_hash,payload_json,vat_amount FROM documents WHERE id=1").get()).toEqual(before);registry.close();ledger.close();});
 test("requires explicit supersession before changing the current resolution",()=>{const {registry,ledger}=setup();const party=createParty(registry,{kind:"organization",name:"Canonical vendor",identifiers:[{country:"DK",identifier:"DK12345678",identifierKind:"dk_cvr"}],source:"test",observedAt:"2026-01-01T00:00:00.000Z",reviewAssertion:"reviewed",actor:"user:test"});linkPartyRole(registry,{partyId:party.partyId,companySlug:"alpha",role:"vendor",actor:"user:test"});const input={documentId:1,companySlug:"alpha",role:"vendor" as const,jurisdiction:"DK",identifierKind:"dk_cvr",identifier:"DK12345678"};const plan=planDocumentPartyLink(ledger,registry,input);if(!plan.ok)throw new Error("expected plan");ledger.run("UPDATE documents SET document_type='internal_voucher' WHERE id=1");const internal=decideInternalNoExternalParty(ledger,{documentId:1,reason:"internal",confirm:true,actor:"user:test",principal:"user:test"});expect(internal.ok).toBeTrue();expect(applyDocumentPartyLink(ledger,registry,{...input,planHash:plan.plan.planHash,confirm:true,actor:"user:test",principal:"user:test"})).toEqual({ok:false,errors:["CURRENT_STATE_CONFLICT"]});if(!internal.ok)throw new Error("expected internal decision");expect(supersedeInternalNoExternalParty(ledger,{documentId:1,decisionHash:internal.decisionHash,reason:"external evidence found",confirm:true,actor:"user:test",principal:"user:test"}).ok).toBeTrue();expect(applyDocumentPartyLink(ledger,registry,{...input,planHash:plan.plan.planHash,confirm:true,actor:"user:test",principal:"user:test"}).ok).toBeTrue();registry.close();ledger.close();});
});

describe("#640 reviewed source observation",()=>{
  function sourceSetup(){
    const ctx=setup(), store=join(ctx.root,"documents","originals"); mkdirSync(store,{recursive:true});
    const bytes=Buffer.from("synthetic posted source with exact legal identity"); const path=join(store,"legacy.pdf"); writeFileSync(path,bytes);
    const sha=createHash("sha256").update(bytes).digest("hex");
    ctx.ledger.query("UPDATE documents SET sha256_hash=?,stored_path=?,mime_type='application/pdf',status='posted',sender_name='Legacy display',sender_address='Old formatting',supplier_country_code=NULL,supplier_identifier_kind=NULL,sender_vat_cvr=NULL WHERE id=1").run(sha,path);
    return {...ctx,sha};
  }
  test("links a posted legacy document from immutable exact-ID evidence and supplements only missing contact identity",()=>{
    const {root,registry,ledger,sha}=sourceSetup();
    const party=createParty(registry,{kind:"organization",name:"Canonical Merchant",identifiers:[{country:"DE",identifierKind:"eu_vat",identifier:"DE123456789"}],source:"synthetic",observedAt:"2026-01-01T00:00:00.000Z",reviewAssertion:"reviewed",actor:"user:reviewer"});
    linkPartyRole(registry,{partyId:party.partyId,companySlug:"alpha",role:"vendor",actor:"user:reviewer"});
    ledger.query("INSERT INTO vendors(id,name,address,identity_status,notes) VALUES(7,'Canonical Merchant','Example Street 1','human_resolution_required','original note')").run();
    const sourceReview={observedName:"CANONICAL   MERCHANT",observedAddress:"Example Street 1",jurisdiction:"DE",identifierKind:"eu_vat" as const,identifier:"DE 123456789",sourceReference:"visible legal identifier",sourceLocation:"page 1, supplier block",rationale:"reviewed against immutable original",vendorId:7};
    const input={documentId:1,companySlug:"alpha",partyId:party.partyId,role:"vendor" as const,sourceReview};
    const beforeDoc=ledger.query("SELECT * FROM documents WHERE id=1").get(), beforeJournals=ledger.query("SELECT count(*) n FROM journal_entries").get();
    const plan=planDocumentPartyLink(ledger,registry,input,root); expect(plan.ok).toBeTrue(); if(!plan.ok)return;
    expect(plan.plan).toMatchObject({documentSha256:sha,evidence:{kind:"reviewed_source_observation",accountingEffect:"none",taxEffect:"none",contactChange:{vendorId:7}}});
    expect(applyDocumentPartyLink(ledger,registry,{...input,planHash:plan.plan.planHash,confirm:true,actor:"agent:reviewer",principal:"service-account:reviewer",idempotencyKey:"source-review-1"},root)).toMatchObject({ok:true,idempotent:false});
    expect(applyDocumentPartyLink(ledger,registry,{...input,planHash:plan.plan.planHash,confirm:true,actor:"agent:other",principal:"service-account:reviewer",idempotencyKey:"source-review-1"},root)).toMatchObject({ok:true,idempotent:true});
    expect(ledger.query("SELECT vat_or_cvr,country_code,identifier_kind,identity_status,notes FROM vendors WHERE id=7").get()).toEqual({vat_or_cvr:"DE123456789",country_code:"DE",identifier_kind:"eu_vat",identity_status:"resolved",notes:"original note"});
    expect(ledger.query("SELECT * FROM documents WHERE id=1").get()).toEqual(beforeDoc); expect(ledger.query("SELECT count(*) n FROM journal_entries").get()).toEqual(beforeJournals);
    const event=ledger.query("SELECT evidence_kind,evidence_json,actor,principal FROM document_party_link_events").get() as any; expect(event).toMatchObject({evidence_kind:"reviewed_source_observation",actor:"agent:reviewer",principal:"service-account:reviewer"}); expect(JSON.parse(event.evidence_json).source.documentSha256).toBe(sha);
    expect(()=>ledger.run("UPDATE document_party_link_events SET actor='x'")).toThrow("append-only"); registry.close();ledger.close();
  });
  test("supports explicit ID-less non-EU review and bank counterparty without implying supplier invoice or VAT",()=>{
    const {root,registry,ledger}=sourceSetup(); ledger.run("UPDATE documents SET document_type='internal_voucher' WHERE id=1");
    const party=createParty(registry,{kind:"financial_institution",name:"Foreign Bank",source:"synthetic",observedAt:"2026-01-01T00:00:00.000Z",reviewAssertion:"reviewed",actor:"user:reviewer"}); linkPartyRole(registry,{partyId:party.partyId,companySlug:"alpha",role:"bank",actor:"user:reviewer"});
    const input={documentId:1,companySlug:"alpha",partyId:party.partyId,role:"bank" as const,sourceReview:{observedName:"Foreign Bank",jurisdiction:"US",identifierKind:"non_eu" as const,sourceReference:"bank evidence",sourceLocation:"statement row 4",rationale:"reviewed counterparty, not preparer"}};
    const plan=planDocumentPartyLink(ledger,registry,input,root); expect(plan.ok).toBeTrue(); if(!plan.ok)return; expect(plan.plan.evidence).toMatchObject({observedIdentity:{identifier:null},accountingEffect:"none",taxEffect:"none",contactChange:null});
    expect(applyDocumentPartyLink(ledger,registry,{...input,planHash:plan.plan.planHash,confirm:true,actor:"user:reviewer",principal:"service-account:reviewer",idempotencyKey:"bank-review"},root).ok).toBeTrue(); registry.close();ledger.close();
  });
  test("fails closed for conflicting, ambiguous, stale, unbound and materially changed evidence",()=>{
    const {root,registry,ledger}=sourceSetup();
    const party=createParty(registry,{kind:"organization",name:"Expected",identifiers:[{country:"DE",identifierKind:"eu_vat",identifier:"DE123456789"}],source:"synthetic",observedAt:"2026-01-01T00:00:00.000Z",reviewAssertion:"reviewed",actor:"user:reviewer"}); linkPartyRole(registry,{partyId:party.partyId,companySlug:"alpha",role:"vendor",actor:"user:reviewer"});
    const base={documentId:1,companySlug:"alpha",partyId:party.partyId,role:"vendor" as const,sourceReview:{observedName:"Expected",jurisdiction:"DE",identifierKind:"eu_vat" as const,identifier:"DE123456789",sourceReference:"legal ID",sourceLocation:"page 1",rationale:"reviewed"}};
    expect(planDocumentPartyLink(ledger,registry,base)).toEqual({ok:false,errors:["SOURCE_REVIEW_INVALID"]});
    ledger.run("UPDATE documents SET supplier_country_code='FR'"); expect(planDocumentPartyLink(ledger,registry,base,root)).toEqual({ok:false,errors:["IDENTIFIER_CONFLICT"]}); ledger.run("UPDATE documents SET supplier_country_code=NULL");
    const plan=planDocumentPartyLink(ledger,registry,base,root); expect(plan.ok).toBeTrue(); if(!plan.ok)return;
    writeFileSync(join(root,"documents","originals","legacy.pdf"),"drift"); expect(applyDocumentPartyLink(ledger,registry,{...base,planHash:plan.plan.planHash,confirm:true,actor:"user:reviewer",principal:"service-account:reviewer",idempotencyKey:"drift"},root)).toEqual({ok:false,errors:["SOURCE_EVIDENCE_INVALID"]});
    expect(ledger.query("SELECT count(*) n FROM document_party_link_events").get()).toEqual({n:0}); registry.close();ledger.close();
  });
  test("rejects a competing reviewed apply for the same role",()=>{
    const {root,registry,ledger}=sourceSetup();
    for(const id of ["party-first","party-second"]){const party=createParty(registry,{partyId:id,kind:"organization",name:"Shared Reviewed Name",source:"synthetic",observedAt:"2026-01-01T00:00:00.000Z",reviewAssertion:"reviewed",actor:"user:reviewer"});linkPartyRole(registry,{partyId:party.partyId,companySlug:"alpha",role:"vendor",actor:"user:reviewer"});}
    const sourceReview={observedName:"Shared Reviewed Name",jurisdiction:"US",identifierKind:"non_eu" as const,sourceReference:"source",sourceLocation:"page 1",rationale:"reviewed"};
    const first={documentId:1,companySlug:"alpha",partyId:"party-first",role:"vendor" as const,sourceReview}, second={...first,partyId:"party-second"};
    const firstPlan=planDocumentPartyLink(ledger,registry,first,root), secondPlan=planDocumentPartyLink(ledger,registry,second,root); if(!firstPlan.ok||!secondPlan.ok)throw new Error("expected competing plans");
    expect(applyDocumentPartyLink(ledger,registry,{...first,planHash:firstPlan.plan.planHash,confirm:true,actor:"user:first",principal:"service-account:first",idempotencyKey:"first"},root).ok).toBeTrue();
    expect(applyDocumentPartyLink(ledger,registry,{...second,planHash:secondPlan.plan.planHash,confirm:true,actor:"user:second",principal:"service-account:second",idempotencyKey:"second"},root)).toEqual({ok:false,errors:["CURRENT_STATE_CONFLICT"]}); registry.close();ledger.close();
  });
});
