import { afterEach, describe, expect, test } from "bun:test";
import { mkdtempSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { initWorkspace } from "../../src/core/workspace";
import { openWorkspaceControlDb } from "../../src/core/workspace-control";
import { migrate, openDb } from "../../src/core/db";
import { companyPaths } from "../../src/core/paths";
import { addBankAccount } from "../../src/core/bank";
import { postJournalEntry, seedAccounts } from "../../src/core/ledger";
import { createParty, linkPartyRole } from "../../src/core/party-registry";
import { applyDocumentPartyLink, decideInternalNoExternalParty, planDocumentPartyLink } from "../../src/core/document-party-links";
import { applyPartyCoverage, planPartyCoverage, projectPartyCoverage } from "../../src/core/party-coverage";

const roots:string[]=[];
function setup(){
  const root=mkdtempSync(join(tmpdir(),"party-coverage-"));roots.push(root);initWorkspace(root);const db=openDb(companyPaths(root).db);migrate(db);seedAccounts(db);db.run("INSERT INTO companies(id,name) VALUES(1,'Synthetic')");const bank=addBankAccount(db,{name:"Bank",slug:"bank",ledgerAccountNo:"2000"}).account!;
  const control=openWorkspaceControlDb(root);const exact=createParty(control,{partyId:"party-exact",kind:"organization",name:"Exact Merchant",identifiers:[{country:"DE",identifierKind:"eu_vat",identifier:"DE123456789"}],source:"synthetic",observedAt:"2026-01-01T00:00:00.000Z",reviewAssertion:"reviewed",actor:"user:test"});linkPartyRole(control,{partyId:exact.partyId,companySlug:"alpha",role:"vendor",actor:"user:test"});
  const linked=createParty(control,{partyId:"party-linked",kind:"organization",name:"Linked Merchant",identifiers:[{country:"DK",identifierKind:"dk_cvr",identifier:"DK12345678"}],source:"synthetic",observedAt:"2026-01-01T00:00:00.000Z",reviewAssertion:"reviewed",actor:"user:test"});linkPartyRole(control,{partyId:linked.partyId,companySlug:"alpha",role:"vendor",actor:"user:test"});
  for(const id of ["ambiguous-a","ambiguous-b"]){const party=createParty(control,{partyId:id,kind:"organization",name:"Same Name",source:"synthetic",observedAt:"2026-01-01T00:00:00.000Z",reviewAssertion:"reviewed",actor:"user:test"});linkPartyRole(control,{partyId:party.partyId,companySlug:"alpha",role:"vendor",actor:"user:test"});}
  const related=createParty(control,{partyId:"party-related",kind:"organization",name:"Related Company",identifiers:[{country:"DK",identifierKind:"dk_cvr",identifier:"DK87654321"}],source:"synthetic",observedAt:"2026-01-01T00:00:00.000Z",reviewAssertion:"reviewed",actor:"user:test"});linkPartyRole(control,{partyId:related.partyId,companySlug:"alpha",role:"related_company",actor:"user:test"});
  const addDoc=(id:number,type:string,name:string|null,country:string|null,kind:string|null,identifier:string|null)=>db.query("INSERT INTO documents(id,source,sha256_hash,payload_json,status,document_type,sender_name,supplier_country_code,supplier_identifier_kind,sender_vat_cvr) VALUES(?,?,?,?,?,?,?,?,?,?)").run(id,"synthetic",String(id).repeat(64).slice(0,64),"{}","posted",type,name,country,kind,identifier);
  addDoc(1,"purchase_sale","Linked Merchant","DK","dk_cvr","DK12345678");addDoc(2,"internal_voucher",null,null,null,null);addDoc(3,"purchase_sale","Exact Merchant","DE","eu_vat","DE123456789");addDoc(4,"purchase_sale","Same Name",null,null,null);
  const journals:number[]=[];for(let id=1;id<=7;id++){db.query("INSERT INTO bank_transactions(id,transaction_date,text,amount,currency,transaction_hash,bank_account_id) VALUES(?,?,?,?,?,?,?)").run(id,`2026-01-0${id}`,`Bank ${id}`,-10-id,"DKK",`bank-${id}`,bank.id);if(id===5)continue;const documentId=id===1?1:id===2?2:id===3||id===6?3:id===4?4:undefined;const posted=postJournalEntry(db,{transactionDate:`2026-01-0${id}`,text:`Journal ${id}`,documentId,sourceBankTransactionId:id,createdBy:"agent:test",lines:[{accountNo:"7000",debitAmount:10+id},{accountNo:"2000",creditAmount:10+id}]});if(!posted.ok)throw new Error(posted.errors.join(","));journals[id]=Number(posted.entryId);}
  const linkedInput={documentId:1,companySlug:"alpha",partyId:"party-linked",role:"vendor" as const,jurisdiction:"DK",identifierKind:"dk_cvr",identifier:"DK12345678"};const linkedPlan=planDocumentPartyLink(db,control,linkedInput);if(!linkedPlan.ok)throw new Error("link plan");applyDocumentPartyLink(db,control,{...linkedInput,planHash:linkedPlan.plan.planHash,confirm:true,actor:"user:test",principal:"service-account:test",idempotencyKey:"linked"});
  decideInternalNoExternalParty(db,{documentId:2,reason:"Synthetic internal evidence",confirm:true,actor:"user:test",principal:"service-account:test",idempotencyKey:"internal"});
  return {root,db,control};
}
afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});

describe("#644 deterministic party coverage",()=>{
  test("CLI exposes the same read-only projection and plan hash",async()=>{const {root,db,control}=setup();db.close();control.close();const run=async(command:string)=>{const process=Bun.spawn(["bun","run","src/cli.ts","documents",command,"--company",root,"--workspace",root,"--company-slug","alpha"],{stdout:"pipe",stderr:"pipe"});const stdout=await new Response(process.stdout).text(),stderr=await new Response(process.stderr).text();expect(await process.exited,stderr).toBe(0);return JSON.parse(stdout);};const projected=await run("party-coverage"),planned=await run("party-coverage-plan");expect(projected).toMatchObject({ok:true,totals:{exact_candidate:2}});expect(projected.rows.find((row:any)=>row.bankTransactionId===1)).toMatchObject({status:"linked"});expect(projected.planHash).toBe(planned.plan.planHash);});
  test("projects every bank row into exactly one status and deduplicates document operations",()=>{const {db,control}=setup();const coverage=projectPartyCoverage(db,control,{companySlug:"alpha"});expect(coverage.totals).toEqual({linked:1,resolved_no_external_party:1,exact_candidate:2,ambiguous:1,missing_source:2});expect(coverage.rows).toHaveLength(7);expect(coverage.rows.find(row=>row.bankTransactionId===4)).toMatchObject({status:"ambiguous",candidate:{candidates:[{provenance:"name_collision_not_evidence"},{provenance:"name_collision_not_evidence"}]}});const plan=planPartyCoverage(db,control,{companySlug:"alpha"});expect(plan.plan.operations.filter(operation=>operation.kind==="document_link")).toHaveLength(1);expect(plan.plan.operations[0]).toMatchObject({documentId:3});expect(coverage.planHash).toBe(plan.plan.planHash);db.close();control.close();});
  test("applies exact document and explicit bank decisions atomically, idempotently and without economic mutation",()=>{const {root,db,control}=setup();const before={journals:db.query("SELECT * FROM journal_entries ORDER BY id").all(),lines:db.query("SELECT * FROM journal_lines ORDER BY id").all(),banks:db.query("SELECT * FROM bank_transactions ORDER BY id").all(),documents:db.query("SELECT * FROM documents ORDER BY id").all()};const decisions=[{bankTransactionId:7,partyId:"party-related",role:"related_company" as const,evidenceReference:"reviewed disposition",rationale:"synthetic related-company transfer"},{bankTransactionId:5,noExternalParty:true,evidenceReference:"unreconciled cannot qualify",rationale:"invalid"}];expect(()=>planPartyCoverage(db,control,{companySlug:"alpha",decisions})).toThrow("reconciled missing-source");const valid=[decisions[0]!,{bankTransactionId:7,noExternalParty:true,evidenceReference:"x",rationale:"x"}];expect(()=>planPartyCoverage(db,control,{companySlug:"alpha",decisions:valid})).toThrow();const plan=planPartyCoverage(db,control,{companySlug:"alpha",decisions:[decisions[0]!]});const input={companySlug:"alpha",decisions:[decisions[0]!],planHash:plan.plan.planHash,idempotencyKey:"coverage-1",confirm:true,actor:"agent:test",principal:"service-account:test"};expect(applyPartyCoverage(db,control,root,input)).toMatchObject({ok:true,idempotent:false,applied:2});expect(applyPartyCoverage(db,control,root,input)).toMatchObject({ok:true,idempotent:true,applied:2});const after=projectPartyCoverage(db,control,{companySlug:"alpha"});expect(after.rows.find(row=>row.bankTransactionId===7)).toMatchObject({status:"linked",candidate:{partyId:"party-related",role:"related_company"}});expect(after.rows.filter(row=>row.documentId===3).every(row=>row.status==="linked")).toBeTrue();expect({journals:db.query("SELECT * FROM journal_entries ORDER BY id").all(),lines:db.query("SELECT * FROM journal_lines ORDER BY id").all(),banks:db.query("SELECT * FROM bank_transactions ORDER BY id").all(),documents:db.query("SELECT * FROM documents ORDER BY id").all()}).toEqual(before);expect(()=>db.run("UPDATE party_coverage_batch_events SET actor='x'")).toThrow("append-only");db.close();control.close();});
  test("records a reviewed no-external-party bank decision without inventing a party",()=>{const {root,db,control}=setup();const decision={bankTransactionId:7,noExternalParty:true,evidenceReference:"reviewed internal settlement",rationale:"synthetic tax settlement"};const plan=planPartyCoverage(db,control,{companySlug:"alpha",decisions:[decision]});const input={companySlug:"alpha",decisions:[decision],planHash:plan.plan.planHash,idempotencyKey:"coverage-no-party",confirm:true,actor:"user:reviewer",principal:"service-account:test"};expect(applyPartyCoverage(db,control,root,input)).toMatchObject({ok:true,idempotent:false,applied:2});expect(projectPartyCoverage(db,control,{companySlug:"alpha"}).rows.find(row=>row.bankTransactionId===7)).toMatchObject({status:"resolved_no_external_party",candidate:null});expect(()=>db.run("UPDATE party_coverage_bank_resolution_events SET rationale='changed'")).toThrow("append-only");db.close();control.close();});
  test("fails closed when the reviewed population changes",()=>{const {root,db,control}=setup();const plan=planPartyCoverage(db,control,{companySlug:"alpha"});db.query("INSERT INTO bank_transactions(id,transaction_date,text,amount,currency,transaction_hash,bank_account_id) SELECT 8,'2026-01-08','Drift',-1,'DKK','bank-8',id FROM bank_accounts LIMIT 1").run();expect(()=>applyPartyCoverage(db,control,root,{companySlug:"alpha",planHash:plan.plan.planHash,idempotencyKey:"stale",confirm:true,actor:"agent:test",principal:"service-account:test"})).toThrow("stale party coverage plan");expect(db.query("SELECT count(*) n FROM party_coverage_batch_events").get()).toEqual({n:0});db.close();control.close();});
});
