import { describe, expect, test } from "bun:test";
import { Database } from "bun:sqlite";
import { migrate } from "../../src/core/db";
import { createPurchaseCase, getPurchaseCase, purchaseCaseSourceFingerprint, reviewPurchaseCase } from "../../src/core/purchase-cases";

const actor={createdBy:"agent:test",createdByProgram:"test"};
function fixture(){ const db=new Database(":memory:"); migrate(db); db.run("INSERT INTO companies(name,cvr) VALUES(?,?)","Synthetic company","12345678"); db.run("INSERT INTO bank_transactions(transaction_date,amount,currency,text,transaction_hash) VALUES(?,?,?,?,?)","2026-01-02",-125,"DKK","Synthetic purchase","a".repeat(64)); return db; }
describe("purchase cases",()=>{
  test("keeps a source-bound append-only provisional case outside the ledger",()=>{const db=fixture(); const before=db.query("SELECT count(*) count FROM journal_entries").get() as {count:number}; const created=createPurchaseCase(db,{caseId:"synthetic-bank-purchase",source:{kind:"bank_transaction",id:1},actor}); expect(created).toMatchObject({ok:true,purchaseCase:{accountingProgress:"unposted",documentationOutcome:"unresolved"}}); expect(db.query("SELECT count(*) count FROM journal_entries").get()).toEqual(before); expect(()=>db.run("UPDATE purchase_case_events SET note='tamper'")).toThrow("append-only"); expect(createPurchaseCase(db,{caseId:"duplicate-source",source:{kind:"bank_transaction",id:1},actor})).toMatchObject({ok:false,errors:["PURCHASE_CASE_SOURCE_ALREADY_HAS_CASE"]}); db.close();});
  test("requires exact current source fingerprint and version for review",()=>{const db=fixture(); const created=createPurchaseCase(db,{caseId:"reviewable-bank-purchase",source:{kind:"bank_transaction",id:1},actor}); if(!created.ok)throw new Error(created.errors.join(",")); const fingerprint=purchaseCaseSourceFingerprint(db,{kind:"bank_transaction",id:1})!; expect(reviewPurchaseCase(db,{caseId:created.purchaseCase.caseId,expectedVersion:2,expectedSourceFingerprint:fingerprint,documentationOutcome:"ordinary_evidence_sufficient",actor})).toMatchObject({ok:false,errors:["STALE_PURCHASE_CASE_VERSION"]}); db.run("UPDATE bank_transactions SET text=? WHERE id=1","Changed synthetic source"); expect(reviewPurchaseCase(db,{caseId:created.purchaseCase.caseId,expectedVersion:1,expectedSourceFingerprint:fingerprint,documentationOutcome:"ordinary_evidence_sufficient",actor})).toMatchObject({ok:false,errors:["STALE_PURCHASE_CASE_SOURCE"]}); expect(getPurchaseCase(db,created.purchaseCase.caseId)?.version).toBe(1); db.close();});
});
